using System;
using System.Collections.Generic;
using WinTune.Models;
using WinTune.Services;

namespace WinTune.Catalog;

/// <summary>
/// Git 命令列完整操作目錄（喺選中嘅儲存庫執行）· The COMPLETE git CLI surface as data-driven operations.
/// 補充 <see cref="GitOperations"/>（已涵蓋約 111 個常用操作），呢度補返賸低嘅 git 指令家族，務求兩者合埋盡晒成個 git CLI。
/// Complements <see cref="GitOperations"/> — adds everything the common-ops catalog does NOT already cover (150+ ops).
/// 聚合器會按 Id 去重；本檔內所有 gitx. 前綴 Id 各自唯一。The aggregator dedups by Id; every gitx. id here is unique within this file.
/// </summary>
public static class GitCliOperations
{
    public static IEnumerable<TweakDefinition> All() => new List<TweakDefinition>
    {
        // ===== setup / init / clone =====
        GitTweak.Git("gitx.init", "Init repository", "初始化儲存庫",
            "Initialise a new git repository in the current folder.", "喺而家個資料夾起一個新嘅 git 儲存庫。",
            "Init", "初始化", "init", keywords: "init,新建,初始化"),
        GitTweak.Git("gitx.init-bare", "Init bare repository", "初始化裸儲存庫",
            "Create a bare repository (no working tree) for use as a server-side remote.", "起一個冇工作區嘅裸 repo，做遠端 server 用。",
            "Init", "初始化", "init --bare", keywords: "init,bare,裸,遠端"),
        GitTweak.Git("gitx.init-branch", "Init with branch name", "初始化並命名分支",
            "Initialise a repository with main as the initial branch name.", "起 repo 嘅同時，將初始分支改名做 main。",
            "Init", "初始化", "init --initial-branch=main", keywords: "init,branch,main,初始分支"),
        GitTweak.Git("gitx.clone-https", "Clone (https)", "複製（https）",
            "Clone a repository over HTTPS into the current folder.", "用 HTTPS 將一個 repo 複製落嚟。",
            "Clone", "複製", "clone https://github.com/user/repo.git", keywords: "clone,https,複製"),
        GitTweak.Git("gitx.clone-depth", "Shallow clone (--depth 1)", "淺複製（--depth 1）",
            "Clone only the latest commit to save time and space.", "淨係複製最新嗰個提交，慳時間慳空間。",
            "Clone", "複製", "clone --depth 1 https://github.com/user/repo.git", keywords: "clone,depth,shallow,淺複製"),
        GitTweak.Git("gitx.clone-bare", "Clone bare", "裸複製",
            "Clone a repository as a bare mirror with no working tree.", "將 repo 複製做一個冇工作區嘅裸鏡像。",
            "Clone", "複製", "clone --bare https://github.com/user/repo.git", keywords: "clone,bare,裸,鏡像"),
        GitTweak.Git("gitx.clone-recursive", "Clone with submodules", "複製連子模組",
            "Clone a repository and recursively fetch all submodules.", "複製 repo 嘅同時，遞迴咁抓埋所有子模組。",
            "Clone", "複製", "clone --recursive https://github.com/user/repo.git", keywords: "clone,recursive,submodule,子模組"),
        GitTweak.Git("gitx.clone-branch", "Clone a specific branch", "複製指定分支",
            "Clone only the 'feature' branch from the remote.", "淨係由遠端複製 'feature' 嗰條分支。",
            "Clone", "複製", "clone --branch feature https://github.com/user/repo.git", keywords: "clone,branch,分支"),
        GitTweak.Git("gitx.version", "Git version", "Git 版本",
            "Print the installed git version.", "印返而家裝咗嘅 git 版本。",
            "Show", "顯示", "version", keywords: "version,版本"),
        GitTweak.Git("gitx.help", "Git help", "Git 說明",
            "Show the top-level git help overview.", "顯示 git 嘅總覽說明。",
            "Help", "說明", "help", keywords: "help,說明,幫助"),
        GitTweak.Git("gitx.var-list", "List logical vars", "列出邏輯變數",
            "List git's logical variables such as GIT_EDITOR and GIT_AUTHOR_IDENT.", "列出 git 嘅邏輯變數，例如 GIT_EDITOR、GIT_AUTHOR_IDENT。",
            "List", "列出", "var -l", keywords: "var,variable,邏輯變數"),

        // ===== config =====
        GitTweak.Git("gitx.config-set-name-global", "Set global user.name", "設定全域 user.name",
            "Set your global commit author name.", "設定全域嘅提交作者名。",
            "Set", "設定", "config --global user.name \"Your Name\"", keywords: "config,global,name,作者名"),
        GitTweak.Git("gitx.config-set-email-global", "Set global user.email", "設定全域 user.email",
            "Set your global commit author email.", "設定全域嘅提交作者電郵。",
            "Set", "設定", "config --global user.email \"you@example.com\"", keywords: "config,global,email,電郵"),
        GitTweak.Git("gitx.config-autocrlf", "Set core.autocrlf", "設定 core.autocrlf",
            "Configure automatic line-ending conversion (true on Windows).", "設定自動換行轉換（Windows 一般用 true）。",
            "Set", "設定", "config --global core.autocrlf true", keywords: "config,autocrlf,換行,line ending"),
        GitTweak.Git("gitx.config-default-branch", "Set init.defaultBranch", "設定預設分支名",
            "Set the default branch name used for new repositories to main.", "將新 repo 嘅預設分支名設做 main。",
            "Set", "設定", "config --global init.defaultBranch main", keywords: "config,defaultbranch,main,預設分支"),
        GitTweak.Git("gitx.config-pull-rebase", "Set pull.rebase", "設定 pull.rebase",
            "Make 'git pull' rebase instead of merge by default.", "令 'git pull' 預設用變基而唔係合併。",
            "Set", "設定", "config --global pull.rebase true", keywords: "config,pull,rebase,變基"),
        GitTweak.Git("gitx.config-alias", "Add an alias", "新增別名",
            "Add a global alias 'st' for 'status'.", "新增全域別名 'st' 等於 'status'。",
            "Set", "設定", "config --global alias.st status", keywords: "config,alias,別名,捷徑"),
        GitTweak.Git("gitx.config-get-regexp", "Get config by regex", "用正則攞設定",
            "List all alias.* configuration entries via regex match.", "用正則列出所有 alias.* 嘅設定項目。",
            "Show", "顯示", "config --get-regexp ^alias\\.", keywords: "config,regexp,正則,別名"),
        GitTweak.Git("gitx.config-unset", "Unset a config value", "清除設定值",
            "Remove the configured core.editor value.", "清除咗已設定嘅 core.editor。",
            "Unset", "清除", "config --unset core.editor", destructive: true, keywords: "config,unset,清除,移除"),
        GitTweak.Git("gitx.config-edit-global", "Edit global config", "編輯全域設定",
            "Open the global git config file in your editor.", "用你嘅編輯器打開全域 git 設定檔。",
            "Edit", "編輯", "config --edit --global", keywords: "config,edit,global,編輯,全域"),
        GitTweak.Git("gitx.config-show-origin", "Config with origins", "設定連來源",
            "List every config value alongside the file it came from.", "列出每個設定值，連埋佢由邊個檔案嚟。",
            "List", "列出", "config --list --show-origin", keywords: "config,origin,來源,列出"),

        // ===== snapshot / stage =====
        GitTweak.Git("gitx.add-all-patch", "Stage all (note: -p)", "暫存全部（備註 -p）",
            "Stage everything with add -A. For interactive hunk-by-hunk staging run 'git add -p' in a terminal.", "用 add -A 暫存全部。想逐段揀就喺終端機行 'git add -p'。",
            "Stage", "暫存", "add -A", keywords: "add,patch,interactive,逐段,暫存"),
        GitTweak.Git("gitx.add-intent", "Add intent-to-add", "標記將會新增",
            "Record that README.md will be added, so it shows in diffs without staging its content.", "登記 README.md 將會加入，令佢喺 diff 出到但唔暫存內容。",
            "Mark", "標記", "add --intent-to-add README.md", keywords: "add,intent-to-add,N,新增"),
        GitTweak.Git("gitx.add-renormalize", "Renormalize line endings", "重新正規化換行",
            "Re-apply clean/smudge filters and line-ending normalisation to all tracked files.", "對所有已追蹤檔案重新套用 clean/smudge 同換行正規化。",
            "Stage", "暫存", "add --renormalize .", keywords: "add,renormalize,換行,正規化"),
        GitTweak.Git("gitx.restore-source", "Restore from older commit", "由舊提交還原",
            "Restore README.md in the working tree from the commit before HEAD.", "由 HEAD 前一個提交將 README.md 還原返落工作區。",
            "Restore", "還原", "restore --source=HEAD~1 README.md", destructive: true, keywords: "restore,source,還原,舊版"),
        GitTweak.Git("gitx.restore-worktree-staged", "Restore worktree & index", "還原工作區同索引",
            "Discard changes to README.md in both the working tree and the staging area.", "將 README.md 喺工作區同暫存區嘅改動一齊丟棄。",
            "Restore", "還原", "restore --worktree --staged README.md", destructive: true, keywords: "restore,worktree,staged,還原"),
        GitTweak.Git("gitx.reset-head-file", "Unstage one file", "取消暫存單檔",
            "Remove README.md from the staging area, keeping its changes.", "將 README.md 喺暫存區攞返出嚟，保留改動。",
            "Unstage", "取消暫存", "reset HEAD README.md", keywords: "reset,head,unstage,取消暫存"),
        GitTweak.Git("gitx.reset-hard-commit", "Hard reset to a commit", "硬重置到提交",
            "Discard everything and move the branch to a given commit. Loses uncommitted and later work.", "丟棄晒所有嘢，將分支移到指定提交，會整唔見未提交同之後嘅工作。",
            "Reset", "重置", "reset --hard COMMIT_SHA", destructive: true, keywords: "reset,hard,commit,重置,丟棄"),
        GitTweak.Git("gitx.reset-keep", "Reset (--keep)", "重置（--keep）",
            "Reset to a commit but keep local changes that don't conflict.", "重置到指定提交，但保留唔衝突嘅本地改動。",
            "Reset", "重置", "reset --keep COMMIT_SHA", destructive: true, keywords: "reset,keep,重置"),
        GitTweak.Git("gitx.reset-merge", "Reset (--merge)", "重置（--merge）",
            "Reset to a commit while keeping unmerged local changes.", "重置到指定提交，同時保留未合併嘅本地改動。",
            "Reset", "重置", "reset --merge COMMIT_SHA", destructive: true, keywords: "reset,merge,重置"),
        GitTweak.Git("gitx.reset-orig-head", "Reset to ORIG_HEAD", "重置到 ORIG_HEAD",
            "Undo the last big operation by resetting hard to ORIG_HEAD.", "硬重置返去 ORIG_HEAD，撤銷上一個大動作。",
            "Reset", "重置", "reset --hard ORIG_HEAD", destructive: true, keywords: "reset,orig_head,撤銷,重置"),
        GitTweak.Git("gitx.rm-r-cached", "Untrack a folder", "取消追蹤資料夾",
            "Stop tracking the build/ folder but leave it on disk.", "唔再追蹤 build/ 資料夾，但留返喺磁碟。",
            "Untrack", "取消追蹤", "rm -r --cached build", keywords: "rm,cached,recursive,取消追蹤,資料夾"),
        GitTweak.Git("gitx.update-index-assume", "Assume file unchanged", "假設檔案無變",
            "Tell git to ignore future changes to README.md (assume-unchanged).", "叫 git 當 README.md 之後唔再有改動。",
            "Mark", "標記", "update-index --assume-unchanged README.md", keywords: "update-index,assume-unchanged,忽略"),
        GitTweak.Git("gitx.update-index-no-assume", "Resume tracking changes", "恢復追蹤改動",
            "Clear the assume-unchanged flag on README.md.", "清除 README.md 上嘅 assume-unchanged 標記。",
            "Mark", "標記", "update-index --no-assume-unchanged README.md", keywords: "update-index,no-assume-unchanged,恢復"),
        GitTweak.Git("gitx.update-index-skip", "Skip worktree file", "略過工作區檔",
            "Mark README.md skip-worktree so local edits are kept private.", "將 README.md 標做 skip-worktree，令本地改動私隱化。",
            "Mark", "標記", "update-index --skip-worktree README.md", keywords: "update-index,skip-worktree,略過"),
        GitTweak.Git("gitx.update-index-refresh", "Refresh index", "重新整理索引",
            "Refresh the staging area's cached file stat information.", "重新整理暫存區對檔案狀態嘅快取資訊。",
            "Refresh", "整理", "update-index --refresh", keywords: "update-index,refresh,索引,整理"),
        GitTweak.Git("gitx.sparse-init-cone", "Sparse-checkout init (cone)", "稀疏檢出初始化（cone）",
            "Enable cone-mode sparse-checkout for partial working trees.", "開啟 cone 模式嘅稀疏檢出，做部分工作區。",
            "Init", "初始化", "sparse-checkout init --cone", keywords: "sparse-checkout,cone,稀疏"),
        GitTweak.Git("gitx.sparse-set", "Sparse-checkout set dir", "稀疏檢出設定資料夾",
            "Limit the working tree to the src/ directory.", "將工作區限制喺 src/ 資料夾。",
            "Set", "設定", "sparse-checkout set src", keywords: "sparse-checkout,set,稀疏,資料夾"),
        GitTweak.Git("gitx.sparse-list", "Sparse-checkout list", "稀疏檢出清單",
            "List the directories currently included by sparse-checkout.", "列出而家稀疏檢出包含咗嘅資料夾。",
            "List", "列出", "sparse-checkout list", keywords: "sparse-checkout,list,稀疏,清單"),
        GitTweak.Git("gitx.sparse-disable", "Sparse-checkout disable", "停用稀疏檢出",
            "Turn off sparse-checkout and restore the full working tree.", "關閉稀疏檢出，還原返完整工作區。",
            "Disable", "停用", "sparse-checkout disable", keywords: "sparse-checkout,disable,停用,稀疏"),
        GitTweak.Git("gitx.sparse-reapply", "Sparse-checkout reapply", "重新套用稀疏檢出",
            "Re-apply the current sparse-checkout patterns to the working tree.", "將而家嘅稀疏檢出規則重新套落工作區。",
            "Reapply", "重套", "sparse-checkout reapply", keywords: "sparse-checkout,reapply,稀疏"),
        GitTweak.Git("gitx.clean-fdx", "Clean incl. ignored", "清理連被忽略",
            "Permanently delete all untracked files including ignored ones. Cannot be undone.", "永久刪除晒所有未追蹤檔案，連被 ignore 嗰啲都刪，無得返轉頭。",
            "Clean", "清理", "clean -fdx", destructive: true, keywords: "clean,fdx,ignored,清理,刪除"),
        GitTweak.Git("gitx.clean-fX", "Clean only ignored", "淨清理被忽略",
            "Permanently delete only the ignored files, keeping other untracked files.", "淨係永久刪除被 ignore 嘅檔案，其他未追蹤嘅留返。",
            "Clean", "清理", "clean -fX", destructive: true, keywords: "clean,fX,ignored,清理,忽略"),
        GitTweak.Git("gitx.check-ignore", "Why is a file ignored?", "點解被忽略？",
            "Show which .gitignore rule causes README.md to be ignored.", "顯示係邊條 .gitignore 規則令 README.md 被忽略。",
            "Check", "檢查", "check-ignore -v README.md", keywords: "check-ignore,gitignore,忽略,規則"),
        GitTweak.Git("gitx.check-attr", "Show file attributes", "顯示檔案屬性",
            "List all gitattributes that apply to README.md.", "列出套用喺 README.md 嘅所有 gitattributes。",
            "Check", "檢查", "check-attr -a README.md", keywords: "check-attr,gitattributes,屬性"),

        // ===== commit variants =====
        GitTweak.Git("gitx.commit-amend-edit", "Amend & edit message", "修改並改訊息",
            "Amend the last commit and open an editor to change its message.", "修改上一個提交，並開編輯器改返個訊息。",
            "Amend", "修改", "commit --amend", destructive: true, keywords: "commit,amend,edit,訊息"),
        GitTweak.Git("gitx.commit-fixup", "Fixup commit", "fixup 提交",
            "Create a fixup! commit targeting a given commit for later autosquash.", "整一個 fixup! 提交對住指定提交，遲啲 autosquash 用。",
            "Commit", "提交", "commit --fixup=COMMIT_SHA", keywords: "commit,fixup,autosquash,提交"),
        GitTweak.Git("gitx.commit-squash", "Squash commit", "squash 提交",
            "Create a squash! commit targeting a given commit for later autosquash.", "整一個 squash! 提交對住指定提交，遲啲 autosquash 用。",
            "Commit", "提交", "commit --squash=COMMIT_SHA", keywords: "commit,squash,autosquash,提交"),
        GitTweak.Git("gitx.commit-signoff", "Commit with sign-off", "提交加簽署",
            "Commit the staged changes and append a Signed-off-by line.", "提交暫存改動，並加返一行 Signed-off-by。",
            "Commit", "提交", "commit --signoff -m \"Update files\"", keywords: "commit,signoff,簽署,提交"),
        GitTweak.Git("gitx.commit-no-verify", "Commit skipping hooks", "提交略過 hooks",
            "Commit while skipping pre-commit and commit-msg hooks.", "提交時略過 pre-commit 同 commit-msg hooks。",
            "Commit", "提交", "commit --no-verify -m \"Update files\"", keywords: "commit,no-verify,hooks,略過"),
        GitTweak.Git("gitx.commit-gpg-sign", "GPG-signed commit", "GPG 簽名提交",
            "Create a cryptographically signed commit.", "整一個有加密簽名嘅提交。",
            "Commit", "提交", "commit --gpg-sign -m \"Signed commit\"", keywords: "commit,gpg,sign,簽名,提交"),
        GitTweak.Git("gitx.commit-date", "Commit with a date", "指定日期提交",
            "Commit using a custom author date.", "用自訂嘅作者日期嚟提交。",
            "Commit", "提交", "commit --date=\"2026-01-01 12:00:00\" -m \"Backdated commit\"", keywords: "commit,date,日期,提交"),
        GitTweak.Git("gitx.commit-author", "Commit as another author", "以他人身份提交",
            "Commit while overriding the author identity.", "提交時改用另一個作者身份。",
            "Commit", "提交", "commit --author=\"Name <name@example.com>\" -m \"Update files\"", keywords: "commit,author,作者,提交"),
        GitTweak.Git("gitx.commit-verbose", "Commit (verbose)", "提交（詳細）",
            "Commit with the staged diff shown in the message editor.", "提交時喺訊息編輯器入面顯示埋暫存嘅 diff。",
            "Commit", "提交", "commit -v -m \"Update files\"", keywords: "commit,verbose,詳細,提交"),
        GitTweak.Git("gitx.notes-add", "Add a note", "加備註",
            "Attach a note to the HEAD commit.", "喺 HEAD 提交度加返個備註。",
            "Note", "備註", "notes add -m \"My note\" HEAD", keywords: "notes,add,備註"),
        GitTweak.Git("gitx.notes-show", "Show note", "顯示備註",
            "Show the note attached to the HEAD commit.", "顯示 HEAD 提交上嘅備註。",
            "Show", "顯示", "notes show HEAD", keywords: "notes,show,備註,顯示"),
        GitTweak.Git("gitx.notes-list", "List notes", "列出備註",
            "List every commit that has a note.", "列出所有有備註嘅提交。",
            "List", "列出", "notes list", keywords: "notes,list,備註,列出"),
        GitTweak.Git("gitx.notes-remove", "Remove note", "移除備註",
            "Remove the note attached to the HEAD commit.", "移除 HEAD 提交上嘅備註。",
            "Remove", "移除", "notes remove HEAD", destructive: true, keywords: "notes,remove,備註,移除"),
        GitTweak.Git("gitx.notes-edit", "Edit note", "編輯備註",
            "Open an editor to change the note on the HEAD commit.", "開編輯器改 HEAD 提交上嘅備註。",
            "Edit", "編輯", "notes edit HEAD", keywords: "notes,edit,備註,編輯"),

        // ===== history / inspect =====
        GitTweak.Git("gitx.log-author", "Log by author", "歷史（按作者）",
            "Show commits authored by a given name.", "睇返某個作者寫嘅提交。",
            "Show", "顯示", "log --oneline --author=\"Your Name\" -30", keywords: "log,author,作者,歷史"),
        GitTweak.Git("gitx.log-committer", "Log by committer", "歷史（按提交者）",
            "Show commits committed by a given name.", "睇返某個提交者嘅提交。",
            "Show", "顯示", "log --oneline --committer=\"Your Name\" -30", keywords: "log,committer,提交者,歷史"),
        GitTweak.Git("gitx.log-grep-body", "Search messages (grep)", "搜尋訊息（grep）",
            "Search commit messages for the word TODO.", "喺提交訊息度搵 TODO 呢個字。",
            "Search", "搜尋", "log --oneline --grep=TODO -30", keywords: "log,grep,訊息,搜尋"),
        GitTweak.Git("gitx.log-merges", "Log merges only", "歷史（淨合併）",
            "Show only merge commits.", "淨係睇合併提交。",
            "Show", "顯示", "log --oneline --merges -30", keywords: "log,merges,合併,歷史"),
        GitTweak.Git("gitx.log-no-merges", "Log without merges", "歷史（無合併）",
            "Show history excluding merge commits.", "睇歷史但唔計合併提交。",
            "Show", "顯示", "log --oneline --no-merges -30", keywords: "log,no-merges,歷史"),
        GitTweak.Git("gitx.log-first-parent", "Log first-parent", "歷史（第一父）",
            "Follow only the first parent to see the mainline history.", "淨係跟第一個父提交，睇主線歷史。",
            "Show", "顯示", "log --oneline --first-parent -30", keywords: "log,first-parent,主線,歷史"),
        GitTweak.Git("gitx.log-all", "Log all refs", "歷史（所有 refs）",
            "Show history across all branches and refs.", "睇晒所有分支同 refs 嘅歷史。",
            "Show", "顯示", "log --oneline --all -30", keywords: "log,all,所有,歷史"),
        GitTweak.Git("gitx.log-reverse", "Log reversed", "歷史（倒轉）",
            "Show history from oldest to newest.", "由舊到新咁睇歷史。",
            "Show", "顯示", "log --oneline --reverse -30", keywords: "log,reverse,倒轉,歷史"),
        GitTweak.Git("gitx.log-date-order", "Log date-order", "歷史（日期序）",
            "Order commits strictly by commit date.", "嚴格按提交日期排序。",
            "Show", "顯示", "log --oneline --date-order -30", keywords: "log,date-order,日期,歷史"),
        GitTweak.Git("gitx.log-topo-order", "Log topo-order", "歷史（拓樸序）",
            "Order commits topologically to avoid interleaving lineages.", "用拓樸排序，避免唔同分支交錯。",
            "Show", "顯示", "log --oneline --topo-order -30", keywords: "log,topo-order,拓樸,歷史"),
        GitTweak.Git("gitx.log-name-status", "Log with name-status", "歷史連檔案狀態",
            "Show history with the change type and file name per commit.", "睇歷史，連埋每個提交嘅改動類型同檔名。",
            "Show", "顯示", "log --name-status -10", keywords: "log,name-status,狀態,歷史"),
        GitTweak.Git("gitx.log-shortstat", "Log with shortstat", "歷史連精簡統計",
            "Show history with a one-line change summary per commit.", "睇歷史，每個提交一行改動摘要。",
            "Show", "顯示", "log --shortstat -10", keywords: "log,shortstat,統計,歷史"),
        GitTweak.Git("gitx.log-numstat", "Log with numstat", "歷史連數值統計",
            "Show added/removed line counts per file per commit.", "睇每個提交每個檔案嘅增刪行數。",
            "Show", "顯示", "log --numstat -10", keywords: "log,numstat,統計,歷史"),
        GitTweak.Git("gitx.log-cherry-mark", "Log cherry-mark", "歷史（cherry-mark）",
            "Mark commits as equivalent (=) or unique (+) versus main.", "對住 main 標示提交係相等（=）定獨有（+）。",
            "Show", "顯示", "log --oneline --cherry-mark main...HEAD", keywords: "log,cherry-mark,歷史"),
        GitTweak.Git("gitx.log-left-right", "Log left-right", "歷史（左右）",
            "Show which side of a symmetric range each commit is on.", "顯示對稱範圍入面每個提交喺邊一邊。",
            "Show", "顯示", "log --oneline --left-right main...HEAD", keywords: "log,left-right,歷史"),
        GitTweak.Git("gitx.log-pretty-format", "Log custom format", "歷史（自訂格式）",
            "Show history using a custom pretty format string.", "用自訂 pretty 格式顯示歷史。",
            "Show", "顯示", "log --pretty=format:\"%h %an %ar %s\" -20", keywords: "log,pretty,format,格式,歷史"),
        GitTweak.Git("gitx.log-pretty-fuller", "Log (fuller)", "歷史（fuller）",
            "Show history with both author and committer details.", "睇歷史，連埋作者同提交者嘅資料。",
            "Show", "顯示", "log --pretty=fuller -10", keywords: "log,fuller,詳細,歷史"),
        GitTweak.Git("gitx.log-oneline-decorate", "Log oneline + decorate", "歷史（單行連標籤）",
            "Show one-line history with branch and tag decorations.", "單行歷史，連埋分支同標籤標示。",
            "Show", "顯示", "log --oneline --decorate -30", keywords: "log,decorate,標籤,歷史"),
        GitTweak.Git("gitx.log-pickaxe-s", "Pickaxe by string (-S)", "鶴嘴搵字串（-S）",
            "Find commits that change the number of occurrences of a string.", "搵啲令某段文字出現次數改變嘅提交。",
            "Search", "搜尋", "log -S\"functionName\" --oneline", keywords: "log,pickaxe,S,字串,搜尋"),
        GitTweak.Git("gitx.log-pickaxe-g", "Pickaxe by regex (-G)", "鶴嘴搵正則（-G）",
            "Find commits whose diff matches a regular expression.", "搵啲 diff 配到正則嘅提交。",
            "Search", "搜尋", "log -G\"regex.*pattern\" --oneline", keywords: "log,pickaxe,G,正則,搜尋"),
        GitTweak.Git("gitx.log-line-range", "Log a line range (-L)", "歷史（行範圍 -L）",
            "Show the history of lines 1-20 in README.md.", "睇 README.md 第 1 至 20 行嘅歷史。",
            "Show", "顯示", "log -L 1,20:README.md", keywords: "log,L,line,行,歷史"),
        GitTweak.Git("gitx.whatchanged", "What changed", "改咗乜",
            "Show recent commits with the files each one touched.", "睇近排提交，連埋每個改過嘅檔案。",
            "Show", "顯示", "whatchanged -10", keywords: "whatchanged,改動,歷史"),
        GitTweak.Git("gitx.show-commit", "Show a commit", "顯示提交",
            "Show the details and diff of a given commit.", "顯示指定提交嘅詳情同 diff。",
            "Show", "顯示", "show COMMIT_SHA", keywords: "show,commit,提交"),
        GitTweak.Git("gitx.show-file-at-commit", "Show file at commit", "顯示某提交嘅檔案",
            "Show the contents of README.md as it was at a given commit.", "顯示 README.md 喺某個提交嗰陣嘅內容。",
            "Show", "顯示", "show COMMIT_SHA:README.md", keywords: "show,file,commit,檔案"),
        GitTweak.Git("gitx.show-stat", "Show commit stat", "顯示提交統計",
            "Show a stat summary of the HEAD commit.", "顯示 HEAD 提交嘅 stat 摘要。",
            "Show", "顯示", "show --stat HEAD", keywords: "show,stat,統計"),
        GitTweak.Git("gitx.show-name-only", "Show changed names", "顯示改動檔名",
            "List only the file names changed in the HEAD commit.", "淨係列出 HEAD 提交改咗嘅檔名。",
            "Show", "顯示", "show --name-only HEAD", keywords: "show,name-only,檔名"),
        GitTweak.Git("gitx.shortlog-sne", "Shortlog -sne", "貢獻者統計 -sne",
            "Summarise commit counts per author with emails.", "按作者統計提交數，連埋電郵。",
            "Show", "顯示", "shortlog -sne HEAD", keywords: "shortlog,sne,貢獻者,統計"),
        GitTweak.Git("gitx.range-diff", "Range-diff two ranges", "範圍差異",
            "Compare two commit ranges to see how a series changed.", "比較兩個提交範圍，睇個系列點變。",
            "Show", "顯示", "range-diff main...HEAD", keywords: "range-diff,範圍,差異"),
        GitTweak.Git("gitx.cherry", "Cherry (-v)", "揀摘比對（-v）",
            "Show which commits on HEAD are not yet in main.", "睇 HEAD 上邊啲提交未入 main。",
            "Show", "顯示", "cherry -v main", keywords: "cherry,verbose,比對"),
        GitTweak.Git("gitx.rev-list-count", "Count commits", "點算提交",
            "Count the number of commits reachable from HEAD.", "點算由 HEAD 接觸得到嘅提交數目。",
            "Count", "點算", "rev-list --count HEAD", keywords: "rev-list,count,點算,提交"),
        GitTweak.Git("gitx.rev-list-all-count", "Count all commits", "點算所有提交",
            "Count commits reachable from every ref.", "點算所有 ref 接觸得到嘅提交數目。",
            "Count", "點算", "rev-list --count --all", keywords: "rev-list,count,all,點算"),
        GitTweak.Git("gitx.rev-list-since", "Commits since date", "某日期後提交",
            "List commits made since two weeks ago.", "列出近兩個禮拜嘅提交。",
            "Show", "顯示", "rev-list --since=\"2 weeks ago\" HEAD", keywords: "rev-list,since,日期,提交"),
        GitTweak.Git("gitx.rev-parse-toplevel", "Repo top-level", "倉庫頂層",
            "Print the absolute path of the repository's top-level directory.", "印返儲存庫頂層資料夾嘅絕對路徑。",
            "Show", "顯示", "rev-parse --show-toplevel", keywords: "rev-parse,toplevel,頂層,路徑"),
        GitTweak.Git("gitx.rev-parse-git-dir", "Locate .git dir", "搵 .git 目錄",
            "Print the path to the .git directory.", "印返 .git 目錄嘅路徑。",
            "Show", "顯示", "rev-parse --git-dir", keywords: "rev-parse,git-dir,目錄"),
        GitTweak.Git("gitx.rev-parse-abbrev", "Current branch name", "目前分支名",
            "Print the short name of the current branch.", "印返而家分支嘅短名。",
            "Show", "顯示", "rev-parse --abbrev-ref HEAD", keywords: "rev-parse,abbrev-ref,分支名"),
        GitTweak.Git("gitx.rev-parse-verify", "Verify a ref", "驗證 ref",
            "Verify that HEAD resolves to a valid object and print it.", "驗證 HEAD 解析到一個有效物件，並印返。",
            "Verify", "驗證", "rev-parse --verify HEAD", keywords: "rev-parse,verify,驗證"),
        GitTweak.Git("gitx.rev-parse-symbolic", "Symbolic full name", "符號全名",
            "Print the full symbolic ref name of HEAD.", "印返 HEAD 嘅完整符號 ref 名。",
            "Show", "顯示", "rev-parse --symbolic-full-name HEAD", keywords: "rev-parse,symbolic,符號"),
        GitTweak.Git("gitx.show-ref", "Show refs", "顯示 refs",
            "List all refs and the object IDs they point to.", "列出所有 refs 同佢哋指住嘅物件 ID。",
            "Show", "顯示", "show-ref", keywords: "show-ref,refs,顯示"),
        GitTweak.Git("gitx.for-each-ref", "Branches by date", "分支按日期",
            "List local branches sorted by most recent commit.", "按最近提交排序列出本地分支。",
            "List", "列出", "for-each-ref --sort=-committerdate refs/heads", keywords: "for-each-ref,sort,分支,日期"),
        GitTweak.Git("gitx.symbolic-ref-head", "Show HEAD target", "顯示 HEAD 目標",
            "Print which branch HEAD currently points to.", "印返 HEAD 而家指住邊條分支。",
            "Show", "顯示", "symbolic-ref HEAD", keywords: "symbolic-ref,head,目標"),
        GitTweak.Git("gitx.name-rev", "Name a commit", "命名提交",
            "Find a symbolic name for the HEAD commit.", "幫 HEAD 提交搵返個符號名。",
            "Show", "顯示", "name-rev --name-only HEAD", keywords: "name-rev,name,命名"),
        GitTweak.Git("gitx.merge-base", "Merge base", "合併基底",
            "Find the common ancestor of main and HEAD.", "搵 main 同 HEAD 嘅共同祖先。",
            "Show", "顯示", "merge-base main HEAD", keywords: "merge-base,ancestor,祖先,基底"),
        GitTweak.Git("gitx.merge-base-ancestor", "Is ancestor?", "係咪祖先？",
            "Check whether main is an ancestor of HEAD (exit code result).", "檢查 main 係咪 HEAD 嘅祖先（用 exit code 表示）。",
            "Check", "檢查", "merge-base --is-ancestor main HEAD", keywords: "merge-base,is-ancestor,祖先"),
        GitTweak.Git("gitx.merge-base-fork-point", "Fork point", "分叉點",
            "Find where the current branch forked off from main.", "搵而家分支由 main 分叉出嚟嗰點。",
            "Show", "顯示", "merge-base --fork-point main", keywords: "merge-base,fork-point,分叉"),
        GitTweak.Git("gitx.describe-all", "Describe (--all)", "描述（--all）",
            "Describe HEAD using any ref, not just tags.", "用任何 ref（唔淨係標籤）嚟描述 HEAD。",
            "Show", "顯示", "describe --all", keywords: "describe,all,描述"),
        GitTweak.Git("gitx.describe-dirty", "Describe (--dirty)", "描述（--dirty）",
            "Describe HEAD and mark it dirty if the tree has changes.", "描述 HEAD，如果工作區有改動就標 dirty。",
            "Show", "顯示", "describe --tags --dirty", keywords: "describe,dirty,描述"),
        GitTweak.Git("gitx.diff-numstat", "Diff numstat", "差異數值統計",
            "Show machine-readable added/removed line counts.", "顯示機器可讀嘅增刪行數。",
            "Show", "顯示", "diff --numstat", keywords: "diff,numstat,統計"),
        GitTweak.Git("gitx.diff-shortstat", "Diff shortstat", "差異精簡統計",
            "Show a one-line summary of working-tree changes.", "用一行摘要顯示工作區改動。",
            "Show", "顯示", "diff --shortstat", keywords: "diff,shortstat,統計"),
        GitTweak.Git("gitx.diff-ignore-ws", "Diff ignore whitespace", "差異（忽略空白）",
            "Show diffs while ignoring whitespace changes.", "顯示 diff 但唔計空白改動。",
            "Show", "顯示", "diff -w", keywords: "diff,whitespace,空白"),
        GitTweak.Git("gitx.diff-word", "Diff word-diff", "差異（逐字）",
            "Show changes word by word instead of line by line.", "逐個字而唔係逐行顯示改動。",
            "Show", "顯示", "diff --word-diff", keywords: "diff,word-diff,逐字"),
        GitTweak.Git("gitx.diff-color-words", "Diff color-words", "差異（彩色字）",
            "Show a coloured word-level diff.", "顯示彩色嘅逐字 diff。",
            "Show", "顯示", "diff --color-words", keywords: "diff,color-words,彩色"),
        GitTweak.Git("gitx.diff-check", "Diff check", "差異檢查",
            "Check for whitespace errors and merge conflict markers.", "檢查空白錯誤同合併衝突標記。",
            "Check", "檢查", "diff --check", keywords: "diff,check,空白,衝突"),
        GitTweak.Git("gitx.diff-filter", "Diff added files only", "差異（淨新增檔）",
            "Show only files that were added (diff-filter=A).", "淨係顯示新增咗嘅檔案（diff-filter=A）。",
            "Show", "顯示", "diff --diff-filter=A --name-only", keywords: "diff,diff-filter,新增"),
        GitTweak.Git("gitx.diff-two-dot", "Diff A..B", "差異 A..B",
            "Show the diff between two refs (two-dot).", "顯示兩個 ref 之間嘅 diff（兩點）。",
            "Show", "顯示", "diff main..HEAD", keywords: "diff,two-dot,範圍"),
        GitTweak.Git("gitx.diff-three-dot", "Diff A...B", "差異 A...B",
            "Show changes on HEAD since it diverged from main (three-dot).", "顯示 HEAD 由 main 分叉之後嘅改動（三點）。",
            "Show", "顯示", "diff main...HEAD", keywords: "diff,three-dot,範圍,分叉"),
        GitTweak.Git("gitx.diff-staged-stat", "Diff staged stat", "差異（已暫存統計）",
            "Show a stat summary of staged changes.", "顯示已暫存改動嘅 stat 摘要。",
            "Show", "顯示", "diff --staged --stat", keywords: "diff,staged,stat,統計"),
        GitTweak.Git("gitx.diff-head", "Diff vs HEAD", "差異對 HEAD",
            "Show all changes (staged and unstaged) against HEAD.", "顯示對住 HEAD 嘅所有改動（暫存同未暫存）。",
            "Show", "顯示", "diff HEAD", keywords: "diff,head,差異"),
        GitTweak.Git("gitx.diff-name-status", "Diff name-status", "差異（名同狀態）",
            "List changed files with their change type.", "列出改動檔案連埋改動類型。",
            "Show", "顯示", "diff --name-status", keywords: "diff,name-status,狀態"),
        GitTweak.Git("gitx.diff-stat-prev", "Diff vs previous", "差異對上一個",
            "Show a stat summary comparing HEAD to its parent.", "比較 HEAD 同上一個提交嘅 stat 摘要。",
            "Show", "顯示", "diff --stat HEAD~1", keywords: "diff,stat,previous,上一個"),
        GitTweak.Git("gitx.diff-tree", "Diff-tree of HEAD", "diff-tree HEAD",
            "List file names changed in the HEAD commit via diff-tree.", "用 diff-tree 列出 HEAD 提交改咗嘅檔名。",
            "Show", "顯示", "diff-tree --no-commit-id --name-only -r HEAD", keywords: "diff-tree,name-only,檔名"),
        GitTweak.Git("gitx.blame-range", "Blame a line range", "追溯行範圍",
            "Show authorship for lines 1-20 of README.md.", "睇 README.md 第 1 至 20 行邊個改。",
            "Show", "顯示", "blame -L 1,20 README.md", keywords: "blame,range,行,追溯"),
        GitTweak.Git("gitx.blame-copy-move", "Blame detect copies", "追溯偵測複製",
            "Blame README.md while detecting moved and copied lines.", "追溯 README.md 並偵測搬移同複製嘅行。",
            "Show", "顯示", "blame -C -M -w README.md", keywords: "blame,copy,move,複製,追溯"),
        GitTweak.Git("gitx.blame-email", "Blame show emails", "追溯顯示電郵",
            "Blame README.md showing author emails instead of names.", "追溯 README.md，顯示作者電郵而唔係名。",
            "Show", "顯示", "blame -e README.md", keywords: "blame,email,電郵,追溯"),
        GitTweak.Git("gitx.grep", "Grep tracked files", "搜尋已追蹤檔案",
            "Search tracked files for the word TODO with line numbers.", "喺已追蹤檔案搵 TODO，連埋行號。",
            "Search", "搜尋", "grep -n \"TODO\"", keywords: "grep,search,搜尋,TODO"),
        GitTweak.Git("gitx.grep-count", "Grep count matches", "搜尋計次數",
            "Count occurrences of TODO per file.", "點算每個檔案出現 TODO 嘅次數。",
            "Search", "搜尋", "grep -c \"TODO\"", keywords: "grep,count,計數,搜尋"),
        GitTweak.Git("gitx.grep-files", "Grep file names", "搜尋（淨檔名）",
            "List files containing TODO without showing the lines.", "淨係列出含 TODO 嘅檔名，唔顯示行。",
            "Search", "搜尋", "grep -l \"TODO\"", keywords: "grep,files,檔名,搜尋"),
        GitTweak.Git("gitx.ls-files-others", "List untracked files", "列出未追蹤檔案",
            "List untracked files not covered by .gitignore.", "列出未追蹤而又冇被 ignore 嘅檔案。",
            "List", "列出", "ls-files --others --exclude-standard", keywords: "ls-files,others,未追蹤"),
        GitTweak.Git("gitx.ls-files-modified", "List modified files", "列出已修改檔案",
            "List tracked files that have unstaged modifications.", "列出有未暫存改動嘅已追蹤檔案。",
            "List", "列出", "ls-files --modified", keywords: "ls-files,modified,修改"),
        GitTweak.Git("gitx.ls-files-deleted", "List deleted files", "列出已刪除檔案",
            "List tracked files that have been deleted on disk.", "列出喺磁碟畀人刪咗嘅已追蹤檔案。",
            "List", "列出", "ls-files --deleted", keywords: "ls-files,deleted,刪除"),
        GitTweak.Git("gitx.ls-files-stage", "List index entries", "列出索引項目",
            "List staged files with their mode and object hash.", "列出已暫存檔案連埋 mode 同物件 hash。",
            "List", "列出", "ls-files --stage", keywords: "ls-files,stage,索引"),
        GitTweak.Git("gitx.ls-files-ignored", "List ignored files", "列出被忽略檔案",
            "List tracked-and-ignored files using the exclude rules.", "用 exclude 規則列出被忽略嘅檔案。",
            "List", "列出", "ls-files --ignored --exclude-standard --others", keywords: "ls-files,ignored,忽略"),
        GitTweak.Git("gitx.ls-tree", "List tree at HEAD", "列出 HEAD 樹",
            "Recursively list files tracked in the HEAD tree.", "遞迴列出 HEAD 樹入面追蹤緊嘅檔案。",
            "List", "列出", "ls-tree -r HEAD", keywords: "ls-tree,tree,樹,檔案"),
        GitTweak.Git("gitx.ls-remote", "List remote heads", "列出遠端分支",
            "List branch refs on the origin remote without fetching.", "唔抓取咁列出 origin 遠端嘅分支 refs。",
            "List", "列出", "ls-remote --heads origin", keywords: "ls-remote,heads,遠端"),
        GitTweak.Git("gitx.cat-file-type", "Object type", "物件類型",
            "Print the object type that HEAD refers to.", "印返 HEAD 指住嗰個物件嘅類型。",
            "Show", "顯示", "cat-file -t HEAD", keywords: "cat-file,type,類型,物件"),
        GitTweak.Git("gitx.cat-file-print", "Pretty-print object", "美化印物件",
            "Pretty-print the contents of the HEAD object.", "美化咁印返 HEAD 物件嘅內容。",
            "Show", "顯示", "cat-file -p HEAD", keywords: "cat-file,print,物件"),
        GitTweak.Git("gitx.cat-file-size", "Object size", "物件大細",
            "Print the size in bytes of the HEAD object.", "印返 HEAD 物件嘅位元組大細。",
            "Show", "顯示", "cat-file -s HEAD", keywords: "cat-file,size,大細,物件"),
        GitTweak.Git("gitx.verify-commit", "Verify commit signature", "驗證提交簽名",
            "Verify the GPG signature on the HEAD commit.", "驗證 HEAD 提交嘅 GPG 簽名。",
            "Verify", "驗證", "verify-commit HEAD", keywords: "verify-commit,gpg,簽名,驗證"),
        GitTweak.Git("gitx.verify-tag", "Verify tag signature", "驗證標籤簽名",
            "Verify the GPG signature on tag v1.0.0.", "驗證標籤 v1.0.0 嘅 GPG 簽名。",
            "Verify", "驗證", "verify-tag v1.0.0", keywords: "verify-tag,gpg,簽名,驗證"),

        // ===== branches / tags (advanced) =====
        GitTweak.Git("gitx.branch-vv", "Branches with tracking", "分支連追蹤",
            "List local branches with upstream and ahead/behind info.", "列出本地分支，連埋上游同領先/落後資訊。",
            "List", "列出", "branch -vv", keywords: "branch,vv,tracking,追蹤"),
        GitTweak.Git("gitx.branch-merged", "Merged branches", "已合併分支",
            "List branches already merged into the current one.", "列出已經合併入而家分支嘅分支。",
            "List", "列出", "branch --merged", keywords: "branch,merged,合併"),
        GitTweak.Git("gitx.branch-no-merged", "Unmerged branches", "未合併分支",
            "List branches not yet merged into the current one.", "列出未合併入而家分支嘅分支。",
            "List", "列出", "branch --no-merged", keywords: "branch,no-merged,未合併"),
        GitTweak.Git("gitx.branch-contains", "Branches containing commit", "含某提交嘅分支",
            "List branches that contain a given commit.", "列出包含咗指定提交嘅分支。",
            "List", "列出", "branch --contains COMMIT_SHA", keywords: "branch,contains,提交"),
        GitTweak.Git("gitx.branch-remote", "Remote branches", "遠端分支",
            "List remote-tracking branches.", "列出遠端追蹤分支。",
            "List", "列出", "branch -r", keywords: "branch,remote,遠端"),
        GitTweak.Git("gitx.branch-set-upstream", "Set upstream branch", "設定上游分支",
            "Set the current branch to track origin/main.", "將而家分支設做追蹤 origin/main。",
            "Set", "設定", "branch --set-upstream-to=origin/main", keywords: "branch,upstream,上游"),
        GitTweak.Git("gitx.branch-unset-upstream", "Unset upstream", "取消上游",
            "Stop the current branch from tracking any upstream.", "令而家分支唔再追蹤任何上游。",
            "Unset", "取消", "branch --unset-upstream", keywords: "branch,unset-upstream,上游"),
        GitTweak.Git("gitx.branch-copy", "Copy a branch", "複製分支",
            "Copy the current branch to a new branch named 'new'.", "將而家分支複製做一條叫 'new' 嘅新分支。",
            "Copy", "複製", "branch -c new", keywords: "branch,copy,複製"),
        GitTweak.Git("gitx.tag-lightweight", "Create lightweight tag", "建立輕量標籤",
            "Create a lightweight tag v1.0.0 at HEAD.", "喺 HEAD 起一個輕量標籤 v1.0.0。",
            "Tag", "標籤", "tag v1.0.0", keywords: "tag,lightweight,輕量,標籤"),
        GitTweak.Git("gitx.tag-signed", "Create signed tag", "建立簽名標籤",
            "Create a GPG-signed tag v1.0.0.", "起一個 GPG 簽名標籤 v1.0.0。",
            "Tag", "標籤", "tag -s v1.0.0 -m \"Release v1.0.0\"", keywords: "tag,signed,簽名,標籤"),
        GitTweak.Git("gitx.tag-list-pattern", "List tags by pattern", "按樣式列標籤",
            "List tags matching the pattern v*.", "列出符合 v* 樣式嘅標籤。",
            "List", "列出", "tag -l \"v*\"", keywords: "tag,list,pattern,樣式,標籤"),
        GitTweak.Git("gitx.tag-points-at", "Tags at HEAD", "HEAD 上嘅標籤",
            "List tags that point at the HEAD commit.", "列出指住 HEAD 提交嘅標籤。",
            "List", "列出", "tag --points-at HEAD", keywords: "tag,points-at,標籤"),
        GitTweak.Git("gitx.tag-n", "Tags with messages", "標籤連訊息",
            "List tags along with their annotation message.", "列出標籤連埋佢哋嘅附註訊息。",
            "List", "列出", "tag -n", keywords: "tag,n,訊息,標籤"),
        GitTweak.Git("gitx.switch-detach", "Switch detached", "切去分離狀態",
            "Check out a commit in detached HEAD state.", "用分離 HEAD 狀態檢出一個提交。",
            "Switch", "切換", "switch --detach COMMIT_SHA", keywords: "switch,detach,分離"),
        GitTweak.Git("gitx.switch-previous", "Switch to previous", "切返上一個",
            "Switch back to the previously checked-out branch.", "切返去之前嗰條分支。",
            "Switch", "切換", "switch -", keywords: "switch,previous,上一個"),
        GitTweak.Git("gitx.checkout-orphan", "Orphan branch", "孤兒分支",
            "Create a new branch with no history (orphan root).", "起一條冇歷史嘅新分支（孤兒根）。",
            "Checkout", "檢出", "checkout --orphan newroot", keywords: "checkout,orphan,孤兒"),
        GitTweak.Git("gitx.checkout-commit-file", "Checkout file at commit", "檢出某提交檔案",
            "Restore README.md from a given commit into the working tree.", "由指定提交將 README.md 還原落工作區。",
            "Checkout", "檢出", "checkout COMMIT_SHA -- README.md", destructive: true, keywords: "checkout,file,commit,檔案"),
        GitTweak.Git("gitx.checkout-track", "Checkout tracking branch", "檢出追蹤分支",
            "Create local branch 'feat' tracking origin/feat.", "起本地分支 'feat' 追蹤 origin/feat。",
            "Checkout", "檢出", "checkout -b feat origin/feat", keywords: "checkout,track,追蹤,分支"),

        // ===== merge / rebase / sequencer =====
        GitTweak.Git("gitx.merge-squash", "Merge squash", "合併壓縮",
            "Merge 'feature' into the index without committing (squash).", "將 'feature' 合併入索引但唔提交（壓縮）。",
            "Merge", "合併", "merge --squash feature", keywords: "merge,squash,壓縮,合併"),
        GitTweak.Git("gitx.merge-ff-only", "Merge fast-forward only", "合併（只快轉）",
            "Merge 'feature' only if it can be a fast-forward.", "淨係喺可以快轉嘅情況下合併 'feature'。",
            "Merge", "合併", "merge --ff-only feature", keywords: "merge,ff-only,快轉"),
        GitTweak.Git("gitx.merge-continue", "Continue merge", "繼續合併",
            "Continue a merge after resolving conflicts.", "解決衝突之後繼續合併。",
            "Continue", "繼續", "merge --continue", keywords: "merge,continue,繼續"),
        GitTweak.Git("gitx.merge-x-ours", "Merge favouring ours", "合併（偏我方）",
            "Merge 'feature' resolving conflicts in favour of our side.", "合併 'feature'，衝突時偏向我方。",
            "Merge", "合併", "merge -X ours feature", keywords: "merge,ours,我方"),
        GitTweak.Git("gitx.merge-x-theirs", "Merge favouring theirs", "合併（偏對方）",
            "Merge 'feature' resolving conflicts in favour of their side.", "合併 'feature'，衝突時偏向對方。",
            "Merge", "合併", "merge -X theirs feature", keywords: "merge,theirs,對方"),
        GitTweak.Git("gitx.rebase-onto", "Rebase --onto", "變基 --onto",
            "Move the last 3 commits of 'feature' onto main. Rewrites history.", "將 'feature' 最後 3 個提交移到 main 上面，會改寫歷史。",
            "Rebase", "變基", "rebase --onto main feature~3 feature", destructive: true, keywords: "rebase,onto,變基"),
        GitTweak.Git("gitx.rebase-continue", "Continue rebase", "繼續變基",
            "Continue a rebase after resolving conflicts.", "解決衝突之後繼續變基。",
            "Continue", "繼續", "rebase --continue", destructive: true, keywords: "rebase,continue,繼續"),
        GitTweak.Git("gitx.rebase-skip", "Skip rebase commit", "略過變基提交",
            "Skip the current commit during a rebase.", "變基途中略過而家呢個提交。",
            "Skip", "略過", "rebase --skip", destructive: true, keywords: "rebase,skip,略過"),
        GitTweak.Git("gitx.rebase-autosquash", "Rebase autosquash", "變基自動壓縮",
            "Rebase onto main, auto-applying fixup!/squash! commits, stashing if needed.", "變基到 main，自動套用 fixup!/squash! 提交，需要時自動 stash。",
            "Rebase", "變基", "rebase --autosquash --autostash main", destructive: true, keywords: "rebase,autosquash,autostash,變基"),
        GitTweak.Git("gitx.rebase-root", "Rebase --root", "變基（--root）",
            "Rebase all commits including the very first one. Rewrites all history.", "由最初一個提交開始全部變基，會改寫晒所有歷史。",
            "Rebase", "變基", "rebase --root", destructive: true, keywords: "rebase,root,變基,歷史"),
        GitTweak.Git("gitx.cherry-pick-continue", "Continue cherry-pick", "繼續揀摘",
            "Continue a cherry-pick after resolving conflicts.", "解決衝突之後繼續揀摘。",
            "Continue", "繼續", "cherry-pick --continue", destructive: true, keywords: "cherry-pick,continue,繼續"),
        GitTweak.Git("gitx.cherry-pick-abort", "Abort cherry-pick", "中止揀摘",
            "Abort an in-progress cherry-pick.", "中止進行緊嘅揀摘。",
            "Abort", "中止", "cherry-pick --abort", destructive: true, keywords: "cherry-pick,abort,中止"),
        GitTweak.Git("gitx.cherry-pick-skip", "Skip cherry-pick", "略過揀摘",
            "Skip the current commit during a cherry-pick.", "揀摘途中略過而家呢個提交。",
            "Skip", "略過", "cherry-pick --skip", destructive: true, keywords: "cherry-pick,skip,略過"),
        GitTweak.Git("gitx.cherry-pick-n", "Cherry-pick no commit", "揀摘（唔提交）",
            "Apply a commit's changes without committing.", "套用某提交嘅改動但唔提交。",
            "Cherry-pick", "揀摘", "cherry-pick -n COMMIT_SHA", destructive: true, keywords: "cherry-pick,no-commit,揀摘"),
        GitTweak.Git("gitx.cherry-pick-x", "Cherry-pick with origin", "揀摘（記來源）",
            "Cherry-pick a commit and record the original commit ID.", "揀摘提交並記低原本嘅提交 ID。",
            "Cherry-pick", "揀摘", "cherry-pick -x COMMIT_SHA", destructive: true, keywords: "cherry-pick,x,來源,揀摘"),
        GitTweak.Git("gitx.revert-continue", "Continue revert", "繼續還原",
            "Continue a revert after resolving conflicts.", "解決衝突之後繼續還原。",
            "Continue", "繼續", "revert --continue", destructive: true, keywords: "revert,continue,繼續"),
        GitTweak.Git("gitx.revert-abort", "Abort revert", "中止還原",
            "Abort an in-progress revert.", "中止進行緊嘅還原。",
            "Abort", "中止", "revert --abort", destructive: true, keywords: "revert,abort,中止"),
        GitTweak.Git("gitx.am-continue", "Continue am", "繼續 am",
            "Continue applying a mailbox patch series after fixing conflicts.", "解決衝突後繼續套用 mailbox 補丁系列。",
            "Continue", "繼續", "am --continue", destructive: true, keywords: "am,continue,繼續,補丁"),
        GitTweak.Git("gitx.am-abort", "Abort am", "中止 am",
            "Abort an in-progress 'git am' and restore the branch.", "中止進行緊嘅 'git am'，還原返分支。",
            "Abort", "中止", "am --abort", destructive: true, keywords: "am,abort,中止,補丁"),
        GitTweak.Git("gitx.am-skip", "Skip am patch", "略過 am 補丁",
            "Skip the current patch during 'git am'.", "喺 'git am' 途中略過而家嘅補丁。",
            "Skip", "略過", "am --skip", destructive: true, keywords: "am,skip,略過,補丁"),
        GitTweak.Git("gitx.am-3way", "Apply patch (3-way)", "套補丁（三方）",
            "Apply patch.eml with 3-way merge fallback.", "用三方合併備援套用 patch.eml。",
            "Apply", "套用", "am --3way patch.eml", destructive: true, keywords: "am,3way,三方,補丁"),
        GitTweak.Git("gitx.apply-check", "Check a patch", "檢查補丁",
            "Check whether patch.diff applies cleanly without applying it.", "檢查 patch.diff 可唔可以乾淨套用，但唔真係套。",
            "Check", "檢查", "apply --check patch.diff", keywords: "apply,check,補丁,檢查"),
        GitTweak.Git("gitx.apply-stat", "Patch stat", "補丁統計",
            "Show a stat summary of what patch.diff would change.", "顯示 patch.diff 會改啲乜嘅 stat 摘要。",
            "Show", "顯示", "apply --stat patch.diff", keywords: "apply,stat,補丁,統計"),
        GitTweak.Git("gitx.apply-3way", "Apply patch 3-way", "套補丁（三方合併）",
            "Apply patch.diff using 3-way merge for conflicting hunks.", "用三方合併嚟套 patch.diff 處理衝突段。",
            "Apply", "套用", "apply --3way patch.diff", destructive: true, keywords: "apply,3way,三方,補丁"),
        GitTweak.Git("gitx.apply-reverse", "Reverse a patch", "反向套補丁",
            "Apply patch.diff in reverse to undo it.", "反向套 patch.diff 嚟撤銷佢。",
            "Apply", "套用", "apply --reverse patch.diff", destructive: true, keywords: "apply,reverse,反向,補丁"),
        GitTweak.Git("gitx.format-patch-1", "Format patch (last)", "輸出補丁（最後）",
            "Create a patch file for the latest commit.", "為最新提交整一個補丁檔。",
            "Format", "輸出", "format-patch -1 HEAD", keywords: "format-patch,補丁,輸出"),
        GitTweak.Git("gitx.format-patch-range", "Format patch (range)", "輸出補丁（範圍）",
            "Create patch files for commits not yet on origin.", "為仲未喺 origin 嘅提交整補丁檔。",
            "Format", "輸出", "format-patch origin..HEAD", keywords: "format-patch,range,範圍,補丁"),
        GitTweak.Git("gitx.request-pull", "Request pull summary", "請求拉取摘要",
            "Generate a pull request summary from main to origin.", "由 main 對 origin 產生一份拉取請求摘要。",
            "Generate", "產生", "request-pull main origin HEAD", keywords: "request-pull,pull,摘要"),

        // ===== stash (advanced) =====
        GitTweak.Git("gitx.stash-apply", "Apply stash", "套用擱置",
            "Reapply the latest stash but keep it in the list.", "重新套用最新嘅 stash，但喺清單保留佢。",
            "Apply", "套用", "stash apply", destructive: true, keywords: "stash,apply,套用,擱置"),
        GitTweak.Git("gitx.stash-branch", "Stash to branch", "擱置開分支",
            "Create a branch 'newbranch' from the latest stash and apply it.", "由最新嘅 stash 開一條 'newbranch' 並套用佢。",
            "Branch", "分支", "stash branch newbranch", keywords: "stash,branch,分支,擱置"),
        GitTweak.Git("gitx.stash-keep-index", "Stash keep index", "擱置保留索引",
            "Stash changes but keep the staged ones in the index.", "擱置改動但保留已暫存嗰啲喺索引度。",
            "Stash", "擱置", "stash push --keep-index", keywords: "stash,keep-index,索引,擱置"),
        GitTweak.Git("gitx.stash-untracked", "Stash incl. untracked", "擱置連未追蹤",
            "Stash changes including untracked files.", "擱置改動，連未追蹤檔案都擱。",
            "Stash", "擱置", "stash push -u", keywords: "stash,untracked,未追蹤,擱置"),
        GitTweak.Git("gitx.stash-path", "Stash a path", "擱置指定路徑",
            "Stash only the changes to README.md.", "淨係擱置 README.md 嘅改動。",
            "Stash", "擱置", "stash push -- README.md", keywords: "stash,path,路徑,擱置"),
        GitTweak.Git("gitx.stash-create", "Create stash object", "建立擱置物件",
            "Create a stash commit object without storing it in the stash list.", "整一個 stash 提交物件但唔放入 stash 清單。",
            "Create", "建立", "stash create", keywords: "stash,create,物件,擱置"),
        GitTweak.Git("gitx.stash-show-stat", "Stash show stat", "擱置統計",
            "Show a stat summary of the latest stash.", "顯示最新 stash 嘅 stat 摘要。",
            "Show", "顯示", "stash show --stat", keywords: "stash,show,stat,統計,擱置"),

        // ===== remotes / transport =====
        GitTweak.Git("gitx.remote-rename", "Rename remote", "重新命名遠端",
            "Rename the remote 'origin' to 'upstream'.", "將遠端 'origin' 改名做 'upstream'。",
            "Rename", "改名", "remote rename origin upstream", keywords: "remote,rename,改名,遠端"),
        GitTweak.Git("gitx.remote-remove", "Remove remote", "移除遠端",
            "Remove the remote named 'origin'.", "移除叫 'origin' 嘅遠端。",
            "Remove", "移除", "remote remove origin", destructive: true, keywords: "remote,remove,移除,遠端"),
        GitTweak.Git("gitx.remote-prune", "Prune remote", "清理遠端",
            "Delete stale remote-tracking refs under origin.", "刪除 origin 下面冇咗嘅遠端追蹤 refs。",
            "Prune", "清理", "remote prune origin", destructive: true, keywords: "remote,prune,清理,遠端"),
        GitTweak.Git("gitx.remote-set-head", "Auto-set remote HEAD", "自動設遠端 HEAD",
            "Automatically determine origin's default branch.", "自動判斷 origin 嘅預設分支。",
            "Set", "設定", "remote set-head origin -a", keywords: "remote,set-head,head,遠端"),
        GitTweak.Git("gitx.remote-get-url", "Get remote URL", "攞遠端網址",
            "Print the fetch URL of the origin remote.", "印返 origin 遠端嘅抓取網址。",
            "Show", "顯示", "remote get-url origin", keywords: "remote,get-url,網址,遠端"),
        GitTweak.Git("gitx.remote-set-branches", "Set tracked branches", "設追蹤分支",
            "Configure origin to track only the main branch.", "設定 origin 淨係追蹤 main 分支。",
            "Set", "設定", "remote set-branches origin main", keywords: "remote,set-branches,追蹤,遠端"),
        GitTweak.Git("gitx.remote-update", "Update all remotes", "更新所有遠端",
            "Fetch updates from all configured remotes.", "由所有已設定遠端抓取更新。",
            "Update", "更新", "remote update", keywords: "remote,update,更新,遠端"),
        GitTweak.Git("gitx.fetch-tags", "Fetch tags", "抓取標籤",
            "Fetch all tags from the remote.", "由遠端抓取所有標籤。",
            "Fetch", "抓取", "fetch --tags", keywords: "fetch,tags,標籤,抓取"),
        GitTweak.Git("gitx.fetch-depth", "Shallow fetch", "淺抓取",
            "Fetch only the most recent commit (depth 1).", "淨係抓取最近一個提交（depth 1）。",
            "Fetch", "抓取", "fetch --depth=1", keywords: "fetch,depth,淺,抓取"),
        GitTweak.Git("gitx.fetch-unshallow", "Unshallow fetch", "還原完整抓取",
            "Convert a shallow clone into a full one.", "將淺複製還原做完整 repo。",
            "Fetch", "抓取", "fetch --unshallow", keywords: "fetch,unshallow,完整,抓取"),
        GitTweak.Git("gitx.fetch-prune-tags", "Fetch prune tags", "抓取清理標籤",
            "Fetch while pruning deleted remote tags.", "抓取嘅同時清理返已刪除嘅遠端標籤。",
            "Fetch", "抓取", "fetch --prune --prune-tags", destructive: true, keywords: "fetch,prune-tags,標籤,清理"),
        GitTweak.Git("gitx.fetch-dry-run", "Fetch dry-run", "抓取（試行）",
            "Show what a fetch would download without doing it.", "顯示抓取會落啲乜但唔真係抓。",
            "Preview", "預覽", "fetch --dry-run", keywords: "fetch,dry-run,試行,預覽"),
        GitTweak.Git("gitx.fetch-origin-branch", "Fetch origin branch", "抓取 origin 分支",
            "Fetch only the main branch from origin.", "淨係由 origin 抓取 main 分支。",
            "Fetch", "抓取", "fetch origin main", keywords: "fetch,origin,branch,分支,抓取"),
        GitTweak.Git("gitx.push-all", "Push all branches", "推送所有分支",
            "Push every local branch to origin.", "將所有本地分支推去 origin。",
            "Push", "推送", "push --all origin", keywords: "push,all,所有,分支,推送"),
        GitTweak.Git("gitx.push-mirror", "Push mirror", "鏡像推送",
            "Mirror all refs to origin, overwriting remote refs. Dangerous.", "將所有 refs 鏡像去 origin，會覆蓋遠端 refs，好危險。",
            "Push", "推送", "push --mirror origin", destructive: true, keywords: "push,mirror,鏡像,推送"),
        GitTweak.Git("gitx.push-delete", "Delete remote branch", "刪除遠端分支",
            "Delete the 'feature' branch on origin.", "刪除 origin 上面嘅 'feature' 分支。",
            "Delete", "刪除", "push --delete origin feature", destructive: true, keywords: "push,delete,遠端,分支,刪除"),
        GitTweak.Git("gitx.push-prune", "Push with prune", "推送並清理",
            "Push and remove remote branches that have no local counterpart.", "推送，同時刪除冇本地對應嘅遠端分支。",
            "Push", "推送", "push --prune origin", destructive: true, keywords: "push,prune,清理,推送"),
        GitTweak.Git("gitx.push-dry-run", "Push dry-run", "推送（試行）",
            "Show what a push would update without doing it.", "顯示推送會更新啲乜但唔真係推。",
            "Preview", "預覽", "push --dry-run", keywords: "push,dry-run,試行,預覽"),
        GitTweak.Git("gitx.push-follow-tags", "Push with tags", "推送連標籤",
            "Push commits along with annotated tags that point at them.", "推送提交，連埋指住佢哋嘅附註標籤。",
            "Push", "推送", "push --follow-tags", keywords: "push,follow-tags,標籤,推送"),
        GitTweak.Git("gitx.push-option", "Push with option", "推送（帶選項）",
            "Push while sending the server option ci.skip.", "推送時送埋伺服器選項 ci.skip。",
            "Push", "推送", "push -o ci.skip", keywords: "push,option,ci.skip,推送"),
        GitTweak.Git("gitx.pull-ff-only", "Pull fast-forward only", "拉取（只快轉）",
            "Pull only if it can fast-forward, never creating a merge.", "淨係喺可以快轉時先拉取，唔整合併。",
            "Pull", "拉取", "pull --ff-only", keywords: "pull,ff-only,快轉,拉取"),
        GitTweak.Git("gitx.pull-no-rebase", "Pull (merge)", "拉取（合併）",
            "Pull and merge, overriding any rebase config.", "拉取並合併，蓋過任何 rebase 設定。",
            "Pull", "拉取", "pull --no-rebase", keywords: "pull,no-rebase,合併,拉取"),
        GitTweak.Git("gitx.pull-autostash", "Pull autostash", "拉取自動擱置",
            "Pull with rebase, auto-stashing local changes first.", "用變基拉取，先自動 stash 本地改動。",
            "Pull", "拉取", "pull --rebase --autostash", destructive: true, keywords: "pull,autostash,擱置,拉取"),

        // ===== worktree / submodule (advanced) =====
        GitTweak.Git("gitx.worktree-add", "Add a worktree", "新增工作樹",
            "Create a linked working tree at ../wt for the 'feature' branch.", "喺 ../wt 為 'feature' 分支建立一個連結工作樹。",
            "Add", "新增", "worktree add ../wt feature", keywords: "worktree,add,工作樹,新增"),
        GitTweak.Git("gitx.worktree-remove", "Remove a worktree", "移除工作樹",
            "Remove the linked working tree at ../wt.", "移除 ../wt 嘅連結工作樹。",
            "Remove", "移除", "worktree remove ../wt", destructive: true, keywords: "worktree,remove,移除,工作樹"),
        GitTweak.Git("gitx.worktree-move", "Move a worktree", "移動工作樹",
            "Move the worktree at ../wt to ../wt2.", "將 ../wt 嘅工作樹移去 ../wt2。",
            "Move", "移動", "worktree move ../wt ../wt2", keywords: "worktree,move,移動,工作樹"),
        GitTweak.Git("gitx.worktree-lock", "Lock a worktree", "鎖定工作樹",
            "Lock the worktree at ../wt to prevent pruning.", "鎖定 ../wt 嘅工作樹，防止被清理。",
            "Lock", "鎖定", "worktree lock ../wt", keywords: "worktree,lock,鎖定,工作樹"),
        GitTweak.Git("gitx.worktree-unlock", "Unlock a worktree", "解鎖工作樹",
            "Unlock the worktree at ../wt.", "解鎖 ../wt 嘅工作樹。",
            "Unlock", "解鎖", "worktree unlock ../wt", keywords: "worktree,unlock,解鎖,工作樹"),
        GitTweak.Git("gitx.submodule-add", "Add a submodule", "新增子模組",
            "Add a submodule at path 'lib' from a URL.", "由網址喺 'lib' 路徑新增一個子模組。",
            "Add", "新增", "submodule add https://github.com/user/repo.git lib", keywords: "submodule,add,子模組,新增"),
        GitTweak.Git("gitx.submodule-sync", "Sync submodule URLs", "同步子模組網址",
            "Recursively sync submodule remote URLs from .gitmodules.", "由 .gitmodules 遞迴同步子模組嘅遠端網址。",
            "Sync", "同步", "submodule sync --recursive", keywords: "submodule,sync,網址,子模組"),
        GitTweak.Git("gitx.submodule-foreach", "Submodule foreach", "子模組逐個執行",
            "Run 'git status' inside each submodule.", "喺每個子模組入面行 'git status'。",
            "Run", "執行", "submodule foreach \"git status\"", keywords: "submodule,foreach,逐個,子模組"),
        GitTweak.Git("gitx.submodule-deinit", "Deinit submodules", "停用子模組",
            "Unregister and clear out all submodules. Removes their working trees.", "取消註冊同清走所有子模組，會刪佢哋嘅工作區。",
            "Deinit", "停用", "submodule deinit -f --all", destructive: true, keywords: "submodule,deinit,停用,子模組"),
        GitTweak.Git("gitx.submodule-set-url", "Set submodule URL", "設子模組網址",
            "Set the URL of the submodule at path 'lib'.", "設定 'lib' 路徑子模組嘅網址。",
            "Set", "設定", "submodule set-url lib https://github.com/user/repo.git", keywords: "submodule,set-url,網址,子模組"),
        GitTweak.Git("gitx.submodule-set-branch", "Set submodule branch", "設子模組分支",
            "Track the main branch for the submodule at path 'lib'.", "令 'lib' 子模組追蹤 main 分支。",
            "Set", "設定", "submodule set-branch --branch main lib", keywords: "submodule,set-branch,分支,子模組"),
        GitTweak.Git("gitx.submodule-summary", "Submodule summary", "子模組摘要",
            "Show a summary of submodule commit differences.", "顯示子模組提交差異嘅摘要。",
            "Show", "顯示", "submodule summary", keywords: "submodule,summary,摘要,子模組"),
        GitTweak.Git("gitx.submodule-update-remote", "Update submodules to remote", "更新子模組到遠端",
            "Update submodules to the latest remote commit and merge.", "將子模組更新到遠端最新提交並合併。",
            "Update", "更新", "submodule update --remote --merge", keywords: "submodule,remote,merge,更新,子模組"),

        // ===== maintenance / plumbing =====
        GitTweak.Git("gitx.gc-auto", "GC (auto)", "垃圾回收（自動）",
            "Run housekeeping only if git decides it is needed.", "淨係喺 git 認為需要時先做整理。",
            "Run", "執行", "gc --auto", keywords: "gc,auto,自動,清理"),
        GitTweak.Git("gitx.maintenance-run-gc", "Maintenance run gc", "維護執行 gc",
            "Run the gc maintenance task once.", "執行一次 gc 維護任務。",
            "Run", "執行", "maintenance run --task=gc", keywords: "maintenance,gc,維護"),
        GitTweak.Git("gitx.maintenance-start", "Start maintenance", "啟動維護",
            "Enable background maintenance for this repository.", "為呢個 repo 開啟背景維護。",
            "Start", "啟動", "maintenance start", keywords: "maintenance,start,啟動,維護"),
        GitTweak.Git("gitx.maintenance-stop", "Stop maintenance", "停止維護",
            "Disable background maintenance for this repository.", "為呢個 repo 關閉背景維護。",
            "Stop", "停止", "maintenance stop", keywords: "maintenance,stop,停止,維護"),
        GitTweak.Git("gitx.repack-adf", "Repack -adf", "重新打包 -adf",
            "Aggressively repack all objects into a single fresh pack.", "進取咁將所有物件重新打包成一個全新 pack。",
            "Repack", "打包", "repack -adf", keywords: "repack,adf,打包"),
        GitTweak.Git("gitx.prune-now", "Prune (expire now)", "清除（即刻過期）",
            "Immediately prune all unreachable objects.", "即刻清除晒所有接觸唔到嘅物件。",
            "Prune", "清除", "prune --expire=now", destructive: true, keywords: "prune,expire,清除,now"),
        GitTweak.Git("gitx.pack-refs", "Pack refs", "打包 refs",
            "Pack all loose refs into a single file for speed.", "將所有散裝 refs 打包入單一檔案加速。",
            "Pack", "打包", "pack-refs --all", keywords: "pack-refs,refs,打包"),
        GitTweak.Git("gitx.prune-packed", "Prune packed", "清理已打包",
            "Remove loose objects that are already in pack files.", "刪除已經喺 pack 入面嘅散裝物件。",
            "Prune", "清理", "prune-packed", keywords: "prune-packed,清理,打包"),
        GitTweak.Git("gitx.commit-graph", "Write commit-graph", "寫提交圖檔",
            "Write a commit-graph file to speed up history operations.", "寫一個 commit-graph 檔案加快歷史操作。",
            "Write", "寫入", "commit-graph write --reachable", keywords: "commit-graph,write,提交圖"),
        GitTweak.Git("gitx.multi-pack-index", "Write multi-pack-index", "寫多重打包索引",
            "Write a multi-pack-index to speed up object lookups.", "寫一個 multi-pack-index 加快物件查找。",
            "Write", "寫入", "multi-pack-index write", keywords: "multi-pack-index,索引,打包"),
        GitTweak.Git("gitx.fsck-unreachable", "Fsck unreachable", "檢查接觸唔到物件",
            "List unreachable objects found during a consistency check.", "列出一致性檢查中接觸唔到嘅物件。",
            "Check", "檢查", "fsck --unreachable", keywords: "fsck,unreachable,檢查,物件"),
        GitTweak.Git("gitx.fsck-dangling", "Fsck dangling", "檢查懸空物件",
            "List dangling objects such as orphaned commits.", "列出懸空物件，例如孤立提交。",
            "Check", "檢查", "fsck --dangling", keywords: "fsck,dangling,懸空,檢查"),
        GitTweak.Git("gitx.reflog-show", "Reflog show", "顯示 reflog",
            "Show the reflog for HEAD.", "顯示 HEAD 嘅 reflog。",
            "Show", "顯示", "reflog show HEAD", keywords: "reflog,show,顯示"),
        GitTweak.Git("gitx.reflog-delete", "Delete a reflog entry", "刪除 reflog 項目",
            "Delete a specific reflog entry HEAD@{1}.", "刪除某個 reflog 項目 HEAD@{1}。",
            "Delete", "刪除", "reflog delete HEAD@{1}", destructive: true, keywords: "reflog,delete,刪除"),
        GitTweak.Git("gitx.replace-list", "List replacements", "列出替換",
            "List configured object replacements.", "列出已設定嘅物件替換。",
            "List", "列出", "replace --list", keywords: "replace,list,替換"),
        GitTweak.Git("gitx.hash-object", "Hash & store object", "雜湊並儲存物件",
            "Hash README.md and write it into the object database.", "雜湊 README.md 並寫入物件資料庫。",
            "Hash", "雜湊", "hash-object -w README.md", keywords: "hash-object,hash,物件"),
        GitTweak.Git("gitx.write-tree", "Write tree", "寫樹物件",
            "Write the current index out as a tree object.", "將而家嘅索引寫做一個樹物件。",
            "Write", "寫入", "write-tree", keywords: "write-tree,tree,樹"),
        GitTweak.Git("gitx.update-ref", "Update a ref", "更新 ref",
            "Point refs/heads/tmp at the HEAD commit.", "將 refs/heads/tmp 指住 HEAD 提交。",
            "Update", "更新", "update-ref refs/heads/tmp HEAD", destructive: true, keywords: "update-ref,ref,更新"),
        GitTweak.Git("gitx.bundle-verify", "Verify a bundle", "驗證 bundle",
            "Check that repo.bundle is valid and applies cleanly.", "檢查 repo.bundle 係咪有效又乾淨套到。",
            "Verify", "驗證", "bundle verify repo.bundle", keywords: "bundle,verify,驗證"),
        GitTweak.Git("gitx.bundle-list-heads", "List bundle heads", "列出 bundle 分支",
            "List the refs stored inside repo.bundle.", "列出 repo.bundle 入面儲住嘅 refs。",
            "List", "列出", "bundle list-heads repo.bundle", keywords: "bundle,list-heads,分支"),
        GitTweak.Git("gitx.archive-tar", "Archive to tar", "封存做 tar",
            "Export HEAD as a tar archive with a repo/ prefix.", "將 HEAD 匯出做帶 repo/ 前綴嘅 tar 封存檔。",
            "Archive", "封存", "archive --format=tar --prefix=repo/ -o repo.tar HEAD", keywords: "archive,tar,封存"),
        GitTweak.Git("gitx.fast-export", "Fast-export all", "快速匯出全部",
            "Stream the entire history in fast-export format.", "用 fast-export 格式串流匯出成個歷史。",
            "Export", "匯出", "fast-export --all", keywords: "fast-export,匯出,歷史"),

        // ===== bisect =====
        GitTweak.Git("gitx.bisect-start", "Bisect start", "二分搜尋開始",
            "Begin a binary search to find a bad commit.", "開始二分搜尋去搵壞咗嘅提交。",
            "Start", "開始", "bisect start", keywords: "bisect,start,二分,搜尋"),
        GitTweak.Git("gitx.bisect-good", "Bisect mark good", "二分標記正常",
            "Mark the current commit as good during a bisect.", "二分途中將而家提交標做正常。",
            "Mark", "標記", "bisect good", keywords: "bisect,good,正常,二分"),
        GitTweak.Git("gitx.bisect-bad", "Bisect mark bad", "二分標記壞",
            "Mark the current commit as bad during a bisect.", "二分途中將而家提交標做壞咗。",
            "Mark", "標記", "bisect bad", keywords: "bisect,bad,壞,二分"),
        GitTweak.Git("gitx.bisect-log", "Bisect log", "二分日誌",
            "Show the log of the current bisect session.", "顯示而家二分過程嘅日誌。",
            "Show", "顯示", "bisect log", keywords: "bisect,log,日誌,二分"),
        GitTweak.Git("gitx.bisect-reset", "Bisect reset", "二分重置",
            "End the bisect session and return to the original branch.", "結束二分搜尋，返返去原本分支。",
            "Reset", "重置", "bisect reset", keywords: "bisect,reset,結束,二分"),

        // ===== history rewrite (discouraged) =====
        GitTweak.Git("gitx.filter-branch", "Filter-branch (discouraged)", "filter-branch（不建議）",
            "Rewrite all history with a per-commit filter. Discouraged: prefer git-filter-repo. Destroys old refs.", "用 per-commit 過濾器改寫晒所有歷史。唔建議用，最好用 git-filter-repo，會摧毀舊 refs。",
            "Rewrite", "改寫", "filter-branch --force --tree-filter \"true\" HEAD", destructive: true, keywords: "filter-branch,rewrite,改寫,歷史"),
    };
}
