using System;
using System.Collections.Generic;
using WinTune.Models;

namespace WinTune.Catalog;

/// <summary>
/// 完整 GitHub 操作目錄（透過 gh CLI 同 gh api 喺選中嘅儲存庫執行）。
/// COMPLETE GitHub coverage driven through the GitHub CLI (gh) and, where gh has no
/// first-class command, through "gh api" (gh substitutes {owner}/{repo} automatically
/// when run inside a repo). Complements <see cref="GitOperations"/>.
/// 由 ultracode workflow 產生。Generated via an ultracode workflow.
/// </summary>
public static class GitHubOperations
{
    public static IEnumerable<TweakDefinition> All() => new List<TweakDefinition>
    {
        // ===== auth / account =====
        GitTweak.Tool("gh.auth-login-web", "Log in (browser)", "登入（瀏覽器）",
            "Authenticate to GitHub by opening a browser login flow.", "用瀏覽器登入流程嚟認證去 GitHub。",
            "Log in", "登入", "gh", "auth login --web", keywords: "auth,login,登入,web,gh"),
        GitTweak.Tool("gh.auth-logout", "Log out", "登出",
            "Log out of your GitHub account from the CLI.", "喺 CLI 度登出你嘅 GitHub 帳號。",
            "Log out", "登出", "gh", "auth logout", destructive: true, keywords: "auth,logout,登出,gh"),
        GitTweak.Tool("gh.auth-refresh", "Refresh auth", "重新整理認證",
            "Refresh your stored authentication credentials and scopes.", "重新整理你儲低嘅認證憑證同權限範圍。",
            "Refresh", "整理", "gh", "auth refresh", keywords: "auth,refresh,scope,認證,gh"),
        GitTweak.Tool("gh.auth-token", "Show auth token", "顯示認證權杖",
            "Print the OAuth token currently used by the CLI.", "印返 CLI 而家用緊嗰個 OAuth 權杖。",
            "Show", "顯示", "gh", "auth token", keywords: "auth,token,權杖,gh"),
        GitTweak.Tool("gh.auth-setup-git", "Set up git credentials", "設定 git 認證",
            "Configure git to use the GitHub CLI as a credential helper.", "設定 git 用 GitHub CLI 做認證助手。",
            "Set up", "設定", "gh", "auth setup-git", keywords: "auth,setup-git,credential,認證,gh"),
        GitTweak.Tool("gh.auth-switch", "Switch account", "切換帳號",
            "Switch the active GitHub account used by the CLI.", "切換 CLI 而家用緊嗰個 GitHub 帳號。",
            "Switch", "切換", "gh", "auth switch", keywords: "auth,switch,account,帳號,gh"),
        GitTweak.Tool("gh.api-user", "Your GitHub profile", "你嘅 GitHub 資料",
            "Fetch your authenticated user profile from the API.", "用 API 攞返你登入帳號嘅資料。",
            "Fetch", "攞返", "gh", "api user", keywords: "api,user,profile,資料,gh"),
        GitTweak.Tool("gh.api-user-emails", "Your email addresses", "你嘅電郵地址",
            "List the email addresses on your GitHub account.", "列出你 GitHub 帳號上面嘅電郵地址。",
            "List", "列出", "gh", "api user/emails", keywords: "api,user,emails,電郵,gh"),
        GitTweak.Tool("gh.api-rate-limit", "API rate limit", "API 速率限制",
            "Show your current GitHub API rate-limit status.", "睇返你而家嘅 GitHub API 速率限制狀態。",
            "Show", "顯示", "gh", "api /rate_limit", keywords: "api,rate limit,速率,限制,gh"),
        GitTweak.Tool("gh.config-git-protocol", "Git protocol setting", "Git 協定設定",
            "Show whether the CLI uses https or ssh for git operations.", "睇返 CLI 做 git 操作時用 https 定 ssh。",
            "Show", "顯示", "gh", "config get git_protocol", keywords: "config,git protocol,協定,gh"),
        GitTweak.Tool("gh.alias-list", "List aliases", "列出別名",
            "List the command aliases defined in the GitHub CLI.", "列出 GitHub CLI 入面定義咗嘅指令別名。",
            "List", "列出", "gh", "alias list", keywords: "alias,list,別名,gh"),
        GitTweak.Tool("gh.extension-list", "List extensions", "列出擴充功能",
            "List the installed GitHub CLI extensions.", "列出安裝咗嘅 GitHub CLI 擴充功能。",
            "List", "列出", "gh", "extension list", keywords: "extension,list,擴充,gh"),
        GitTweak.Tool("gh.version", "CLI version", "CLI 版本",
            "Show the installed GitHub CLI version.", "顯示安裝咗嘅 GitHub CLI 版本。",
            "Show", "顯示", "gh", "version", keywords: "version,版本,gh"),

        // ===== repo lifecycle =====
        GitTweak.Tool("gh.repo-create-public", "Create public repo", "建立公開 Repo",
            "Create a new public repository on GitHub.", "喺 GitHub 度建立一個新嘅公開 repo。",
            "Create", "建立", "gh", "repo create --public", keywords: "repo,create,public,公開,gh"),
        GitTweak.Tool("gh.repo-create-private", "Create private repo", "建立私人 Repo",
            "Create a new private repository on GitHub.", "喺 GitHub 度建立一個新嘅私人 repo。",
            "Create", "建立", "gh", "repo create --private", keywords: "repo,create,private,私人,gh"),
        GitTweak.Tool("gh.repo-create-template", "Create from template", "由範本建立",
            "Create a new repository from a template repository.", "用範本 repo 嚟建立一個新 repo。",
            "Create", "建立", "gh", "repo create --template OWNER/REPO", keywords: "repo,create,template,範本,gh"),
        GitTweak.Tool("gh.repo-clone", "Clone a repo", "複製 Repo",
            "Clone the repository OWNER/REPO to your machine.", "將 OWNER/REPO 呢個 repo 複製落你部機。",
            "Clone", "複製", "gh", "repo clone OWNER/REPO", keywords: "repo,clone,複製,gh"),
        GitTweak.Tool("gh.repo-fork-clone", "Fork & clone", "分叉並複製",
            "Fork this repository and clone your fork locally.", "將呢個 repo 分叉，再將你嘅分叉複製落本機。",
            "Fork", "分叉", "gh", "repo fork --clone", keywords: "repo,fork,clone,分叉,複製,gh"),
        GitTweak.Tool("gh.repo-list", "Your repos", "你嘅 Repo",
            "List repositories owned by your account.", "列出你帳號擁有嘅 repo。",
            "List", "列出", "gh", "repo list", keywords: "repo,list,你,gh"),
        GitTweak.Tool("gh.repo-list-org", "Org repos", "組織 Repo",
            "List repositories belonging to an organisation.", "列出某個組織擁有嘅 repo。",
            "List", "列出", "gh", "repo list ORG", keywords: "repo,list,org,組織,gh"),
        GitTweak.Tool("gh.repo-view", "View repository", "睇個 Repo",
            "Show details of the current repository.", "顯示而家呢個 repo 嘅資料。",
            "View", "查睇", "gh", "repo view", keywords: "repo,view,資料,gh"),
        GitTweak.Tool("gh.repo-view-web", "Open repo in browser", "喺瀏覽器開 Repo",
            "Open the current repository on GitHub in your browser.", "喺瀏覽器度開返呢個 repo 嘅 GitHub 頁面。",
            "Open", "開啟", "gh", "repo view --web", keywords: "repo,web,browser,瀏覽器,gh"),
        GitTweak.Tool("gh.repo-view-json", "Repo details (JSON)", "Repo 詳情（JSON）",
            "Show selected repository fields as JSON.", "用 JSON 顯示返揀好嘅 repo 欄位。",
            "View", "查睇", "gh", "repo view --json name,description,visibility,defaultBranchRef", keywords: "repo,json,詳情,gh"),
        GitTweak.Tool("gh.repo-edit-description", "Edit description", "改描述",
            "Update the repository's description text.", "更新呢個 repo 嘅描述文字。",
            "Edit", "修改", "gh", "repo edit --description \"New description\"", keywords: "repo,edit,description,描述,gh"),
        GitTweak.Tool("gh.repo-edit-visibility", "Change visibility", "改可見度",
            "Change whether the repository is public or private.", "改返呢個 repo 係公開定私人。",
            "Edit", "修改", "gh", "repo edit --visibility private", destructive: true, keywords: "repo,edit,visibility,可見度,gh"),
        GitTweak.Tool("gh.repo-rename", "Rename repo", "改 Repo 名",
            "Rename the current repository.", "將而家呢個 repo 改名。",
            "Rename", "改名", "gh", "repo rename NEWNAME", keywords: "repo,rename,改名,gh"),
        GitTweak.Tool("gh.repo-archive", "Archive repo", "封存 Repo",
            "Mark the repository as archived (read-only).", "將呢個 repo 標做封存（唯讀）。",
            "Archive", "封存", "gh", "repo archive --yes", destructive: true, keywords: "repo,archive,封存,gh"),
        GitTweak.Tool("gh.repo-unarchive", "Unarchive repo", "解除封存",
            "Restore an archived repository to active status.", "將封存咗嘅 repo 還原做活躍狀態。",
            "Unarchive", "解除封存", "gh", "repo unarchive --yes", keywords: "repo,unarchive,解除,封存,gh"),
        GitTweak.Tool("gh.repo-delete", "Delete repo", "刪除 Repo",
            "Permanently delete the current repository.", "永久刪除而家呢個 repo。",
            "Delete", "刪除", "gh", "repo delete --yes", destructive: true, keywords: "repo,delete,刪除,gh"),
        GitTweak.Tool("gh.repo-set-default", "Set default repo", "設定預設 Repo",
            "Set the default repository for gh commands.", "設定 gh 指令用嘅預設 repo。",
            "Set", "設定", "gh", "repo set-default", keywords: "repo,set-default,預設,gh"),
        GitTweak.Tool("gh.repo-sync", "Sync fork", "同步分叉",
            "Sync the local repository with its upstream parent.", "將本機 repo 同上游母 repo 同步。",
            "Sync", "同步", "gh", "repo sync", keywords: "repo,sync,fork,同步,gh"),
        GitTweak.Tool("gh.repo-deploykey-list", "List deploy keys", "列出部署金鑰",
            "List the deploy keys configured on this repository.", "列出呢個 repo 設定咗嘅部署金鑰。",
            "List", "列出", "gh", "repo deploy-key list", keywords: "repo,deploy-key,deploy,部署,金鑰,gh"),
        GitTweak.Tool("gh.repo-deploykey-add", "Add deploy key", "新增部署金鑰",
            "Add a deploy key from a public key file.", "由一個公鑰檔案新增部署金鑰。",
            "Add", "新增", "gh", "repo deploy-key add key.pub", keywords: "repo,deploy-key,add,部署,金鑰,gh"),
        GitTweak.Tool("gh.repo-deploykey-delete", "Delete deploy key", "刪除部署金鑰",
            "Remove a deploy key by its ID.", "用 ID 移除一個部署金鑰。",
            "Delete", "刪除", "gh", "repo deploy-key delete KEY_ID", destructive: true, keywords: "repo,deploy-key,delete,部署,金鑰,gh"),
        GitTweak.Tool("gh.license-list", "List licenses", "列出授權",
            "List the open-source licenses GitHub knows about.", "列出 GitHub 認得嘅開源授權條款。",
            "List", "列出", "gh", "repo license list", keywords: "license,list,授權,gh"),
        GitTweak.Tool("gh.gitignore-list", "List gitignore templates", "列出 gitignore 範本",
            "List the available .gitignore templates.", "列出可用嘅 .gitignore 範本。",
            "List", "列出", "gh", "repo gitignore list", keywords: "gitignore,list,範本,gh"),
        GitTweak.Tool("gh.gitignore-view", "View gitignore template", "睇 gitignore 範本",
            "View the contents of a named .gitignore template.", "睇返某個 .gitignore 範本嘅內容。",
            "View", "查睇", "gh", "repo gitignore view VisualStudio", keywords: "gitignore,view,範本,gh"),

        // ===== issues =====
        GitTweak.Tool("gh.issue-list", "List open issues", "列出開緊嘅 Issue",
            "List the open issues for this repository.", "列出呢個 repo 開緊嘅 issue。",
            "List", "列出", "gh", "issue list", keywords: "issue,list,開,gh"),
        GitTweak.Tool("gh.issue-list-all", "List all issues", "列出所有 Issue",
            "List issues in every state for this repository.", "列出呢個 repo 所有狀態嘅 issue。",
            "List", "列出", "gh", "issue list --state all", keywords: "issue,all,所有,gh"),
        GitTweak.Tool("gh.issue-list-mine", "Issues assigned to me", "派畀我嘅 Issue",
            "List issues assigned to you in this repository.", "列出呢個 repo 派咗畀你嘅 issue。",
            "List", "列出", "gh", "issue list --assignee @me", keywords: "issue,assignee,me,我,gh"),
        GitTweak.Tool("gh.issue-list-label", "Issues by label", "按標籤列 Issue",
            "List issues carrying the 'bug' label.", "列出帶住 'bug' 標籤嘅 issue。",
            "List", "列出", "gh", "issue list --label bug", keywords: "issue,label,bug,標籤,gh"),
        GitTweak.Tool("gh.issue-view", "View an issue", "睇一個 Issue",
            "View the details of issue number N.", "睇返 issue 編號 N 嘅詳情。",
            "View", "查睇", "gh", "issue view N", keywords: "issue,view,gh"),
        GitTweak.Tool("gh.issue-create", "Create issue", "開 Issue",
            "Open a new issue with a title and body.", "開一個有標題同內容嘅新 issue。",
            "Create", "建立", "gh", "issue create --title \"Title\" --body \"Body\"", keywords: "issue,create,開,gh"),
        GitTweak.Tool("gh.issue-close", "Close issue", "關閉 Issue",
            "Close issue number N.", "關閉 issue 編號 N。",
            "Close", "關閉", "gh", "issue close N", destructive: true, keywords: "issue,close,關閉,gh"),
        GitTweak.Tool("gh.issue-reopen", "Reopen issue", "重開 Issue",
            "Reopen a previously closed issue number N.", "重開返之前關咗嘅 issue 編號 N。",
            "Reopen", "重開", "gh", "issue reopen N", keywords: "issue,reopen,重開,gh"),
        GitTweak.Tool("gh.issue-comment", "Comment on issue", "回應 Issue",
            "Add a comment to issue number N.", "喺 issue 編號 N 度加一個回應。",
            "Comment", "回應", "gh", "issue comment N --body \"Comment\"", keywords: "issue,comment,回應,gh"),
        GitTweak.Tool("gh.issue-edit-label", "Add label to issue", "畀 Issue 加標籤",
            "Add the 'bug' label to issue number N.", "畀 issue 編號 N 加 'bug' 標籤。",
            "Edit", "修改", "gh", "issue edit N --add-label bug", keywords: "issue,edit,label,標籤,gh"),
        GitTweak.Tool("gh.issue-delete", "Delete issue", "刪除 Issue",
            "Permanently delete issue number N.", "永久刪除 issue 編號 N。",
            "Delete", "刪除", "gh", "issue delete N --yes", destructive: true, keywords: "issue,delete,刪除,gh"),
        GitTweak.Tool("gh.issue-transfer", "Transfer issue", "轉移 Issue",
            "Transfer issue number N to another repository.", "將 issue 編號 N 轉移去另一個 repo。",
            "Transfer", "轉移", "gh", "issue transfer N OWNER/REPO", destructive: true, keywords: "issue,transfer,轉移,gh"),
        GitTweak.Tool("gh.issue-pin", "Pin issue", "釘住 Issue",
            "Pin issue number N to the top of the issues list.", "將 issue 編號 N 釘喺 issue 清單頂部。",
            "Pin", "釘住", "gh", "issue pin N", keywords: "issue,pin,釘,gh"),
        GitTweak.Tool("gh.issue-unpin", "Unpin issue", "取消釘住 Issue",
            "Unpin issue number N.", "取消釘住 issue 編號 N。",
            "Unpin", "取消釘", "gh", "issue unpin N", keywords: "issue,unpin,取消釘,gh"),
        GitTweak.Tool("gh.issue-lock", "Lock issue", "鎖定 Issue",
            "Lock conversation on issue number N.", "鎖定 issue 編號 N 嘅討論。",
            "Lock", "鎖定", "gh", "issue lock N", destructive: true, keywords: "issue,lock,鎖定,gh"),
        GitTweak.Tool("gh.issue-unlock", "Unlock issue", "解鎖 Issue",
            "Unlock conversation on issue number N.", "解鎖 issue 編號 N 嘅討論。",
            "Unlock", "解鎖", "gh", "issue unlock N", keywords: "issue,unlock,解鎖,gh"),
        GitTweak.Tool("gh.issue-develop", "Branch for issue", "為 Issue 開分支",
            "Create a linked branch to work on issue number N.", "開一條連結住 issue 編號 N 嘅分支去做嘢。",
            "Develop", "開分支", "gh", "issue develop N", keywords: "issue,develop,branch,分支,gh"),
        GitTweak.Tool("gh.issue-status", "Issue status", "Issue 狀態",
            "Show the status of issues relevant to you.", "睇返同你有關嘅 issue 嘅狀態。",
            "Show", "顯示", "gh", "issue status", keywords: "issue,status,狀態,gh"),

        // ===== pull requests =====
        GitTweak.Tool("gh.pr-list", "List pull requests", "列出 PR",
            "List open pull requests for this repository.", "列出呢個 repo 開緊嘅 PR。",
            "List", "列出", "gh", "pr list", keywords: "pr,pull request,列出,gh"),
        GitTweak.Tool("gh.pr-list-all", "List all PRs", "列出所有 PR",
            "List pull requests in every state.", "列出所有狀態嘅 PR。",
            "List", "列出", "gh", "pr list --state all", keywords: "pr,all,所有,gh"),
        GitTweak.Tool("gh.pr-view", "View current PR", "睇目前 PR",
            "View the pull request for the current branch.", "睇返同而家呢條分支有關嘅 PR。",
            "View", "查睇", "gh", "pr view", keywords: "pr,view,分支,gh"),
        GitTweak.Tool("gh.pr-view-web", "Open PR in browser", "喺瀏覽器開 PR",
            "Open the current pull request on GitHub.", "喺瀏覽器度開返而家嘅 PR。",
            "Open", "開啟", "gh", "pr view --web", keywords: "pr,web,browser,瀏覽器,gh"),
        GitTweak.Tool("gh.pr-checkout", "Check out a PR", "切去某個 PR",
            "Check out the branch of pull request number N.", "切去 PR 編號 N 嘅分支。",
            "Checkout", "切換", "gh", "pr checkout N", keywords: "pr,checkout,切換,gh"),
        GitTweak.Tool("gh.pr-diff", "PR diff", "PR 差異",
            "Show the diff of the current pull request.", "睇返而家 PR 嘅 diff。",
            "Show", "顯示", "gh", "pr diff", keywords: "pr,diff,差異,gh"),
        GitTweak.Tool("gh.pr-create-fill", "Create PR (auto-fill)", "建立 PR（自動填）",
            "Create a pull request, filling title and body from commits.", "建立 PR，由提交自動填好標題同內容。",
            "Create", "建立", "gh", "pr create --fill", keywords: "pr,create,fill,建立,gh"),
        GitTweak.Tool("gh.pr-create-draft", "Create draft PR", "建立草稿 PR",
            "Create a draft pull request, filling from commits.", "建立一個草稿 PR，由提交自動填好。",
            "Create", "建立", "gh", "pr create --draft --fill", keywords: "pr,create,draft,草稿,gh"),
        GitTweak.Tool("gh.pr-merge-merge", "Merge PR (merge)", "合併 PR（合併）",
            "Merge the current pull request with a merge commit.", "用合併提交將而家嘅 PR 合併。",
            "Merge", "合併", "gh", "pr merge --merge", destructive: true, keywords: "pr,merge,合併,gh"),
        GitTweak.Tool("gh.pr-merge-squash", "Merge PR (squash)", "合併 PR（壓縮）",
            "Squash-merge the current pull request into one commit.", "將而家嘅 PR 壓縮合併成一個提交。",
            "Merge", "合併", "gh", "pr merge --squash", destructive: true, keywords: "pr,merge,squash,壓縮,gh"),
        GitTweak.Tool("gh.pr-merge-rebase", "Merge PR (rebase)", "合併 PR（變基）",
            "Rebase-merge the current pull request.", "用變基方式合併而家嘅 PR。",
            "Merge", "合併", "gh", "pr merge --rebase", destructive: true, keywords: "pr,merge,rebase,變基,gh"),
        GitTweak.Tool("gh.pr-close", "Close PR", "關閉 PR",
            "Close pull request number N without merging.", "關閉 PR 編號 N，唔合併佢。",
            "Close", "關閉", "gh", "pr close N", destructive: true, keywords: "pr,close,關閉,gh"),
        GitTweak.Tool("gh.pr-reopen", "Reopen PR", "重開 PR",
            "Reopen a previously closed pull request number N.", "重開返之前關咗嘅 PR 編號 N。",
            "Reopen", "重開", "gh", "pr reopen N", keywords: "pr,reopen,重開,gh"),
        GitTweak.Tool("gh.pr-ready", "Mark PR ready", "標 PR 為就緒",
            "Mark the current draft pull request as ready for review.", "將而家嘅草稿 PR 標做可以覆核。",
            "Ready", "就緒", "gh", "pr ready", keywords: "pr,ready,draft,就緒,gh"),
        GitTweak.Tool("gh.pr-review-approve", "Approve PR", "批准 PR",
            "Approve the current pull request.", "批准而家嘅 PR。",
            "Approve", "批准", "gh", "pr review --approve", keywords: "pr,review,approve,批准,gh"),
        GitTweak.Tool("gh.pr-review-request-changes", "Request changes", "要求修改",
            "Submit a request-changes review with a body comment.", "提交一個要求修改嘅覆核，連埋意見。",
            "Review", "覆核", "gh", "pr review --request-changes --body \"Please fix\"", keywords: "pr,review,request changes,修改,gh"),
        GitTweak.Tool("gh.pr-review-comment", "Comment review", "覆核意見",
            "Submit a comment-only review on the current PR.", "喺而家嘅 PR 提交一個淨係意見嘅覆核。",
            "Review", "覆核", "gh", "pr review --comment --body \"Looks good\"", keywords: "pr,review,comment,意見,gh"),
        GitTweak.Tool("gh.pr-comment", "Comment on PR", "回應 PR",
            "Add a comment to the current pull request.", "喺而家嘅 PR 度加一個回應。",
            "Comment", "回應", "gh", "pr comment --body \"Comment\"", keywords: "pr,comment,回應,gh"),
        GitTweak.Tool("gh.pr-edit-reviewer", "Add reviewer", "加覆核者",
            "Request a reviewer on the current pull request.", "喺而家嘅 PR 度要求一個覆核者。",
            "Edit", "修改", "gh", "pr edit --add-reviewer USERNAME", keywords: "pr,edit,reviewer,覆核者,gh"),
        GitTweak.Tool("gh.pr-checks", "PR checks", "PR 檢查",
            "Show the status of CI checks on the current PR.", "睇返而家 PR 上面 CI 檢查嘅狀態。",
            "Show", "顯示", "gh", "pr checks", keywords: "pr,checks,ci,檢查,gh"),
        GitTweak.Tool("gh.pr-status", "Pull request status", "PR 狀態",
            "Show the status of pull requests relevant to you.", "睇返同你有關嘅 PR 嘅狀態。",
            "Show", "顯示", "gh", "pr status", keywords: "pr,status,狀態,gh"),
        GitTweak.Tool("gh.pr-lock", "Lock PR", "鎖定 PR",
            "Lock conversation on pull request number N.", "鎖定 PR 編號 N 嘅討論。",
            "Lock", "鎖定", "gh", "pr lock N", destructive: true, keywords: "pr,lock,鎖定,gh"),

        // ===== actions =====
        GitTweak.Tool("gh.run-list", "List workflow runs", "列出工作流程執行",
            "List recent GitHub Actions workflow runs.", "列出近排 GitHub Actions 嘅工作流程執行記錄。",
            "List", "列出", "gh", "run list", keywords: "run,actions,workflow,執行,gh"),
        GitTweak.Tool("gh.run-view", "View a run", "睇一次執行",
            "View details of a workflow run.", "睇返某次工作流程執行嘅詳情。",
            "View", "查睇", "gh", "run view", keywords: "run,view,執行,gh"),
        GitTweak.Tool("gh.run-view-log", "View run logs", "睇執行記錄",
            "View the full logs of a workflow run.", "睇返某次工作流程執行嘅完整記錄。",
            "View", "查睇", "gh", "run view --log", keywords: "run,log,記錄,gh"),
        GitTweak.Tool("gh.run-watch", "Watch a run", "監看執行",
            "Watch a workflow run until it completes.", "監看一次工作流程執行直到佢完成。",
            "Watch", "監看", "gh", "run watch", keywords: "run,watch,監看,gh"),
        GitTweak.Tool("gh.run-rerun", "Rerun workflow", "重新執行工作流程",
            "Rerun all jobs in a workflow run.", "重新執行某次工作流程入面嘅所有作業。",
            "Rerun", "重跑", "gh", "run rerun", destructive: true, keywords: "run,rerun,重跑,gh"),
        GitTweak.Tool("gh.run-rerun-failed", "Rerun failed jobs", "重跑失敗作業",
            "Rerun only the failed jobs in a workflow run.", "淨係重新執行某次執行入面失敗咗嘅作業。",
            "Rerun", "重跑", "gh", "run rerun --failed", destructive: true, keywords: "run,rerun,failed,失敗,gh"),
        GitTweak.Tool("gh.run-cancel", "Cancel run", "取消執行",
            "Cancel an in-progress workflow run.", "取消進行緊嘅工作流程執行。",
            "Cancel", "取消", "gh", "run cancel", destructive: true, keywords: "run,cancel,取消,gh"),
        GitTweak.Tool("gh.run-download", "Download artifacts", "下載產物",
            "Download artifacts produced by a workflow run.", "下載某次工作流程執行整出嚟嘅產物。",
            "Download", "下載", "gh", "run download", keywords: "run,download,artifacts,產物,gh"),
        GitTweak.Tool("gh.workflow-list", "List workflows", "列出工作流程",
            "List the GitHub Actions workflows in this repository.", "列出呢個 repo 嘅 GitHub Actions 工作流程。",
            "List", "列出", "gh", "workflow list", keywords: "workflow,actions,工作流程,gh"),
        GitTweak.Tool("gh.workflow-view", "View workflow", "睇工作流程",
            "View details of a workflow.", "睇返某個工作流程嘅詳情。",
            "View", "查睇", "gh", "workflow view", keywords: "workflow,view,工作流程,gh"),
        GitTweak.Tool("gh.workflow-run", "Run workflow", "執行工作流程",
            "Manually trigger a workflow by name.", "用名手動觸發一個工作流程。",
            "Run", "執行", "gh", "workflow run NAME", keywords: "workflow,run,dispatch,執行,gh"),
        GitTweak.Tool("gh.workflow-enable", "Enable workflow", "啟用工作流程",
            "Enable a disabled workflow.", "啟用返一個停用咗嘅工作流程。",
            "Enable", "啟用", "gh", "workflow enable NAME", keywords: "workflow,enable,啟用,gh"),
        GitTweak.Tool("gh.workflow-disable", "Disable workflow", "停用工作流程",
            "Disable a workflow so it stops running.", "停用一個工作流程令佢唔再行。",
            "Disable", "停用", "gh", "workflow disable NAME", destructive: true, keywords: "workflow,disable,停用,gh"),
        GitTweak.Tool("gh.cache-list", "List Actions caches", "列出 Actions 快取",
            "List the GitHub Actions caches for this repository.", "列出呢個 repo 嘅 GitHub Actions 快取。",
            "List", "列出", "gh", "cache list", keywords: "cache,actions,快取,gh"),
        GitTweak.Tool("gh.cache-delete-all", "Delete all caches", "刪除全部快取",
            "Delete every GitHub Actions cache in this repository.", "刪除呢個 repo 入面所有 GitHub Actions 快取。",
            "Delete", "刪除", "gh", "cache delete --all", destructive: true, keywords: "cache,delete,all,快取,gh"),

        // ===== releases =====
        GitTweak.Tool("gh.release-list", "List releases", "列出 Release",
            "List releases published for this repository.", "列出呢個 repo 出咗嘅 release。",
            "List", "列出", "gh", "release list", keywords: "release,list,版本,gh"),
        GitTweak.Tool("gh.release-view", "View latest release", "睇最新 Release",
            "View details of the latest release.", "睇返最新一個 release 嘅詳情。",
            "View", "查睇", "gh", "release view", keywords: "release,view,版本,gh"),
        GitTweak.Tool("gh.release-create", "Create release", "建立 Release",
            "Create a release for tag v1.0.0 with notes.", "為標籤 v1.0.0 建立一個 release，連埋說明。",
            "Create", "建立", "gh", "release create v1.0.0 --notes \"Release notes\"", keywords: "release,create,版本,gh"),
        GitTweak.Tool("gh.release-upload", "Upload release asset", "上載 Release 檔案",
            "Upload a file as an asset on release v1.0.0.", "將一個檔案上載做 release v1.0.0 嘅資產。",
            "Upload", "上載", "gh", "release upload v1.0.0 README.md", keywords: "release,upload,asset,資產,gh"),
        GitTweak.Tool("gh.release-download", "Download release assets", "下載 Release 檔案",
            "Download the assets from release v1.0.0.", "下載 release v1.0.0 嘅資產。",
            "Download", "下載", "gh", "release download v1.0.0", keywords: "release,download,asset,資產,gh"),
        GitTweak.Tool("gh.release-edit", "Edit release", "修改 Release",
            "Edit metadata of release v1.0.0.", "修改 release v1.0.0 嘅中繼資料。",
            "Edit", "修改", "gh", "release edit v1.0.0 --notes \"Updated notes\"", keywords: "release,edit,修改,gh"),
        GitTweak.Tool("gh.release-delete", "Delete release", "刪除 Release",
            "Permanently delete release v1.0.0.", "永久刪除 release v1.0.0。",
            "Delete", "刪除", "gh", "release delete v1.0.0 --yes", destructive: true, keywords: "release,delete,刪除,gh"),
        GitTweak.Tool("gh.release-delete-asset", "Delete release asset", "刪除 Release 檔案",
            "Delete a single asset from release v1.0.0.", "由 release v1.0.0 刪除一個資產。",
            "Delete", "刪除", "gh", "release delete-asset v1.0.0 README.md", destructive: true, keywords: "release,delete-asset,資產,gh"),

        // ===== gists =====
        GitTweak.Tool("gh.gist-list", "List gists", "列出 Gist",
            "List your gists via the GitHub CLI.", "用 GitHub CLI 列出你嘅 gist。",
            "List", "列出", "gh", "gist list", keywords: "gist,list,gh"),
        GitTweak.Tool("gh.gist-view", "View a gist", "睇一個 Gist",
            "View the contents of a gist.", "睇返某個 gist 嘅內容。",
            "View", "查睇", "gh", "gist view", keywords: "gist,view,gh"),
        GitTweak.Tool("gh.gist-create", "Create gist", "建立 Gist",
            "Create a secret gist from a file.", "由一個檔案建立一個秘密 gist。",
            "Create", "建立", "gh", "gist create README.md", keywords: "gist,create,建立,gh"),
        GitTweak.Tool("gh.gist-create-public", "Create public gist", "建立公開 Gist",
            "Create a public gist from a file.", "由一個檔案建立一個公開 gist。",
            "Create", "建立", "gh", "gist create --public README.md", keywords: "gist,create,public,公開,gh"),
        GitTweak.Tool("gh.gist-edit", "Edit gist", "修改 Gist",
            "Edit the contents of an existing gist.", "修改一個現有 gist 嘅內容。",
            "Edit", "修改", "gh", "gist edit", keywords: "gist,edit,修改,gh"),
        GitTweak.Tool("gh.gist-clone", "Clone gist", "複製 Gist",
            "Clone a gist to your local machine.", "將一個 gist 複製落你部機。",
            "Clone", "複製", "gh", "gist clone GIST_ID", keywords: "gist,clone,複製,gh"),
        GitTweak.Tool("gh.gist-delete", "Delete gist", "刪除 Gist",
            "Permanently delete a gist.", "永久刪除一個 gist。",
            "Delete", "刪除", "gh", "gist delete GIST_ID --yes", destructive: true, keywords: "gist,delete,刪除,gh"),
        GitTweak.Tool("gh.gist-rename", "Rename gist file", "改 Gist 檔名",
            "Rename a file within a gist.", "將 gist 入面一個檔案改名。",
            "Rename", "改名", "gh", "gist rename GIST_ID old.txt new.txt", keywords: "gist,rename,改名,gh"),

        // ===== secrets / variables =====
        GitTweak.Tool("gh.secret-list", "List secrets", "列出密鑰",
            "List the names of secrets set for this repository.", "列出呢個 repo 設定咗嘅密鑰名稱。",
            "List", "列出", "gh", "secret list", keywords: "secret,list,密鑰,gh"),
        GitTweak.Tool("gh.secret-set", "Set a secret", "設定密鑰",
            "Set or update a repository secret value.", "設定或更新一個 repo 密鑰嘅值。",
            "Set", "設定", "gh", "secret set NAME", keywords: "secret,set,密鑰,gh"),
        GitTweak.Tool("gh.secret-delete", "Delete a secret", "刪除密鑰",
            "Delete a repository secret by name.", "用名刪除一個 repo 密鑰。",
            "Delete", "刪除", "gh", "secret delete NAME", destructive: true, keywords: "secret,delete,刪除,密鑰,gh"),
        GitTweak.Tool("gh.variable-list", "List variables", "列出變數",
            "List the Actions variables for this repository.", "列出呢個 repo 嘅 Actions 變數。",
            "List", "列出", "gh", "variable list", keywords: "variable,list,變數,gh"),
        GitTweak.Tool("gh.variable-set", "Set a variable", "設定變數",
            "Set or update an Actions variable value.", "設定或更新一個 Actions 變數嘅值。",
            "Set", "設定", "gh", "variable set NAME", keywords: "variable,set,變數,gh"),
        GitTweak.Tool("gh.variable-delete", "Delete a variable", "刪除變數",
            "Delete an Actions variable by name.", "用名刪除一個 Actions 變數。",
            "Delete", "刪除", "gh", "variable delete NAME", destructive: true, keywords: "variable,delete,刪除,變數,gh"),

        // ===== labels =====
        GitTweak.Tool("gh.label-list", "List labels", "列出標籤",
            "List the labels defined in this repository.", "列出呢個 repo 入面定義咗嘅標籤。",
            "List", "列出", "gh", "label list", keywords: "label,list,標籤,gh"),
        GitTweak.Tool("gh.label-create", "Create label", "建立標籤",
            "Create a new label with a colour.", "建立一個有顏色嘅新標籤。",
            "Create", "建立", "gh", "label create NAME --color FF0000", keywords: "label,create,標籤,gh"),
        GitTweak.Tool("gh.label-edit", "Edit label", "修改標籤",
            "Edit an existing label's colour or description.", "修改一個現有標籤嘅顏色或描述。",
            "Edit", "修改", "gh", "label edit NAME --description \"New description\"", keywords: "label,edit,修改,標籤,gh"),
        GitTweak.Tool("gh.label-delete", "Delete label", "刪除標籤",
            "Permanently delete a label by name.", "用名永久刪除一個標籤。",
            "Delete", "刪除", "gh", "label delete NAME --yes", destructive: true, keywords: "label,delete,刪除,標籤,gh"),
        GitTweak.Tool("gh.label-clone", "Clone labels", "複製標籤",
            "Clone labels from another repository into this one.", "由另一個 repo 將標籤複製入嚟。",
            "Clone", "複製", "gh", "label clone OWNER/REPO", keywords: "label,clone,複製,標籤,gh"),

        // ===== keys =====
        GitTweak.Tool("gh.sshkey-list", "List SSH keys", "列出 SSH 金鑰",
            "List the SSH keys on your GitHub account.", "列出你 GitHub 帳號上面嘅 SSH 金鑰。",
            "List", "列出", "gh", "ssh-key list", keywords: "ssh-key,list,ssh,金鑰,gh"),
        GitTweak.Tool("gh.sshkey-add", "Add SSH key", "新增 SSH 金鑰",
            "Add an SSH public key from a file.", "由一個檔案新增 SSH 公鑰。",
            "Add", "新增", "gh", "ssh-key add key.pub", keywords: "ssh-key,add,ssh,金鑰,gh"),
        GitTweak.Tool("gh.sshkey-delete", "Delete SSH key", "刪除 SSH 金鑰",
            "Remove an SSH key from your account by ID.", "用 ID 由你帳號移除一個 SSH 金鑰。",
            "Delete", "刪除", "gh", "ssh-key delete KEY_ID", destructive: true, keywords: "ssh-key,delete,ssh,金鑰,gh"),
        GitTweak.Tool("gh.gpgkey-list", "List GPG keys", "列出 GPG 金鑰",
            "List the GPG keys on your GitHub account.", "列出你 GitHub 帳號上面嘅 GPG 金鑰。",
            "List", "列出", "gh", "gpg-key list", keywords: "gpg-key,list,gpg,金鑰,gh"),
        GitTweak.Tool("gh.gpgkey-add", "Add GPG key", "新增 GPG 金鑰",
            "Add a GPG public key from a file.", "由一個檔案新增 GPG 公鑰。",
            "Add", "新增", "gh", "gpg-key add key.asc", keywords: "gpg-key,add,gpg,金鑰,gh"),
        GitTweak.Tool("gh.gpgkey-delete", "Delete GPG key", "刪除 GPG 金鑰",
            "Remove a GPG key from your account by ID.", "用 ID 由你帳號移除一個 GPG 金鑰。",
            "Delete", "刪除", "gh", "gpg-key delete KEY_ID", destructive: true, keywords: "gpg-key,delete,gpg,金鑰,gh"),

        // ===== projects / codespaces / org =====
        GitTweak.Tool("gh.project-list", "List projects", "列出專案",
            "List GitHub Projects you have access to.", "列出你有權存取嘅 GitHub Projects。",
            "List", "列出", "gh", "project list", keywords: "project,list,專案,gh"),
        GitTweak.Tool("gh.project-view", "View project", "睇專案",
            "View details of a GitHub Project.", "睇返某個 GitHub Project 嘅詳情。",
            "View", "查睇", "gh", "project view", keywords: "project,view,專案,gh"),
        GitTweak.Tool("gh.project-item-list", "List project items", "列出專案項目",
            "List the items in a GitHub Project.", "列出某個 GitHub Project 入面嘅項目。",
            "List", "列出", "gh", "project item-list", keywords: "project,item-list,項目,gh"),
        GitTweak.Tool("gh.codespace-list", "List codespaces", "列出 Codespace",
            "List your GitHub Codespaces.", "列出你嘅 GitHub Codespaces。",
            "List", "列出", "gh", "codespace list", keywords: "codespace,list,gh"),
        GitTweak.Tool("gh.codespace-create", "Create codespace", "建立 Codespace",
            "Create a new codespace for this repository.", "為呢個 repo 建立一個新 codespace。",
            "Create", "建立", "gh", "codespace create", keywords: "codespace,create,建立,gh"),
        GitTweak.Tool("gh.codespace-stop", "Stop codespace", "停止 Codespace",
            "Stop a running codespace.", "停止一個行緊嘅 codespace。",
            "Stop", "停止", "gh", "codespace stop", keywords: "codespace,stop,停止,gh"),
        GitTweak.Tool("gh.codespace-delete", "Delete codespace", "刪除 Codespace",
            "Permanently delete a codespace.", "永久刪除一個 codespace。",
            "Delete", "刪除", "gh", "codespace delete", destructive: true, keywords: "codespace,delete,刪除,gh"),
        GitTweak.Tool("gh.codespace-ssh", "SSH into codespace", "SSH 入 Codespace",
            "Open an SSH session into a codespace.", "開一個 SSH 工作階段入去 codespace。",
            "SSH", "連線", "gh", "codespace ssh", keywords: "codespace,ssh,連線,gh"),
        GitTweak.Tool("gh.codespace-ports", "Codespace ports", "Codespace 連接埠",
            "List the forwarded ports of a codespace.", "列出某個 codespace 轉送咗嘅連接埠。",
            "List", "列出", "gh", "codespace ports", keywords: "codespace,ports,連接埠,gh"),
        GitTweak.Tool("gh.org-list", "List organisations", "列出組織",
            "List the organisations you belong to.", "列出你所屬嘅組織。",
            "List", "列出", "gh", "org list", keywords: "org,list,組織,gh"),
        GitTweak.Tool("gh.status", "GitHub status", "GitHub 狀態",
            "Show what is going on across GitHub for you right now.", "睇返你而家喺 GitHub 各處嘅最新狀況。",
            "Show", "顯示", "gh", "status", keywords: "status,狀態,gh"),

        // ===== search =====
        GitTweak.Tool("gh.search-repos", "Search repos", "搜尋 Repo",
            "Search across GitHub for repositories matching a query.", "喺成個 GitHub 度搵符合查詢嘅 repo。",
            "Search", "搜尋", "gh", "search repos QUERY", keywords: "search,repos,搜尋,gh"),
        GitTweak.Tool("gh.search-issues", "Search issues", "搜尋 Issue",
            "Search across GitHub for issues matching a query.", "喺成個 GitHub 度搵符合查詢嘅 issue。",
            "Search", "搜尋", "gh", "search issues QUERY", keywords: "search,issues,搜尋,gh"),
        GitTweak.Tool("gh.search-prs-me", "My pull requests", "我開嘅 PR",
            "Search across GitHub for pull requests you authored.", "喺成個 GitHub 度搵返你開嘅 PR。",
            "Search", "搜尋", "gh", "search prs --author=@me", keywords: "search,pr,author,me,gh"),
        GitTweak.Tool("gh.search-code", "Search code", "搜尋程式碼",
            "Search across GitHub for code matching a query.", "喺成個 GitHub 度搵符合查詢嘅程式碼。",
            "Search", "搜尋", "gh", "search code QUERY", keywords: "search,code,程式碼,gh"),
        GitTweak.Tool("gh.search-commits", "Search commits", "搜尋提交",
            "Search across GitHub for commits matching a query.", "喺成個 GitHub 度搵符合查詢嘅提交。",
            "Search", "搜尋", "gh", "search commits QUERY", keywords: "search,commits,提交,gh"),

        // ===== rulesets =====
        GitTweak.Tool("gh.ruleset-list", "List rulesets", "列出規則集",
            "List the rulesets configured for this repository.", "列出呢個 repo 設定咗嘅規則集。",
            "List", "列出", "gh", "ruleset list", keywords: "ruleset,rules,規則,gh"),
        GitTweak.Tool("gh.ruleset-view", "View ruleset", "睇規則集",
            "View details of a repository ruleset.", "睇返某個 repo 規則集嘅詳情。",
            "View", "查睇", "gh", "ruleset view", keywords: "ruleset,view,規則,gh"),
        GitTweak.Tool("gh.ruleset-check", "Check rulesets", "檢查規則集",
            "Check which rulesets apply to the current branch.", "檢查邊啲規則集套用喺而家呢條分支。",
            "Check", "檢查", "gh", "ruleset check", keywords: "ruleset,check,規則,檢查,gh"),

        // ===== api: repo-level features =====
        GitTweak.Tool("gh.api-branches", "Branches", "分支",
            "List the branches of this repository via the API.", "用 API 列出呢個 repo 嘅分支。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/branches", keywords: "api,branches,分支,gh"),
        GitTweak.Tool("gh.api-branch-protection", "Branch protection", "分支保護",
            "Show the protection settings on the main branch.", "睇返 main 分支嘅保護設定。",
            "Show", "顯示", "gh", "api repos/{owner}/{repo}/branches/main/protection", keywords: "api,branch protection,保護,gh"),
        GitTweak.Tool("gh.api-collaborators", "Collaborators", "協作者",
            "List the collaborators on this repository.", "列出呢個 repo 嘅協作者。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/collaborators", keywords: "api,collaborators,協作者,gh"),
        GitTweak.Tool("gh.api-teams", "Repo teams", "Repo 團隊",
            "List the teams with access to this repository.", "列出有權存取呢個 repo 嘅團隊。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/teams", keywords: "api,teams,團隊,gh"),
        GitTweak.Tool("gh.api-hooks", "Repo webhooks", "Repo Webhook",
            "List the webhooks configured on this repository.", "列出呢個 repo 設定咗嘅 webhook。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/hooks", keywords: "api,hooks,webhooks,gh"),
        GitTweak.Tool("gh.api-deployments", "Deployments", "部署",
            "List the deployments for this repository.", "列出呢個 repo 嘅部署。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/deployments", keywords: "api,deployments,部署,gh"),
        GitTweak.Tool("gh.api-environments", "Environments", "環境",
            "List the deployment environments for this repository.", "列出呢個 repo 嘅部署環境。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/environments", keywords: "api,environments,環境,gh"),
        GitTweak.Tool("gh.api-pages", "GitHub Pages", "GitHub Pages",
            "Show the GitHub Pages configuration for this repository.", "睇返呢個 repo 嘅 GitHub Pages 設定。",
            "Show", "顯示", "gh", "api repos/{owner}/{repo}/pages", keywords: "api,pages,gh"),
        GitTweak.Tool("gh.api-traffic-views", "Traffic: views", "流量：瀏覽",
            "Show the page-view traffic for this repository.", "睇返呢個 repo 嘅頁面瀏覽流量。",
            "Show", "顯示", "gh", "api repos/{owner}/{repo}/traffic/views", keywords: "api,traffic,views,流量,瀏覽,gh"),
        GitTweak.Tool("gh.api-traffic-clones", "Traffic: clones", "流量：複製",
            "Show the clone traffic for this repository.", "睇返呢個 repo 嘅複製流量。",
            "Show", "顯示", "gh", "api repos/{owner}/{repo}/traffic/clones", keywords: "api,traffic,clones,流量,複製,gh"),
        GitTweak.Tool("gh.api-topics", "Repo topics", "Repo 主題",
            "List the topics assigned to this repository.", "列出呢個 repo 設咗嘅主題標籤。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/topics", keywords: "api,topics,主題,gh"),
        GitTweak.Tool("gh.api-languages", "Repo languages", "Repo 語言",
            "Show the language breakdown of this repository.", "睇返呢個 repo 嘅程式語言分佈。",
            "Show", "顯示", "gh", "api repos/{owner}/{repo}/languages", keywords: "api,languages,語言,gh"),
        GitTweak.Tool("gh.api-tags", "Repo tags", "Repo 標籤",
            "List the tags of this repository via the API.", "用 API 列出呢個 repo 嘅標籤。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/tags", keywords: "api,tags,標籤,gh"),
        GitTweak.Tool("gh.api-contributors", "Contributors", "貢獻者",
            "List the contributors to this repository.", "列出呢個 repo 嘅貢獻者。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/contributors", keywords: "api,contributors,貢獻者,gh"),
        GitTweak.Tool("gh.api-forks", "Forks", "分叉",
            "List the forks of this repository.", "列出呢個 repo 嘅分叉。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/forks", keywords: "api,forks,分叉,gh"),
        GitTweak.Tool("gh.api-stargazers", "Stargazers", "Star 嘅人",
            "List the users who starred this repository.", "列出畀呢個 repo star 嘅用戶。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/stargazers", keywords: "api,stargazers,star,gh"),
        GitTweak.Tool("gh.api-subscribers", "Watchers", "關注者",
            "List the users watching this repository.", "列出關注緊呢個 repo 嘅用戶。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/subscribers", keywords: "api,subscribers,watchers,關注,gh"),
        GitTweak.Tool("gh.api-milestones", "Milestones", "里程碑",
            "List the milestones for this repository.", "列出呢個 repo 嘅里程碑。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/milestones", keywords: "api,milestones,里程碑,gh"),
        GitTweak.Tool("gh.api-commits", "Commits (API)", "提交（API）",
            "List recent commits for this repository via the API.", "用 API 列出呢個 repo 近排嘅提交。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/commits", keywords: "api,commits,提交,gh"),
        GitTweak.Tool("gh.api-community-profile", "Community profile", "社群檔案",
            "Show the community-profile health metrics for this repo.", "睇返呢個 repo 嘅社群檔案健康指標。",
            "Show", "顯示", "gh", "api repos/{owner}/{repo}/community/profile", keywords: "api,community,profile,社群,gh"),
        GitTweak.Tool("gh.api-code-scanning-alerts", "Code scanning alerts", "程式碼掃描警示",
            "List code-scanning alerts for this repository.", "列出呢個 repo 嘅程式碼掃描警示。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/code-scanning/alerts", keywords: "api,code-scanning,alerts,掃描,警示,gh"),
        GitTweak.Tool("gh.api-secret-scanning-alerts", "Secret scanning alerts", "密鑰掃描警示",
            "List secret-scanning alerts for this repository.", "列出呢個 repo 嘅密鑰掃描警示。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/secret-scanning/alerts", keywords: "api,secret-scanning,alerts,密鑰,警示,gh"),
        GitTweak.Tool("gh.api-dependabot-alerts", "Dependabot alerts", "Dependabot 警示",
            "List Dependabot vulnerability alerts for this repository.", "列出呢個 repo 嘅 Dependabot 漏洞警示。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/dependabot/alerts", keywords: "api,dependabot,alerts,漏洞,警示,gh"),
        GitTweak.Tool("gh.api-vulnerability-alerts", "Vulnerability alerts", "漏洞警示",
            "Check whether vulnerability alerts are enabled on this repo.", "檢查呢個 repo 有冇開啟漏洞警示。",
            "Check", "檢查", "gh", "api repos/{owner}/{repo}/vulnerability-alerts", keywords: "api,vulnerability-alerts,漏洞,警示,gh"),
        GitTweak.Tool("gh.api-contents-readme", "File contents", "檔案內容",
            "Fetch the contents of README.md via the API.", "用 API 攞返 README.md 嘅內容。",
            "Fetch", "攞返", "gh", "api repos/{owner}/{repo}/contents/README.md", keywords: "api,contents,readme,內容,gh"),
        GitTweak.Tool("gh.api-compare", "Compare commits", "比較提交",
            "Compare two commits or branches via the API.", "用 API 比較兩個提交或者分支。",
            "Compare", "比較", "gh", "api repos/{owner}/{repo}/compare/main...feature", keywords: "api,compare,比較,gh"),
        GitTweak.Tool("gh.api-releases-latest", "Latest release (API)", "最新 Release（API）",
            "Fetch the latest release via the API.", "用 API 攞返最新嘅 release。",
            "Fetch", "攞返", "gh", "api repos/{owner}/{repo}/releases/latest", keywords: "api,releases,latest,版本,gh"),
        GitTweak.Tool("gh.api-actions-permissions", "Actions permissions", "Actions 權限",
            "Show the GitHub Actions permissions for this repository.", "睇返呢個 repo 嘅 GitHub Actions 權限。",
            "Show", "顯示", "gh", "api repos/{owner}/{repo}/actions/permissions", keywords: "api,actions,permissions,權限,gh"),
        GitTweak.Tool("gh.api-runners", "Self-hosted runners", "自架執行器",
            "List the self-hosted Actions runners for this repository.", "列出呢個 repo 嘅自架 Actions 執行器。",
            "List", "列出", "gh", "api repos/{owner}/{repo}/actions/runners", keywords: "api,runners,self-hosted,執行器,gh"),

        // ===== api: account-level features =====
        GitTweak.Tool("gh.api-notifications", "Notifications", "通知",
            "List your GitHub notifications.", "列出你嘅 GitHub 通知。",
            "List", "列出", "gh", "api notifications", keywords: "api,notifications,通知,gh"),
        GitTweak.Tool("gh.api-user-starred", "Your stars", "你 Star 嘅",
            "List the repositories you have starred.", "列出你 star 咗嘅 repo。",
            "List", "列出", "gh", "api user/starred", keywords: "api,starred,star,gh"),
        GitTweak.Tool("gh.api-user-subscriptions", "Watched repos", "你關注嘅 Repo",
            "List the repositories you are watching.", "列出你關注緊嘅 repo。",
            "List", "列出", "gh", "api user/subscriptions", keywords: "api,subscriptions,watching,關注,gh"),
        GitTweak.Tool("gh.api-user-followers", "Your followers", "你嘅追蹤者",
            "List the users who follow you.", "列出追蹤緊你嘅用戶。",
            "List", "列出", "gh", "api user/followers", keywords: "api,followers,追蹤者,gh"),
        GitTweak.Tool("gh.api-user-following", "Following", "你追蹤緊",
            "List the users you follow.", "列出你追蹤緊嘅用戶。",
            "List", "列出", "gh", "api user/following", keywords: "api,following,追蹤,gh"),
        GitTweak.Tool("gh.api-user-orgs", "Your organisations", "你嘅組織",
            "List the organisations you belong to via the API.", "用 API 列出你所屬嘅組織。",
            "List", "列出", "gh", "api user/orgs", keywords: "api,orgs,組織,gh"),
        GitTweak.Tool("gh.api-user-repos", "Your repos (API)", "你嘅 Repo（API）",
            "List your repositories via the API.", "用 API 列出你嘅 repo。",
            "List", "列出", "gh", "api user/repos", keywords: "api,repos,gh"),
        GitTweak.Tool("gh.api-user-gists", "Your gists (API)", "你嘅 Gist（API）",
            "List your gists via the API.", "用 API 列出你嘅 gist。",
            "List", "列出", "gh", "api user/gists", keywords: "api,gists,gh"),
        GitTweak.Tool("gh.api-user-issues", "Your issues", "你嘅 Issue",
            "List issues assigned to you across GitHub.", "列出成個 GitHub 度派咗畀你嘅 issue。",
            "List", "列出", "gh", "api user/issues", keywords: "api,issues,gh"),
        GitTweak.Tool("gh.api-gists-starred", "Starred gists", "你 Star 嘅 Gist",
            "List the gists you have starred.", "列出你 star 咗嘅 gist。",
            "List", "列出", "gh", "api gists/starred", keywords: "api,gists,starred,star,gh"),
        GitTweak.Tool("gh.api-user-keys", "Your SSH keys (API)", "你嘅 SSH 金鑰（API）",
            "List your SSH keys via the API.", "用 API 列出你嘅 SSH 金鑰。",
            "List", "列出", "gh", "api user/keys", keywords: "api,keys,ssh,金鑰,gh"),
        GitTweak.Tool("gh.api-user-gpg-keys", "Your GPG keys (API)", "你嘅 GPG 金鑰（API）",
            "List your GPG keys via the API.", "用 API 列出你嘅 GPG 金鑰。",
            "List", "列出", "gh", "api user/gpg_keys", keywords: "api,gpg,keys,金鑰,gh"),
        GitTweak.Tool("gh.api-octocat", "Octocat", "Octocat",
            "Fetch the Octocat ASCII art easter egg.", "攞返 Octocat 嘅 ASCII 圖案彩蛋。",
            "Fetch", "攞返", "gh", "api /octocat", keywords: "api,octocat,彩蛋,gh"),
        GitTweak.Tool("gh.api-zen", "GitHub Zen", "GitHub 禪語",
            "Fetch a random GitHub design philosophy phrase.", "攞返一句 GitHub 設計哲學嘅隨機句子。",
            "Fetch", "攞返", "gh", "api /zen", keywords: "api,zen,禪語,gh"),
        GitTweak.Tool("gh.api-star-repo", "Star this repo", "Star 呢個 Repo",
            "Star the current repository via the API.", "用 API 畀而家呢個 repo 加 star。",
            "Star", "加星", "gh", "api --method PUT user/starred/{owner}/{repo}", keywords: "api,star,加星,gh"),
        GitTweak.Tool("gh.api-unstar-repo", "Unstar this repo", "取消 Star",
            "Remove your star from the current repository via the API.", "用 API 由而家呢個 repo 攞返你個 star。",
            "Unstar", "取消星", "gh", "api --method DELETE user/starred/{owner}/{repo}", destructive: true, keywords: "api,unstar,取消星,gh"),
    };
}
