using System;
using System.Collections.Generic;
using WinTune.Models;
using WinTune.Services;

namespace WinTune.Catalog;

/// <summary>
/// Git 與 GitHub 操作目錄（喺選中嘅儲存庫執行）。
/// Catalog of 111 real Git/GitHub operations that run inside the selected repository.
/// 由 ultracode workflow 產生並經對抗式覆核。Generated and adversarially reviewed via an ultracode workflow.
/// </summary>
public static class GitOperations
{
    public static IEnumerable<TweakDefinition> All() => new List<TweakDefinition>
    {
        // ===== inspect (24) =====
        GitTweak.Git("git.status-short", "Status (short)", "狀態（精簡）",
    "Show a compact short-format working tree status with branch info.", "用精簡格式睇返工作區嘅狀態同埋分支資訊。",
    "Show", "顯示", "status --short --branch", keywords: "status,short,狀態,精簡"),
GitTweak.Git("git.status-long", "Status (full)", "狀態（完整）",
    "Show the full long-format working tree status.", "用完整格式睇返工作區嘅狀態。",
    "Show", "顯示", "status", keywords: "status,full,狀態,完整"),
GitTweak.Git("git.log-oneline", "Log (oneline)", "歷史（單行）",
    "Show recent commit history, one line per commit.", "每個提交一行咁睇返近排嘅歷史。",
    "Show", "顯示", "log --oneline -30", keywords: "log,oneline,歷史,單行"),
GitTweak.Git("git.log-graph", "Commit graph", "提交圖譜",
    "Show recent history as an ASCII graph with refs.", "用 ASCII 圖譜連埋分支標籤睇返近排嘅歷史。",
    "Show", "顯示", "log --oneline --graph --decorate --all -30", keywords: "log,graph,歷史,圖譜"),
GitTweak.Git("git.log-stat", "Log with stats", "歷史連統計",
    "Show recent commits with per-file change statistics.", "睇返近排嘅提交，連埋每個檔案嘅改動統計。",
    "Show", "顯示", "log --stat -10", keywords: "log,stat,歷史,統計"),
GitTweak.Git("git.log-patch", "Log with patches", "歷史連補丁",
    "Show recent commits with full diff patches inline.", "睇返近排嘅提交，連埋成個 diff 補丁。",
    "Show", "顯示", "log --patch -5", keywords: "log,patch,diff,補丁"),
GitTweak.Git("git.log-since", "Log (last 2 weeks)", "歷史（近兩週）",
    "Show commits authored in the last two weeks.", "睇返近兩個禮拜入面嘅提交。",
    "Show", "顯示", "log --oneline --since=\"2 weeks ago\"", keywords: "log,since,date,歷史,日期"),
GitTweak.Git("git.log-grep", "Search commit messages", "搜尋提交訊息",
    "Search commit messages for the word fix, case-insensitive.", "唔分大細階咁喺提交訊息度搵 fix 呢個字。",
    "Search", "搜尋", "log --oneline -i --grep=fix -30", keywords: "log,grep,search,搜尋,訊息"),
GitTweak.Git("git.log-file", "File history", "檔案歷史",
    "Show the commit history that touched README.md.", "睇返改動過 README.md 嘅提交歷史。",
    "Show", "顯示", "log --oneline --follow -- README.md", keywords: "log,file,history,檔案,歷史"),
GitTweak.Git("git.show-head", "Show HEAD commit", "顯示 HEAD 提交",
    "Show the latest commit details and its diff.", "睇返最新一個提交嘅詳情同埋佢嘅 diff。",
    "Show", "顯示", "show HEAD", keywords: "show,head,commit,提交"),
GitTweak.Git("git.diff-working", "Diff (working tree)", "差異（工作區）",
    "Show unstaged changes in the working tree.", "睇返工作區度未暫存嘅改動。",
    "Show", "顯示", "diff", keywords: "diff,working,差異,工作區"),
GitTweak.Git("git.diff-staged", "Diff (staged)", "差異（已暫存）",
    "Show changes that are staged for the next commit.", "睇返已經暫存咗、準備提交嘅改動。",
    "Show", "顯示", "diff --staged", keywords: "diff,staged,cached,差異,暫存"),
GitTweak.Git("git.diff-stat", "Diff summary", "差異摘要",
    "Show a stat summary of working tree changes.", "用 stat 摘要睇返工作區改動嘅檔名同行數。",
    "Show", "顯示", "diff --stat", keywords: "diff,stat,差異,摘要"),
GitTweak.Git("git.diff-name-only", "Diff (names only)", "差異（淨檔名）",
    "List only the names of files changed in the working tree.", "淨係列出工作區改動咗嘅檔案名。",
    "Show", "顯示", "diff --name-only", keywords: "diff,name-only,差異,檔名"),
GitTweak.Git("git.blame", "Blame a file", "追溯檔案",
    "Show line-by-line authorship for README.md.", "逐行睇返 README.md 邊個改嘅。",
    "Show", "顯示", "blame README.md", keywords: "blame,annotate,追溯,作者"),
GitTweak.Git("git.shortlog", "Contributor summary", "貢獻者摘要",
    "Summarise commits grouped and counted per author.", "按作者分組同點算返提交數目嘅摘要。",
    "Show", "顯示", "shortlog --summary --numbered --email", keywords: "shortlog,contributors,貢獻者,摘要"),
GitTweak.Git("git.describe", "Describe (tags)", "描述（標籤）",
    "Describe the current commit relative to the nearest tag.", "用最近嘅標籤嚟描述返而家呢個提交。",
    "Show", "顯示", "describe --tags --always", keywords: "describe,tag,標籤,描述"),
GitTweak.Git("git.rev-parse-head", "Resolve HEAD", "解析 HEAD",
    "Print the full commit SHA that HEAD points to.", "印返 HEAD 而家指住嗰個完整 commit SHA。",
    "Show", "顯示", "rev-parse HEAD", keywords: "rev-parse,sha,head,解析"),
GitTweak.Git("git.tag-list", "List tags", "列出標籤",
    "List all tags in the repository.", "列出倉庫入面所有標籤。",
    "List", "列出", "tag --list", keywords: "tag,list,標籤"),
GitTweak.Git("git.branch-all", "All branches", "所有分支",
    "List all local and remote branches with last commit info.", "列出所有本地同遠端分支，連埋最後提交資訊。",
    "List", "列出", "branch --all -v", keywords: "branch,all,分支,遠端"),
GitTweak.Git("git.remote-verbose", "Remotes", "遠端倉庫",
    "List configured remotes with their fetch and push URLs.", "列出設定咗嘅遠端，連埋 fetch 同 push 嘅網址。",
    "List", "列出", "remote -v", keywords: "remote,url,遠端,網址"),
GitTweak.Git("git.ls-files", "Tracked files", "已追蹤檔案",
    "List all files currently tracked by git.", "列出 git 而家追蹤緊嘅所有檔案。",
    "List", "列出", "ls-files", keywords: "ls-files,tracked,檔案,追蹤"),
GitTweak.Git("git.count-objects", "Repo object stats", "倉庫物件統計",
    "Show object count and disk usage in human-readable form.", "用易睇嘅單位顯示物件數目同埋佔咗幾多磁碟空間。",
    "Show", "顯示", "count-objects -vH", keywords: "count-objects,size,統計,物件"),
GitTweak.Git("git.reflog", "Reflog", "引用日誌",
    "Show the reference log of recent HEAD movements.", "睇返 HEAD 近排郁過邊度嘅引用日誌。",
    "Show", "顯示", "reflog -30", keywords: "reflog,history,引用,日誌"),

        // ===== stage-commit (22) =====
        GitTweak.Git("git.add-all", "Stage all changes", "暫存全部改動",
    "Stage every change including new, modified and deleted files.", "暫存晒所有改動，包括新增、修改同刪咗嘅檔案。",
    "Stage", "暫存", "add -A", keywords: "add,stage,暫存,全部"),
GitTweak.Git("git.add-update", "Stage tracked changes", "暫存已追蹤改動",
    "Stage modifications and deletions to already-tracked files only.", "淨係暫存已追蹤檔案嘅修改同刪除，唔包新檔。",
    "Stage", "暫存", "add -u", keywords: "add,update,tracked,暫存"),
GitTweak.Git("git.restore-staged-path", "Unstage a path", "取消暫存路徑",
    "Remove README.md from the staging area while keeping its changes.", "將 README.md 喺暫存區攞返出嚟，但保留住啲改動。",
    "Unstage", "取消暫存", "restore --staged README.md", keywords: "restore,unstage,staged,取消暫存"),
GitTweak.Git("git.commit-message", "Commit with message", "帶訊息提交",
    "Commit the staged changes with a sample message.", "用一個範例訊息將暫存咗嘅改動提交。",
    "Commit", "提交", "commit -m \"Update files\"", keywords: "commit,message,提交,訊息"),
GitTweak.Git("git.commit-amend", "Amend last commit", "修改上次提交",
    "Add staged changes to the previous commit, keeping its message.", "將暫存改動併入上一個提交，唔改返個訊息。",
    "Amend", "修改", "commit --amend --no-edit", destructive: true, keywords: "commit,amend,修改,提交"),
GitTweak.Git("git.commit-all", "Stage tracked and commit", "暫存並提交已追蹤",
    "Automatically stage all tracked changes then commit them.", "自動暫存晒已追蹤嘅改動，再一齊提交。",
    "Commit", "提交", "commit -a -m \"Update tracked files\"", keywords: "commit,all,提交,已追蹤"),
GitTweak.Git("git.commit-empty", "Empty commit", "空白提交",
    "Create a commit with no changes, useful as a marker.", "整一個冇任何改動嘅提交，可以做標記用。",
    "Commit", "提交", "commit --allow-empty -m \"Empty commit\"", keywords: "commit,empty,空白,提交"),
GitTweak.Git("git.reset-soft", "Soft reset one commit", "軟重置一個提交",
    "Undo the last commit but keep its changes staged.", "撤回上一個提交，但啲改動會留返喺暫存區。",
    "Reset", "重置", "reset --soft HEAD~1", destructive: true, keywords: "reset,soft,重置,撤回"),
GitTweak.Git("git.reset-mixed", "Mixed reset", "混合重置",
    "Unstage everything, keeping the changes in the working tree.", "將所有嘢取消暫存，但改動仲留喺工作區。",
    "Reset", "重置", "reset --mixed HEAD", destructive: true, keywords: "reset,mixed,重置,取消暫存"),
GitTweak.Git("git.reset-hard", "Hard reset to HEAD", "硬重置到 HEAD",
    "Discard all staged and working changes, matching HEAD exactly.", "丟棄晒所有暫存同工作區改動，完全對返 HEAD。",
    "Reset", "重置", "reset --hard HEAD", destructive: true, keywords: "reset,hard,重置,丟棄"),
GitTweak.Git("git.restore-file", "Restore a file", "還原檔案",
    "Discard working-tree changes to README.md, reverting to HEAD.", "丟棄 README.md 喺工作區嘅改動，還原返做 HEAD 版本。",
    "Restore", "還原", "restore README.md", destructive: true, keywords: "restore,discard,還原,丟棄"),
GitTweak.Git("git.checkout-dot", "Discard all working changes", "丟棄全部工作改動",
    "Revert every tracked file in the working tree back to HEAD.", "將工作區所有已追蹤檔案還原返做 HEAD。",
    "Discard", "丟棄", "checkout -- .", destructive: true, keywords: "checkout,discard,丟棄,還原"),
GitTweak.Git("git.clean-dryrun", "Preview untracked cleanup", "預覽清理未追蹤",
    "Show which untracked files and directories would be removed.", "睇下有邊啲未追蹤嘅檔案同資料夾會被清走，唔會真係刪。",
    "Preview", "預覽", "clean -nd", keywords: "clean,dry run,預覽,未追蹤"),
GitTweak.Git("git.clean-force", "Remove untracked files", "刪除未追蹤檔案",
    "Permanently delete untracked files and directories.", "永久刪除晒未追蹤嘅檔案同資料夾。",
    "Clean", "清理", "clean -fd", destructive: true, keywords: "clean,force,清理,刪除"),
GitTweak.Git("git.rm-cached", "Untrack but keep file", "取消追蹤但保留檔",
    "Stop tracking secret.txt while leaving it on disk.", "唔再追蹤 secret.txt，但個檔案仍然留喺磁碟。",
    "Untrack", "取消追蹤", "rm --cached secret.txt", keywords: "rm,cached,untrack,取消追蹤"),
GitTweak.Git("git.mv", "Move or rename file", "移動或重新命名",
    "Rename old.txt to new.txt and stage the move.", "將 old.txt 改名做 new.txt，同時暫存呢個移動。",
    "Move", "移動", "mv old.txt new.txt", keywords: "mv,move,rename,移動,改名"),
GitTweak.Git("git.stash-push", "Stash changes", "暫存擱置改動",
    "Save your current changes onto the stash with a label.", "將你而家嘅改動擱置入 stash，仲畀個標籤佢。",
    "Stash", "擱置", "stash push -m \"Work in progress\"", keywords: "stash,push,擱置,儲存"),
GitTweak.Git("git.stash-pop", "Pop latest stash", "彈出最新擱置",
    "Reapply the most recent stash and remove it from the list.", "將最新嗰個 stash 重新套返，並喺清單度移走佢。",
    "Pop", "彈出", "stash pop", destructive: true, keywords: "stash,pop,彈出,還原"),
GitTweak.Git("git.stash-list", "List stashes", "列出擱置",
    "Show all stash entries currently saved.", "睇晒而家儲低嘅所有 stash 項目。",
    "List", "列出", "stash list", keywords: "stash,list,列出,擱置"),
GitTweak.Git("git.stash-show", "Show stash diff", "顯示擱置差異",
    "Display the patch of changes in the latest stash.", "顯示最新嗰個 stash 入面啲改動嘅 patch 差異。",
    "Show", "顯示", "stash show -p", keywords: "stash,show,diff,差異,顯示"),
GitTweak.Git("git.stash-drop", "Drop a stash", "刪除一個擱置",
    "Permanently delete the most recent stash entry.", "永久刪除最新嗰個 stash 項目。",
    "Drop", "刪除", "stash drop", destructive: true, keywords: "stash,drop,刪除,擱置"),
GitTweak.Git("git.stash-clear", "Clear all stashes", "清除全部擱置",
    "Permanently remove every stash entry at once.", "一次過永久清走晒所有 stash 項目。",
    "Clear", "清除", "stash clear", destructive: true, keywords: "stash,clear,清除,全部"),

        // ===== branch-sync (25) =====
        GitTweak.Git("git.branch-list", "List branches", "列出分支",
    "List all local branches with the current one marked.", "列出所有本機分支，並標示返而家喺邊個。",
    "List", "列出", "branch", keywords: "branch,list,分支,列出"),
GitTweak.Git("git.branch-create", "Create branch", "開分支",
    "Create a new branch named 'feature' without switching to it.", "開一個叫 'feature' 嘅新分支，但係唔切換過去。",
    "Create", "建立", "branch feature", keywords: "branch,create,新分支,建立"),
GitTweak.Git("git.switch-create", "Switch to new branch", "切去新分支",
    "Create a new branch named 'feature' and switch to it right away.", "開一個叫 'feature' 嘅新分支，即刻切換埋過去。",
    "Switch", "切換", "switch -c feature", keywords: "switch,create,branch,切換,新分支"),
GitTweak.Git("git.checkout-main", "Checkout main", "切去 main",
    "Switch your working tree to the main branch.", "將工作區切返去 main 分支。",
    "Checkout", "切換", "checkout main", keywords: "checkout,main,切換"),
GitTweak.Git("git.branch-rename", "Rename branch", "改分支名",
    "Rename the current branch to 'new-name'.", "將而家嘅分支改名做 'new-name'。",
    "Rename", "改名", "branch -m new-name", keywords: "branch,rename,改名"),
GitTweak.Git("git.branch-delete", "Delete branch (safe)", "刪除分支（安全）",
    "Delete the branch 'feature' only if it is already merged.", "淨係喺 'feature' 已經合併咗先至刪除佢。",
    "Delete", "刪除", "branch -d feature", keywords: "branch,delete,刪除,安全"),
GitTweak.Git("git.branch-delete-force", "Force-delete branch", "強制刪除分支",
    "Force-delete the branch 'feature' even if it is not merged. This loses unmerged work.", "就算 'feature' 未合併都強制刪除，會整唔見未合併嘅嘢。",
    "Force delete", "強制刪除", "branch -D feature", destructive: true, keywords: "branch,delete,force,強制,刪除"),
GitTweak.Git("git.fetch-all-prune", "Fetch all & prune", "抓取全部並清理",
    "Fetch from every remote and prune deleted remote-tracking branches.", "由每個遠端抓取，並清理返已刪除嘅遠端追蹤分支。",
    "Fetch", "抓取", "fetch --all --prune", keywords: "fetch,prune,all,抓取,清理"),
GitTweak.Git("git.fetch-origin", "Fetch origin", "抓取 origin",
    "Fetch the latest objects and refs from the origin remote.", "由 origin 遠端抓取最新嘅物件同 refs。",
    "Fetch", "抓取", "fetch origin", keywords: "fetch,origin,抓取"),
GitTweak.Git("git.pull", "Pull", "拉取",
    "Fetch from the upstream and merge it into the current branch.", "由上游抓取，再合併入而家嘅分支。",
    "Pull", "拉取", "pull", keywords: "pull,merge,拉取"),
GitTweak.Git("git.pull-rebase", "Pull with rebase", "拉取並變基",
    "Fetch from the upstream and rebase the current branch on top of it.", "由上游抓取，再將而家嘅分支變基喺佢上面。",
    "Pull rebase", "拉取變基", "pull --rebase", destructive: true, keywords: "pull,rebase,拉取,變基"),
GitTweak.Git("git.push", "Push", "推送",
    "Push the current branch's commits to its upstream remote.", "將而家分支嘅提交推送去佢嘅上游遠端。",
    "Push", "推送", "push", keywords: "push,推送"),
GitTweak.Git("git.push-set-upstream", "Push & set upstream", "推送並設上游",
    "Push the current branch to origin and set it as the upstream.", "將而家嘅分支推送去 origin，並設返做上游。",
    "Push", "推送", "push -u origin HEAD", keywords: "push,upstream,origin,推送,上游"),
GitTweak.Git("git.push-tags", "Push tags", "推送標籤",
    "Push all local tags to the origin remote.", "將所有本機標籤推送去 origin 遠端。",
    "Push tags", "推送標籤", "push --tags", keywords: "push,tags,標籤,推送"),
GitTweak.Git("git.push-force-with-lease", "Force-push (with lease)", "強制推送（租約）",
    "Force-push using --force-with-lease so you don't clobber others' work unexpectedly.", "用 --force-with-lease 強制推送，避免唔小心覆蓋咗人哋啲嘢。",
    "Force push", "強制推送", "push --force-with-lease", destructive: true, keywords: "push,force,lease,強制,推送"),
GitTweak.Git("git.remote-v", "List remotes", "列出遠端",
    "List configured remotes with their fetch and push URLs.", "列出已設定嘅遠端，連埋佢哋嘅抓取同推送網址。",
    "List", "列出", "remote -v", keywords: "remote,list,遠端,列出"),
GitTweak.Git("git.remote-add-origin", "Add origin remote", "新增 origin 遠端",
    "Add a remote named 'origin' pointing at the given URL.", "新增一個叫 'origin' 嘅遠端，指住所提供嘅網址。",
    "Add", "新增", "remote add origin https://github.com/user/repo.git", keywords: "remote,add,origin,遠端,新增"),
GitTweak.Git("git.remote-show-origin", "Show origin", "顯示 origin",
    "Show detailed information about the origin remote.", "顯示返 origin 遠端嘅詳細資料。",
    "Show", "顯示", "remote show origin", keywords: "remote,show,origin,遠端,顯示"),
GitTweak.Git("git.remote-set-url", "Set remote URL", "設定遠端網址",
    "Change the URL of the origin remote to a new one.", "將 origin 遠端嘅網址改去一個新嘅。",
    "Set URL", "設定網址", "remote set-url origin https://github.com/user/repo.git", keywords: "remote,set-url,url,遠端,網址"),
GitTweak.Git("git.merge-no-ff", "Merge (no fast-forward)", "合併（唔快轉）",
    "Merge the 'feature' branch creating a merge commit even if fast-forward is possible.", "合併 'feature' 分支，就算可以快轉都照整個合併提交出嚟。",
    "Merge", "合併", "merge --no-ff feature", keywords: "merge,no-ff,合併"),
GitTweak.Git("git.merge-abort", "Abort merge", "中止合併",
    "Abort an in-progress merge and restore the pre-merge state.", "中止進行緊嘅合併，還原返合併之前嘅狀態。",
    "Abort", "中止", "merge --abort", destructive: true, keywords: "merge,abort,中止,合併"),
GitTweak.Git("git.rebase-main", "Rebase onto main", "變基到 main",
    "Rebase the current branch on top of main, rewriting its commits.", "將而家嘅分支變基喺 main 上面，會改寫返佢啲提交。",
    "Rebase", "變基", "rebase main", destructive: true, keywords: "rebase,main,變基"),
GitTweak.Git("git.rebase-abort", "Abort rebase", "中止變基",
    "Abort an in-progress rebase and restore the original branch.", "中止進行緊嘅變基，還原返原本嘅分支。",
    "Abort", "中止", "rebase --abort", destructive: true, keywords: "rebase,abort,中止,變基"),
GitTweak.Git("git.cherry-pick", "Cherry-pick commit", "揀摘提交",
    "Apply the changes from a given commit onto the current branch.", "將指定提交嘅改動套用喺而家嘅分支上面。",
    "Cherry-pick", "揀摘", "cherry-pick COMMIT_SHA", destructive: true, keywords: "cherry-pick,commit,揀摘,提交"),
GitTweak.Git("git.revert-no-edit", "Revert commit", "還原提交",
    "Create a new commit that undoes a given commit, without opening an editor.", "整一個新提交去撤銷指定嘅提交，唔使開編輯器。",
    "Revert", "還原", "revert --no-edit COMMIT_SHA", destructive: true, keywords: "revert,no-edit,還原,提交"),

        // ===== maintenance-tags (20) =====
        GitTweak.Git("git.tag-list", "List tags", "列出標籤",
    "Show every tag in the repository.", "列返 repo 入面所有標籤。",
    "List", "列出", "tag --list", keywords: "tag,list,標籤"),
GitTweak.Git("git.tag-annotated", "Create annotated tag", "建立附註標籤",
    "Create an annotated tag v1.0.0 with a message.", "建立一個附註標籤 v1.0.0，仲加埋訊息。",
    "Tag", "標籤", "tag -a v1.0.0 -m \"Release v1.0.0\"", keywords: "tag,annotate,附註,標籤"),
GitTweak.Git("git.tag-delete", "Delete tag", "刪除標籤",
    "Delete the local tag v1.0.0.", "刪除咗本地標籤 v1.0.0。",
    "Delete", "刪除", "tag -d v1.0.0", destructive: true, keywords: "tag,delete,刪除,標籤"),
GitTweak.Git("git.tag-push", "Push a tag", "推送標籤",
    "Push tag v1.0.0 to the origin remote.", "將標籤 v1.0.0 推送去 origin。",
    "Push", "推送", "push origin v1.0.0", keywords: "tag,push,推送,標籤"),
GitTweak.Git("git.config-list", "List config", "列出設定",
    "Show all effective git configuration values.", "顯示返所有生效咗嘅 git 設定。",
    "List", "列出", "config --list", keywords: "config,list,設定"),
GitTweak.Git("git.config-username", "Show user.name", "顯示 user.name",
    "Show the configured user.name value.", "睇返設定咗嘅 user.name。",
    "Show", "顯示", "config user.name", keywords: "config,user,name,名"),
GitTweak.Git("git.config-useremail", "Show user.email", "顯示 user.email",
    "Show the configured user.email value.", "睇返設定咗嘅 user.email。",
    "Show", "顯示", "config user.email", keywords: "config,user,email,電郵"),
GitTweak.Git("git.config-editor", "Show core.editor", "顯示 core.editor",
    "Show the configured core.editor value.", "睇返設定咗嘅 core.editor。",
    "Show", "顯示", "config core.editor", keywords: "config,editor,編輯器"),
GitTweak.Git("git.gc", "Garbage collect", "垃圾回收",
    "Clean up and optimise the local repository.", "清理同埋優化本地 repo。",
    "Run", "執行", "gc", keywords: "gc,garbage,清理,優化"),
GitTweak.Git("git.gc-aggressive", "Aggressive gc", "進取垃圾回收",
    "Aggressively repack and prune objects now.", "進取咁重新打包，同埋即刻 prune 物件。",
    "Run", "執行", "gc --aggressive --prune=now", destructive: true, keywords: "gc,aggressive,prune,清理"),
GitTweak.Git("git.fsck-full", "Check integrity", "檢查完整性",
    "Run a full consistency check on all objects.", "對所有物件做完整嘅一致性檢查。",
    "Check", "檢查", "fsck --full", keywords: "fsck,check,完整性,檢查"),
GitTweak.Git("git.repack", "Repack objects", "重新打包物件",
    "Repack all objects into a single pack.", "將所有物件重新打包成一個 pack。",
    "Repack", "打包", "repack -ad", keywords: "repack,pack,打包"),
GitTweak.Git("git.prune-verbose", "Prune objects", "清除物件",
    "Prune unreachable objects and list what is removed.", "清除接觸唔到嘅物件，仲列返刪咗乜。",
    "Prune", "清除", "prune -v", destructive: true, keywords: "prune,清除,unreachable"),
GitTweak.Git("git.reflog-expire", "Expire reflog", "清空 reflog",
    "Expire all reflog entries immediately.", "即刻清空晒所有 reflog 紀錄。",
    "Expire", "清空", "reflog expire --expire=now --all", destructive: true, keywords: "reflog,expire,清空"),
GitTweak.Git("git.archive-zip", "Archive to zip", "封存做 zip",
    "Export HEAD as a zip archive named repo.zip.", "將 HEAD 匯出做一個叫 repo.zip 嘅封存檔。",
    "Archive", "封存", "archive -o repo.zip HEAD", keywords: "archive,zip,封存"),
GitTweak.Git("git.bundle-all", "Create bundle", "建立 bundle",
    "Bundle the entire repository into repo.bundle.", "將成個 repo 打包做 repo.bundle。",
    "Bundle", "打包", "bundle create repo.bundle --all", keywords: "bundle,封包,備份"),
GitTweak.Git("git.worktree-list", "List worktrees", "列出工作樹",
    "List all linked working trees.", "列返所有連結咗嘅工作樹。",
    "List", "列出", "worktree list", keywords: "worktree,list,工作樹"),
GitTweak.Git("git.worktree-prune", "Prune worktrees", "清理工作樹",
    "Prune stale working tree administrative files.", "清理返冇用嘅工作樹管理檔案。",
    "Prune", "清理", "worktree prune", keywords: "worktree,prune,清理,工作樹"),
GitTweak.Git("git.submodule-status", "Submodule status", "子模組狀態",
    "Show the status of each submodule.", "顯示返每個子模組嘅狀態。",
    "Show", "顯示", "submodule status", keywords: "submodule,status,子模組"),
GitTweak.Git("git.submodule-update-init", "Init & update submodules", "初始化同更新子模組",
    "Initialise and recursively update all submodules.", "初始化，仲遞迴咁更新晒所有子模組。",
    "Update", "更新", "submodule update --init --recursive", keywords: "submodule,update,init,子模組"),

        // ===== gh-cli (20) =====
        GitTweak.Tool("git.gh-auth-status", "GitHub auth status", "GitHub 登入狀態",
    "Check who you are logged in as via the GitHub CLI.", "用 GitHub CLI 睇返你而家登入咗邊個身份。",
    "Check", "查睇", "gh", "auth status", keywords: "auth,login,登入,身份,gh"),
GitTweak.Tool("git.gh-repo-view", "View repository", "睇個 Repo",
    "Show details of the current repository.", "顯示而家呢個 repo 嘅資料。",
    "View", "查睇", "gh", "repo view", keywords: "repo,view,資料,gh"),
GitTweak.Tool("git.gh-repo-view-web", "Open repo in browser", "喺瀏覽器開 Repo",
    "Open the current repository on GitHub in your browser.", "喺瀏覽器度開返呢個 repo 嘅 GitHub 頁面。",
    "Open", "開啟", "gh", "repo view --web", keywords: "repo,web,browser,瀏覽器,gh"),
GitTweak.Tool("git.gh-pr-list", "List pull requests", "列出 PR",
    "List open pull requests for this repository.", "列出呢個 repo 開緊嘅 PR。",
    "List", "列出", "gh", "pr list", keywords: "pr,pull request,列出,gh"),
GitTweak.Tool("git.gh-pr-status", "Pull request status", "PR 狀態",
    "Show the status of pull requests relevant to you.", "睇返同你有關嘅 PR 嘅狀態。",
    "Show", "顯示", "gh", "pr status", keywords: "pr,status,狀態,gh"),
GitTweak.Tool("git.gh-pr-view", "View current PR", "睇目前 PR",
    "View the pull request associated with the current branch.", "睇返同而家呢條分支有關嘅 PR。",
    "View", "查睇", "gh", "pr view", keywords: "pr,view,分支,gh"),
GitTweak.Tool("git.gh-issue-list-all", "List all issues", "列出所有 Issue",
    "List issues in every state for this repository.", "列出呢個 repo 所有狀態嘅 issue。",
    "List", "列出", "gh", "issue list --state all", keywords: "issue,all,所有,gh"),
GitTweak.Tool("git.gh-issue-status", "Issue status", "Issue 狀態",
    "Show the status of issues relevant to you.", "睇返同你有關嘅 issue 嘅狀態。",
    "Show", "顯示", "gh", "issue status", keywords: "issue,status,狀態,gh"),
GitTweak.Tool("git.gh-release-list", "List releases", "列出 Release",
    "List releases published for this repository.", "列出呢個 repo 出咗嘅 release。",
    "List", "列出", "gh", "release list", keywords: "release,list,版本,gh"),
GitTweak.Tool("git.gh-release-view", "View latest release", "睇最新 Release",
    "View details of the latest release.", "睇返最新一個 release 嘅詳情。",
    "View", "查睇", "gh", "release view", keywords: "release,view,版本,gh"),
GitTweak.Tool("git.gh-run-list", "List workflow runs", "列出工作流程執行",
    "List recent GitHub Actions workflow runs.", "列出近排 GitHub Actions 嘅工作流程執行記錄。",
    "List", "列出", "gh", "run list", keywords: "run,actions,workflow,執行,gh"),
GitTweak.Tool("git.gh-gist-list", "List gists", "列出 Gist",
    "List your gists via the GitHub CLI.", "用 GitHub CLI 列出你嘅 gist。",
    "List", "列出", "gh", "gist list", keywords: "gist,list,gh"),
GitTweak.Tool("git.gh-workflow-list", "List workflows", "列出工作流程",
    "List the GitHub Actions workflows in this repository.", "列出呢個 repo 嘅 GitHub Actions 工作流程。",
    "List", "列出", "gh", "workflow list", keywords: "workflow,actions,工作流程,gh"),
GitTweak.Tool("git.gh-api-user", "Your GitHub profile", "你嘅 GitHub 資料",
    "Fetch your authenticated user profile from the GitHub API.", "用 GitHub API 攞返你登入帳號嘅資料。",
    "Fetch", "攞返", "gh", "api user", keywords: "api,user,profile,資料,gh"),
GitTweak.Tool("git.gh-label-list", "List labels", "列出標籤",
    "List the labels defined in this repository.", "列出呢個 repo 入面定義咗嘅標籤。",
    "List", "列出", "gh", "label list", keywords: "label,list,標籤,gh"),
GitTweak.Tool("git.gh-search-prs-me", "My pull requests", "我開嘅 PR",
    "Search across GitHub for pull requests you authored.", "喺成個 GitHub 度搵返你開嘅 PR。",
    "Search", "搜尋", "gh", "search prs --author=@me", keywords: "search,pr,author,me,gh"),
GitTweak.Tool("git.gh-cache-list", "List Actions caches", "列出 Actions 快取",
    "List the GitHub Actions caches for this repository.", "列出呢個 repo 嘅 GitHub Actions 快取。",
    "List", "列出", "gh", "cache list", keywords: "cache,actions,快取,gh"),
GitTweak.Tool("git.gh-ruleset-list", "List rulesets", "列出規則集",
    "List the rulesets configured for this repository.", "列出呢個 repo 設定咗嘅規則集。",
    "List", "列出", "gh", "ruleset list", keywords: "ruleset,rules,規則,gh"),
GitTweak.Tool("git.gh-secret-list", "List secrets", "列出密鑰",
    "List the names of secrets set for this repository.", "列出呢個 repo 設定咗嘅密鑰名稱。",
    "List", "列出", "gh", "secret list", keywords: "secret,list,密鑰,gh"),
GitTweak.Tool("git.gh-status", "GitHub status", "GitHub 狀態",
    "Show what is going on across GitHub for you right now.", "睇返你而家喺 GitHub 各處嘅最新狀況。",
    "Show", "顯示", "gh", "status", keywords: "status,狀態,gh"),
    };
}