using System;
using System.Collections.Generic;
using Microsoft.Win32;
using WinTune.Models;
using WinTune.Services;

namespace WinTune.Catalog;

/// <summary>
/// 維護與診斷操作 · Maintenance &amp; diagnostics operations (services, disk, integrity, drivers, reports).
/// 由 ultracode workflow 產生並對抗式覆核。Generated + adversarially reviewed via an ultracode workflow.
/// </summary>
public static class MaintenanceTweaks
{
    public static IEnumerable<TweakDefinition> All() => new List<TweakDefinition>
    {
        // ===== services (22) =====
Tweak.Powershell("maint.list-running-services", "List running services", "列出運行緊嘅服務",
        "Show every service that is currently running.", "顯示而家運行緊嘅所有服務。",
        "List", "列出", "Get-Service | Where-Object Status -eq 'Running' | Sort-Object DisplayName | Select-Object Status,Name,DisplayName | Format-Table -Auto | Out-String", keywords: "service,running,服務,運行"),

    Tweak.Powershell("maint.list-auto-stopped", "Auto services that are stopped", "自動但已停咗嘅服務",
        "List services set to start automatically but currently stopped.", "列出設定咗自動啟動但而家停咗嘅服務。",
        "List", "列出", "Get-CimInstance Win32_Service | Where-Object { $_.StartMode -eq 'Auto' -and $_.State -ne 'Running' } | Select-Object Name,DisplayName,State | Format-Table -Auto | Out-String", keywords: "service,auto,stopped,自動,停咗"),

    Tweak.Powershell("maint.list-auto-services", "List automatic services", "列出自動啟動嘅服務",
        "List all services configured to start automatically.", "列出所有設定咗自動啟動嘅服務。",
        "List", "列出", "Get-CimInstance Win32_Service | Where-Object StartMode -eq 'Auto' | Select-Object Name,DisplayName,State | Sort-Object DisplayName | Format-Table -Auto | Out-String", keywords: "service,auto,自動,服務"),

    Tweak.Powershell("maint.restart-spooler", "Restart Print Spooler", "重啟列印多工緩衝處理器",
        "Restart the Print Spooler service.", "重啟 Print Spooler 列印服務。",
        "Restart", "重啟", "Restart-Service -Name Spooler -Force; Get-Service Spooler | Out-String", requiresAdmin: true, keywords: "print,spooler,列印,打印"),

    Tweak.Powershell("maint.restart-audio", "Restart Windows Audio", "重啟 Windows 音效服務",
        "Restart the Windows Audio (audiosrv) service.", "重啟 Windows 音效 (audiosrv) 服務。",
        "Restart", "重啟", "Restart-Service -Name audiosrv -Force; Get-Service audiosrv | Out-String", requiresAdmin: true, keywords: "audio,sound,音效,聲音"),

    Tweak.Powershell("maint.restart-search", "Restart Windows Search", "重啟 Windows 搜尋服務",
        "Restart the Windows Search (wsearch) indexing service.", "重啟 Windows 搜尋 (wsearch) 索引服務。",
        "Restart", "重啟", "Restart-Service -Name wsearch -Force; Get-Service wsearch | Out-String", requiresAdmin: true, keywords: "search,index,搜尋,索引"),

    Tweak.Powershell("maint.restart-explorer", "Restart Explorer", "重啟檔案總管",
        "Restart the Windows Explorer shell process.", "重啟 Windows 檔案總管外殼程序。",
        "Restart", "重啟", "Stop-Process -Name explorer -Force; Start-Sleep -Seconds 1; if (-not (Get-Process explorer -ErrorAction SilentlyContinue)) { Start-Process explorer }; 'Explorer restarted.'", restart: RestartScope.Explorer, keywords: "explorer,shell,檔案總管,桌面"),

    Tweak.Powershell("maint.restart-bits", "Restart BITS", "重啟 BITS 背景傳輸服務",
        "Restart the Background Intelligent Transfer Service.", "重啟背景智慧傳輸服務 (BITS)。",
        "Restart", "重啟", "Restart-Service -Name BITS -Force; Get-Service BITS | Out-String", requiresAdmin: true, keywords: "bits,transfer,傳輸,背景"),

    Tweak.Cmd("maint.set-diagtrack-demand", "Set DiagTrack to Manual", "將 DiagTrack 設為手動啟動",
        "Change the Connected User Experiences and Telemetry service start type to demand (manual).", "將連線使用者體驗同遙測服務 (DiagTrack) 嘅啟動類型改做手動 (demand)。",
        "Set", "設定", "sc config DiagTrack start= demand", requiresAdmin: true, keywords: "diagtrack,telemetry,遙測,手動,sc config"),

    Tweak.Cmd("maint.stop-diagtrack", "Stop DiagTrack", "停止 DiagTrack 服務",
        "Stop the Connected User Experiences and Telemetry (DiagTrack) service.", "停止連線使用者體驗同遙測 (DiagTrack) 服務。",
        "Stop", "停止", "sc stop DiagTrack", requiresAdmin: true, keywords: "diagtrack,telemetry,stop,停止,遙測"),

    Tweak.Cmd("maint.start-diagtrack", "Start DiagTrack", "啟動 DiagTrack 服務",
        "Start the Connected User Experiences and Telemetry (DiagTrack) service.", "啟動連線使用者體驗同遙測 (DiagTrack) 服務。",
        "Start", "啟動", "sc start DiagTrack", requiresAdmin: true, keywords: "diagtrack,telemetry,start,啟動,遙測"),

    Tweak.Cmd("maint.query-spooler", "Query a service", "查詢服務狀態",
        "Query the current state of the Print Spooler service.", "查詢 Print Spooler 服務嘅目前狀態。",
        "Query", "查詢", "sc query Spooler", keywords: "sc query,service,查詢,狀態"),

    Tweak.Cmd("maint.list-scheduled-tasks", "List scheduled tasks", "列出排程工作",
        "List all scheduled tasks with verbose detail.", "詳細列出所有排程工作。",
        "List", "列出", "schtasks /query /fo LIST /v", keywords: "schtasks,scheduled,排程,工作"),

    Tweak.Cmd("maint.run-task", "Run a scheduled task", "執行排程工作",
        "Run a named scheduled task on demand (edit the task path as needed).", "即時執行指定名稱嘅排程工作（按需要改工作路徑）。",
        "Run", "執行", "schtasks /run /tn \"\\Microsoft\\Windows\\Defrag\\ScheduledDefrag\"", requiresAdmin: true, keywords: "schtasks,run,執行,排程"),

    Tweak.Powershell("maint.list-autostart", "List startup programs", "列出開機自動啟動程式",
        "List programs configured to start automatically at logon.", "列出登入時自動啟動嘅程式。",
        "List", "列出", "Get-CimInstance Win32_StartupCommand | Select-Object Name,Command,Location,User | Format-Table -Auto | Out-String", keywords: "startup,autostart,開機,啟動,自動"),

    Tweak.Cmd("maint.reset-update-services", "Reset Windows Update services", "重置 Windows Update 服務",
        "Stop and restart the Windows Update, BITS and Cryptographic services.", "停止再重啟 Windows Update、BITS 同密碼編譯服務。",
        "Reset", "重置", "net stop wuauserv && net stop bits && net stop cryptsvc && net start wuauserv && net start bits && net start cryptsvc", requiresAdmin: true, destructive: true, keywords: "windows update,wuauserv,bits,cryptsvc,更新,重置"),

    Tweak.Shell("maint.open-services-msc", "Open Services", "開啟服務管理員",
        "Open the Services management console (services.msc).", "開啟服務管理主控台 (services.msc)。",
        "Open", "開啟", "mmc.exe", "services.msc", keywords: "services.msc,console,服務,管理員"),

    Tweak.Shell("maint.open-task-scheduler", "Open Task Scheduler", "開啟工作排程器",
        "Open the Task Scheduler console (taskschd.msc).", "開啟工作排程器主控台 (taskschd.msc)。",
        "Open", "開啟", "mmc.exe", "taskschd.msc", keywords: "taskschd.msc,scheduler,排程,工作"),

    Tweak.Shell("maint.open-startup-apps", "Open Startup apps settings", "開啟開機應用程式設定",
        "Open the Startup apps page in Windows Settings.", "喺 Windows 設定度開啟開機應用程式版面。",
        "Open", "開啟", "explorer.exe", "ms-settings:startupapps", keywords: "startup,settings,開機,設定,應用程式"),

    Tweak.Powershell("maint.restart-dnscache", "Restart DNS Client", "重啟 DNS 用戶端服務",
        "Restart the DNS Client (dnscache) service.", "重啟 DNS 用戶端 (dnscache) 服務。",
        "Restart", "重啟", "Restart-Service -Name dnscache -Force; Get-Service dnscache | Out-String", requiresAdmin: true, keywords: "dns,dnscache,client,用戶端,網域"),

    Tweak.Powershell("maint.restart-w32time", "Restart Windows Time + resync", "重啟 Windows 時間並同步",
        "Restart the Windows Time (w32time) service and resynchronise the clock.", "重啟 Windows 時間 (w32time) 服務再同步時鐘。",
        "Restart", "重啟", "Restart-Service -Name w32time -Force; w32tm /resync 2>&1 | Out-String", requiresAdmin: true, keywords: "time,w32time,resync,時間,同步"),

    Tweak.Powershell("maint.flush-spooler-queue", "Flush + restart spooler queue", "清空並重啟列印佇列",
        "Stop the spooler, clear the pending print queue, then restart it.", "停止多工緩衝處理器、清走等緊嘅列印佇列，再重啟。",
        "Flush", "清空", "Stop-Service Spooler -Force; Remove-Item \"$env:SystemRoot\\System32\\spool\\PRINTERS\\*\" -Force -ErrorAction SilentlyContinue; Start-Service Spooler; 'Spooler queue flushed.'", requiresAdmin: true, destructive: true, keywords: "spooler,queue,print,佇列,列印,清空"),

        // ===== disk (22) =====
Tweak.Cmd("maint.disk-chkdsk-readonly", "Check disk (read-only)", "檢查磁碟（唯讀）",
        "Run chkdsk on C: in read-only mode to report errors without changing anything.", "用唯讀模式喺 C: 行 chkdsk，淨係報告錯誤唔會改嘢。",
        "Check", "檢查", "chkdsk C:", keywords: "chkdsk,disk,check,磁碟,檢查"),
    Tweak.Cmd("maint.disk-chkdsk-fix", "Schedule full check & repair", "排程完整檢查同修復",
        "Schedule chkdsk /f to fix errors on C: at the next reboot.", "排程 chkdsk /f 喺下次重開機時修復 C: 嘅錯誤。",
        "Schedule", "排程", "echo Y| chkdsk C: /f", requiresAdmin: true, destructive: true, restart: RestartScope.Reboot, keywords: "chkdsk,repair,fix,修復,磁碟"),
    Tweak.Powershell("maint.disk-optimize", "Optimize / defrag C:", "最佳化／重組 C:",
        "Run Optimize-Volume on C: to defrag HDDs or retrim SSDs as appropriate, with verbose output.", "喺 C: 行 Optimize-Volume，HDD 會重組、SSD 會 retrim，顯示詳細過程。",
        "Optimize", "最佳化", "Optimize-Volume -DriveLetter C -Verbose | Out-String", requiresAdmin: true, keywords: "optimize,defrag,retrim,重組,最佳化"),
    Tweak.Powershell("maint.disk-physical-health", "Physical disk health", "實體磁碟健康",
        "Show each physical disk's media type, health and operational status.", "顯示每個實體磁碟嘅媒體類型、健康同運作狀態。",
        "Show", "顯示", "Get-PhysicalDisk | Select-Object FriendlyName,MediaType,HealthStatus,OperationalStatus | Format-Table -Auto | Out-String", keywords: "physical disk,health,健康,磁碟"),
    Tweak.Powershell("maint.disk-reliability", "Storage reliability counters", "儲存可靠性計數器",
        "Read SMART-style reliability counters (temperature, wear, read/write errors) for each disk.", "讀取每個磁碟嘅可靠性計數器（溫度、磨損、讀寫錯誤），類似 SMART。",
        "Show", "顯示", "Get-PhysicalDisk | Get-StorageReliabilityCounter | Format-List | Out-String", keywords: "reliability,smart,counter,可靠性,磁碟"),
    Tweak.Powershell("maint.disk-repair-scan", "Scan volume for errors", "掃描磁碟區錯誤",
        "Run Repair-Volume -Scan on C: to check the filesystem online without fixing.", "喺 C: 行 Repair-Volume -Scan，線上檢查檔案系統但唔會修復。",
        "Scan", "掃描", "Repair-Volume -DriveLetter C -Scan | Out-String", requiresAdmin: true, keywords: "repair,scan,volume,掃描,磁碟區"),
    Tweak.Powershell("maint.disk-repair-spotfix", "Spot-fix volume errors", "即時修復磁碟區錯誤",
        "Run Repair-Volume -SpotFix on C: to quickly fix logged corruption.", "喺 C: 行 Repair-Volume -SpotFix，快速修復記錄到嘅損毀。",
        "Spot Fix", "即時修復", "Repair-Volume -DriveLetter C -SpotFix | Out-String", requiresAdmin: true, destructive: true, keywords: "repair,spotfix,修復,磁碟區"),
    Tweak.Cmd("maint.disk-dirty-query", "Query dirty bit", "查詢污染位元",
        "Check whether C: is flagged dirty and needs a chkdsk at boot.", "睇吓 C: 係咪畀人標記咗污染、開機時要行 chkdsk。",
        "Query", "查詢", "fsutil dirty query C:", keywords: "dirty,fsutil,污染,磁碟"),
    Tweak.Cmd("maint.disk-free", "Volume free space", "磁碟區可用空間",
        "Show total, free and available bytes on C: via fsutil.", "用 fsutil 顯示 C: 嘅總容量、可用同剩餘位元組。",
        "Show", "顯示", "fsutil volume diskfree C:", keywords: "free,space,diskfree,空間,磁碟"),
    Tweak.Cmd("maint.disk-shadows", "List shadow copies", "列出陰影複本",
        "List all Volume Shadow Copy (System Restore) snapshots.", "列出所有磁碟區陰影複本（系統還原）快照。",
        "List", "列出", "vssadmin list shadows", requiresAdmin: true, keywords: "vss,shadow,restore,陰影,快照"),
    Tweak.Cmd("maint.disk-shadowstorage", "Shadow storage usage", "陰影儲存用量",
        "Show how much space is reserved and used by shadow copies.", "顯示陰影複本預留同用咗幾多空間。",
        "Show", "顯示", "vssadmin list shadowstorage", requiresAdmin: true, keywords: "vss,shadowstorage,陰影,空間"),
    Tweak.Powershell("maint.disk-get-disk", "List disks", "列出磁碟",
        "List all disks with their size, partition style and health status.", "列出所有磁碟連同容量、分割區樣式同健康狀態。",
        "Show", "顯示", "Get-Disk | Select-Object Number,FriendlyName,@{n='SizeGB';e={[math]::Round($_.Size/1GB,1)}},PartitionStyle,HealthStatus | Format-Table -Auto | Out-String", keywords: "disk,get-disk,磁碟"),
    Tweak.Powershell("maint.disk-get-partition", "List partitions", "列出分割區",
        "List all partitions with drive letter, type and size.", "列出所有分割區連同磁碟機代號、類型同容量。",
        "Show", "顯示", "Get-Partition | Select-Object DiskNumber,PartitionNumber,DriveLetter,Type,@{n='SizeGB';e={[math]::Round($_.Size/1GB,1)}} | Format-Table -Auto | Out-String", keywords: "partition,分割區,磁碟"),
    Tweak.Powershell("maint.disk-get-volume", "List volumes", "列出磁碟區",
        "List all volumes with filesystem, health and free space.", "列出所有磁碟區連同檔案系統、健康同可用空間。",
        "Show", "顯示", "Get-Volume | Select-Object DriveLetter,FileSystemLabel,FileSystem,HealthStatus,@{n='FreeGB';e={[math]::Round($_.SizeRemaining/1GB,1)}},@{n='SizeGB';e={[math]::Round($_.Size/1GB,1)}} | Format-Table -Auto | Out-String", keywords: "volume,磁碟區,空間"),
    Tweak.Powershell("maint.disk-largest-folders", "Largest folders in Users", "Users 最大嘅資料夾",
        "Measure each top-level folder under C:\\Users and show the largest first.", "量度 C:\\Users 下每個頂層資料夾，由最大嘅排先。",
        "Analyze", "分析", "Get-ChildItem 'C:\\Users' -Directory -Force -ErrorAction SilentlyContinue | ForEach-Object { [PSCustomObject]@{ Folder=$_.Name; SizeGB=[math]::Round((Get-ChildItem $_.FullName -Recurse -File -Force -ErrorAction SilentlyContinue | Measure-Object Length -Sum).Sum/1GB,2) } } | Sort-Object SizeGB -Descending | Format-Table -Auto | Out-String", keywords: "size,folder,users,大細,資料夾"),
    Tweak.Cmd("maint.disk-component-cleanup", "Clean up component store", "清理元件儲存區",
        "Run DISM StartComponentCleanup to remove superseded WinSxS components.", "行 DISM StartComponentCleanup，移除畀人取代咗嘅 WinSxS 元件。",
        "Clean Up", "清理", "Dism.exe /Online /Cleanup-Image /StartComponentCleanup", requiresAdmin: true, destructive: true, keywords: "dism,winsxs,cleanup,清理,元件"),
    Tweak.Cmd("maint.disk-analyze-store", "Analyze component store", "分析元件儲存區",
        "Run DISM AnalyzeComponentStore to report WinSxS size and whether cleanup is recommended.", "行 DISM AnalyzeComponentStore，報告 WinSxS 大細同係咪建議清理。",
        "Analyze", "分析", "Dism.exe /Online /Cleanup-Image /AnalyzeComponentStore", requiresAdmin: true, keywords: "dism,winsxs,analyze,分析,元件"),
    Tweak.Shell("maint.disk-mgmt", "Open Disk Management", "開磁碟管理",
        "Launch the Disk Management console (diskmgmt.msc).", "開啟磁碟管理主控台（diskmgmt.msc）。",
        "Open", "開啟", "diskmgmt.msc", "", keywords: "disk management,diskmgmt,磁碟管理"),
    Tweak.Shell("maint.disk-dfrgui", "Open Optimize Drives", "開最佳化磁碟機",
        "Launch the Optimize Drives (defragment) tool.", "開啟最佳化磁碟機（重組）工具。",
        "Open", "開啟", "dfrgui.exe", "", keywords: "defrag,optimize,dfrgui,重組,最佳化"),
    Tweak.Powershell("maint.disk-retrim", "ReTrim SSD", "重新 TRIM SSD",
        "Send TRIM/ReTrim commands to C: so the SSD can reclaim free blocks.", "向 C: 發出 TRIM/ReTrim 指令，等 SSD 可以回收空閒區塊。",
        "ReTrim", "重新修整", "Optimize-Volume -DriveLetter C -ReTrim -Verbose | Out-String", requiresAdmin: true, keywords: "trim,retrim,ssd,修整"),
    Tweak.Cmd("maint.disk-8dot3-query", "Query 8.3 name creation", "查詢 8.3 短檔名建立",
        "Show whether 8dot3 short filename creation is enabled on C:.", "顯示 C: 係咪開咗 8dot3 短檔名建立。",
        "Query", "查詢", "fsutil 8dot3name query C:", keywords: "8dot3,shortname,fsutil,短檔名"),
    Tweak.Cmd("maint.disk-fsinfo", "Filesystem info", "檔案系統資訊",
        "Show NTFS filesystem details and capabilities for C: via fsutil fsinfo.", "用 fsutil fsinfo 顯示 C: 嘅 NTFS 檔案系統詳情同功能。",
        "Show", "顯示", "fsutil fsinfo ntfsinfo C:", keywords: "fsinfo,ntfs,fsutil,檔案系統"),

        // ===== integrity (22) =====
Tweak.Cmd("maint.sfc-scannow", "Run System File Checker", "執行系統檔案檢查 (SFC)",
        "Scan and repair protected system files.", "掃描同修復受保護嘅系統檔案。",
        "Scan & Repair", "掃描修復", "sfc /scannow", requiresAdmin: true, keywords: "sfc,system file checker,系統檔案,修復"),
    Tweak.Cmd("maint.sfc-verifyonly", "Verify system files only", "淨係驗證系統檔案",
        "Scan protected system files without repairing them.", "淨係掃描受保護嘅系統檔案，唔做修復。",
        "Verify", "驗證", "sfc /verifyonly", requiresAdmin: true, keywords: "sfc,verify,驗證,系統檔案"),
    Tweak.Cmd("maint.dism-checkhealth", "DISM check health", "DISM 快速檢查健康",
        "Quickly check if the component store is flagged as corrupt.", "快速睇下組件存放區有冇被標記為損壞。",
        "Check", "檢查", "DISM /Online /Cleanup-Image /CheckHealth", requiresAdmin: true, keywords: "dism,checkhealth,健康,組件"),
    Tweak.Cmd("maint.dism-scanhealth", "DISM scan health", "DISM 深入掃描健康",
        "Run a deeper scan of the component store for corruption.", "深入掃描組件存放區有冇損壞。",
        "Scan", "掃描", "DISM /Online /Cleanup-Image /ScanHealth", requiresAdmin: true, keywords: "dism,scanhealth,掃描,組件"),
    Tweak.Cmd("maint.dism-restorehealth", "DISM restore health", "DISM 修復健康",
        "Repair the Windows component store using Windows Update.", "用 Windows Update 修復 Windows 組件存放區。",
        "Restore", "修復", "DISM /Online /Cleanup-Image /RestoreHealth", requiresAdmin: true, keywords: "dism,restorehealth,修復,組件"),
    Tweak.Powershell("maint.create-restore-point", "Create restore point", "建立還原點",
        "Create a system restore point named WinTune.", "建立一個叫 WinTune 嘅系統還原點。",
        "Create", "建立", "Checkpoint-Computer -Description 'WinTune' -RestorePointType 'MODIFY_SETTINGS'", requiresAdmin: true, keywords: "restore point,checkpoint,還原點"),
    Tweak.Powershell("maint.list-restore-points", "List restore points", "列出還原點",
        "Show all available system restore points.", "列出所有可用嘅系統還原點。",
        "List", "列出", "Get-ComputerRestorePoint | Select-Object SequenceNumber,Description,RestorePointType,CreationTime | Format-Table -Auto | Out-String", keywords: "restore point,還原點,列出"),
    Tweak.Powershell("maint.enable-system-protection", "Enable System Protection", "開啟系統保護",
        "Turn on System Protection for the C: drive so restore points can be created.", "為 C: 碟開啟系統保護，等可以建立還原點。",
        "Enable", "開啟", "Enable-ComputerRestore -Drive 'C:\\'", requiresAdmin: true, keywords: "system protection,enable,系統保護,還原"),
    Tweak.Cmd("maint.wu-startscan", "Scan for Windows Updates", "掃描 Windows 更新",
        "Trigger Windows Update to check for new updates.", "叫 Windows Update 即刻掃描有冇新更新。",
        "Scan", "掃描", "UsoClient StartScan", keywords: "windows update,usoclient,scan,更新,掃描"),
    Tweak.Cmd("maint.wu-startdownload", "Download Windows Updates", "下載 Windows 更新",
        "Start downloading available Windows Updates.", "開始下載可用嘅 Windows 更新。",
        "Download", "下載", "UsoClient StartDownload", keywords: "windows update,usoclient,download,更新,下載"),
    Tweak.Cmd("maint.wu-startinstall", "Install Windows Updates", "安裝 Windows 更新",
        "Start installing downloaded Windows Updates.", "開始安裝已下載嘅 Windows 更新。",
        "Install", "安裝", "UsoClient StartInstall", keywords: "windows update,usoclient,install,更新,安裝"),
    Tweak.Powershell("maint.list-hotfixes", "List installed updates", "列出已安裝更新",
        "Show the 30 most recently installed updates and hotfixes.", "列出最近安裝嘅 30 個更新同修補程式。",
        "List", "列出", "Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 30 HotFixID,Description,InstalledOn | Format-Table -Auto | Out-String", keywords: "hotfix,updates,kb,更新,修補"),
    Tweak.Powershell("maint.pending-reboot", "Check pending reboot", "檢查待重啟",
        "Check registry keys to see if a reboot is pending.", "睇下登錄機碼，檢查係咪有更新等緊重啟。",
        "Check", "檢查", "$p = (Test-Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Component Based Servicing\\RebootPending') -or (Test-Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update\\RebootRequired'); if ($p) { 'Reboot is PENDING' } else { 'No reboot pending' }", keywords: "pending reboot,restart,待重啟,重啟"),
    Tweak.Cmd("maint.clear-update-cache", "Clear Windows Update cache", "清除更新快取",
        "Stop the update service and delete the SoftwareDistribution download cache.", "停止更新服務，再刪除 SoftwareDistribution 下載快取。",
        "Clear", "清除", "net stop wuauserv && rd /s /q \"%SystemRoot%\\SoftwareDistribution\\Download\" && net start wuauserv", requiresAdmin: true, destructive: true, keywords: "update cache,softwaredistribution,wuauserv,更新快取,清除"),
    Tweak.Powershell("maint.recent-critical-events", "Recent critical & error events", "近期嚴重同錯誤事件",
        "List the 30 most recent critical and error events from the System log.", "列出系統記錄最近 30 條嚴重同錯誤事件。",
        "Show", "顯示", "Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2} -MaxEvents 30 | Select-Object TimeCreated,Id,LevelDisplayName,ProviderName,Message | Format-Table -Auto | Out-String", keywords: "events,critical,error,system log,事件,錯誤"),
    Tweak.Cmd("maint.clear-system-log", "Clear System event log", "清除系統事件記錄",
        "Permanently clear all entries in the System event log.", "永久清除系統事件記錄入面嘅所有項目。",
        "Clear", "清除", "wevtutil cl System", requiresAdmin: true, destructive: true, keywords: "event log,wevtutil,clear,system,事件記錄,清除"),
    Tweak.Cmd("maint.clear-application-log", "Clear Application event log", "清除應用程式記錄",
        "Permanently clear all entries in the Application event log.", "永久清除應用程式事件記錄入面嘅所有項目。",
        "Clear", "清除", "wevtutil cl Application", requiresAdmin: true, destructive: true, keywords: "event log,wevtutil,clear,application,事件記錄,清除"),
    Tweak.Cmd("maint.export-system-log", "Export System event log", "匯出系統事件記錄",
        "Export the System event log to a .evtx file on the desktop.", "將系統事件記錄匯出做 .evtx 檔案，放喺桌面。",
        "Export", "匯出", "wevtutil epl System \"%USERPROFILE%\\Desktop\\System-log.evtx\"", requiresAdmin: true, keywords: "event log,wevtutil,export,evtx,事件記錄,匯出"),
    Tweak.Info("maint.open-event-viewer", "Event Viewer", "事件檢視器",
        "Now built in — use the in-app Event Viewer module (System/Application/Security/Setup logs, no eventvwr.msc).",
        "已經內建 — 用 app 內嘅事件檢視器模組（System/Application/Security/Setup 記錄，唔使 eventvwr.msc）。",
        () => "→ Event Viewer · 事件檢視器", "event viewer,eventvwr,事件檢視器,log,記錄"),
    Tweak.Shell("maint.reliability-monitor", "Open Reliability Monitor", "開可靠性監視器",
        "Launch the Reliability Monitor to review system stability history.", "開啟可靠性監視器，睇返系統穩定性歷史。",
        "Open", "開啟", "perfmon.exe", "/rel", keywords: "reliability monitor,perfmon,可靠性,監視器"),
    Tweak.Shell("maint.open-windows-update-settings", "Open Windows Update settings", "開 Windows Update 設定",
        "Open the Windows Update page in Settings.", "喺設定度開啟 Windows Update 頁面。",
        "Open", "開啟", "ms-settings:windowsupdate", "", keywords: "windows update,ms-settings,settings,更新,設定"),
    Tweak.Shell("maint.open-msinfo", "Open System Information", "開系統資訊",
        "Launch System Information (msinfo32) for a full hardware and software summary.", "開啟系統資訊 (msinfo32)，睇晒硬件同軟件摘要。",
        "Open", "開啟", "msinfo32.exe", "", keywords: "msinfo32,system information,系統資訊"),

        // ===== drivers (18) =====
Tweak.Powershell("maint.drivers.list-thirdparty", "List third-party drivers", "列出第三方驅動程式",
        "Enumerate all non-Microsoft (third-party) driver packages installed in the driver store.", "列出所有非 Microsoft（即係第三方）嘅驅動程式套件。",
        "List", "列出", "pnputil /enum-drivers", requiresAdmin: true, keywords: "pnputil,drivers,third-party,驅動,第三方"),

    Tweak.Cmd("maint.drivers.driverquery", "Detailed driver query", "詳細驅動程式清單",
        "Show a verbose table of all installed drivers, their type, state and start mode.", "用表格詳細列出所有已安裝嘅驅動程式、類型、狀態同啟動模式。",
        "Show", "顯示", "driverquery /v /fo table", keywords: "driverquery,drivers,驅動,清單"),

    Tweak.Powershell("maint.drivers.problem-devices", "Devices with errors", "有錯誤嘅裝置",
        "List all devices currently reporting an error status in Device Manager.", "列出所有喺裝置管理員入面報緊錯誤狀態嘅裝置。",
        "Show", "顯示", "Get-PnpDevice -Status Error | Format-Table -Auto FriendlyName,Class,Status,InstanceId | Out-String", keywords: "pnp,error,problem,裝置,錯誤,問題"),

    Tweak.Powershell("maint.drivers.display-adapters", "List display adapters", "列出顯示卡",
        "List all display adapter devices (graphics cards) and their status.", "列出所有顯示卡裝置同佢哋嘅狀態。",
        "Show", "顯示", "Get-PnpDevice -Class Display | Format-Table -Auto FriendlyName,Status,InstanceId | Out-String", keywords: "display,gpu,adapter,顯示卡,顯示"),

    Tweak.Powershell("maint.drivers.disk-drives", "List disk drives", "列出磁碟機",
        "List all disk drive devices and their current status.", "列出所有磁碟機裝置同佢哋而家嘅狀態。",
        "Show", "顯示", "Get-PnpDevice -Class DiskDrive | Format-Table -Auto FriendlyName,Status,InstanceId | Out-String", keywords: "disk,drive,storage,磁碟,硬碟"),

    Tweak.Cmd("maint.drivers.scan-hardware", "Scan for hardware changes", "掃描硬件變更",
        "Trigger Windows to re-scan the system for new or changed hardware devices.", "叫 Windows 重新掃描成個系統有冇新加或者改咗嘅硬件裝置。",
        "Scan", "掃描", "pnputil /scan-devices", requiresAdmin: true, keywords: "pnputil,scan,hardware,掃描,硬件"),

    Tweak.Shell("maint.drivers.device-manager", "Open Device Manager", "開啟裝置管理員",
        "Launch the Device Manager console to view and manage hardware devices.", "開啟裝置管理員嚟睇同管理硬件裝置。",
        "Open", "開啟", "mmc.exe", "devmgmt.msc", keywords: "device manager,devmgmt,裝置管理員"),

    Tweak.Powershell("maint.drivers.net-adapters", "List network adapters", "列出網絡卡",
        "List all network adapters with their status, link speed and MAC address.", "列出所有網絡卡同佢哋嘅狀態、連線速度同 MAC 位址。",
        "Show", "顯示", "Get-NetAdapter | Format-Table -Auto Name,InterfaceDescription,Status,LinkSpeed,MacAddress | Out-String", keywords: "network,adapter,netadapter,網絡卡,網絡"),

    Tweak.Powershell("maint.drivers.restart-net-adapters", "Restart active network adapters", "重啟使用緊嘅網絡卡",
        "Restart all network adapters that are currently up. This briefly drops connectivity.", "重啟所有而家開緊嘅網絡卡，過程中網絡會短暫斷開。",
        "Restart", "重啟", "Get-NetAdapter | Where-Object Status -eq 'Up' | Restart-NetAdapter -Confirm:$false; 'Active network adapters restarted.'", requiresAdmin: true, keywords: "restart,netadapter,network,重啟,網絡卡"),

    Tweak.Powershell("maint.drivers.usb-devices", "List USB devices", "列出 USB 裝置",
        "List all USB devices connected to the system and their status.", "列出所有駁喺系統上面嘅 USB 裝置同佢哋嘅狀態。",
        "Show", "顯示", "Get-PnpDevice -Class USB | Format-Table -Auto FriendlyName,Status,InstanceId | Out-String", keywords: "usb,device,USB,裝置"),

    Tweak.Powershell("maint.drivers.export-list", "Export driver list to file", "匯出驅動清單去檔案",
        "Export the full third-party driver list to a text file on your Desktop.", "將完整嘅第三方驅動清單匯出去你桌面嘅一個文字檔。",
        "Export", "匯出", "$out = Join-Path ([Environment]::GetFolderPath('Desktop')) 'DriverList.txt'; pnputil /enum-drivers | Out-File -FilePath $out -Encoding UTF8; \"Saved driver list to $out\"", requiresAdmin: true, keywords: "export,driver,list,file,匯出,驅動,檔案"),

    Tweak.Powershell("maint.drivers.signed-drivers", "Signed drivers (top 30)", "已簽署驅動（頭 30 個）",
        "Show the first 30 signed PnP drivers with device name, version and provider.", "列出頭 30 個已簽署嘅 PnP 驅動，包括裝置名、版本同供應商。",
        "Show", "顯示", "Get-CimInstance Win32_PnPSignedDriver | Select-Object -First 30 DeviceName,DriverVersion,DriverProviderName | Format-Table -Auto | Out-String", keywords: "signed,driver,pnp,簽署,驅動"),

    Tweak.Powershell("maint.drivers.audio-devices", "List audio devices", "列出音效裝置",
        "List all media/audio class devices and their status.", "列出所有媒體／音效類別嘅裝置同佢哋嘅狀態。",
        "Show", "顯示", "Get-PnpDevice -Class Media | Format-Table -Auto FriendlyName,Status,InstanceId | Out-String", keywords: "audio,media,sound,音效,聲音"),

    Tweak.Powershell("maint.drivers.problem-count", "Count devices with problems", "數有問題嘅裝置",
        "Show how many devices are currently in an error state.", "顯示而家有幾多個裝置處於錯誤狀態。",
        "Count", "數", "$n = (Get-PnpDevice -Status Error | Measure-Object).Count; \"Devices with problems: $n\"", keywords: "problem,count,error,問題,數量"),

    Tweak.Powershell("maint.drivers.gpu-info", "GPU information", "顯示卡資料",
        "Show detailed information about installed video controllers (GPUs).", "顯示已安裝嘅顯示卡（GPU）嘅詳細資料。",
        "Show", "顯示", "Get-CimInstance Win32_VideoController | Format-List Name,DriverVersion,AdapterRAM,VideoProcessor,CurrentHorizontalResolution,CurrentVerticalResolution | Out-String", keywords: "gpu,video,graphics,顯示卡,顯卡"),

    Tweak.Powershell("maint.drivers.monitor-info", "Monitor information", "顯示器資料",
        "Show information about connected desktop monitors.", "顯示駁住嘅顯示器嘅資料。",
        "Show", "顯示", "Get-CimInstance Win32_DesktopMonitor | Format-Table -Auto Name,MonitorManufacturer,ScreenWidth,ScreenHeight | Out-String", keywords: "monitor,display,顯示器,螢幕"),

    Tweak.Shell("maint.drivers.sound-settings", "Open Sound settings", "開啟音效設定",
        "Open the Windows sound settings page.", "開啟 Windows 嘅音效設定頁面。",
        "Open", "開啟", "explorer.exe", "ms-settings:sound", keywords: "sound,settings,音效,設定"),

    Tweak.Powershell("maint.drivers.printers", "List printers", "列出打印機",
        "List all printers installed on this system with their status and driver.", "列出呢部機裝咗嘅所有打印機，連狀態同驅動。",
        "Show", "顯示", "Get-Printer | Format-Table -Auto Name,DriverName,PortName,PrinterStatus | Out-String", keywords: "printer,打印機,印表機"),

        // ===== diagnostics (18) =====
Tweak.Cmd("maint.energy-report", "Energy efficiency report", "電源效率報告",
        "Run a 60-second power-efficiency trace and save an HTML report on the Desktop.", "做一次 60 秒嘅電源效率追蹤,儲存成 HTML 報告喺桌面。",
        "Run", "執行", "powercfg /energy /output \"%USERPROFILE%\\Desktop\\energy-report.html\"", requiresAdmin: true, keywords: "powercfg,energy,power,電源,能源"),
    Tweak.Cmd("maint.battery-report", "Battery report", "電池報告",
        "Generate an HTML battery health and usage report on the Desktop.", "整一份 HTML 電池健康同使用報告喺桌面。",
        "Generate", "產生", "powercfg /batteryreport /output \"%USERPROFILE%\\Desktop\\battery-report.html\"", keywords: "powercfg,battery,電池,報告"),
    Tweak.Cmd("maint.sleep-study", "Sleep study report", "睡眠研究報告",
        "Generate a Modern Standby sleep-study HTML report on the Desktop.", "整一份新式待機 (Modern Standby) 睡眠研究 HTML 報告喺桌面。",
        "Generate", "產生", "powercfg /sleepstudy /output \"%USERPROFILE%\\Desktop\\sleepstudy.html\"", requiresAdmin: true, keywords: "powercfg,sleepstudy,sleep,睡眠,待機"),
    Tweak.Cmd("maint.system-power-report", "System power report", "系統電源報告",
        "Generate a detailed system power (SoC) diagnostics HTML report on the Desktop.", "整一份詳細嘅系統電源 (SoC) 診斷 HTML 報告喺桌面。",
        "Generate", "產生", "powercfg /systempowerreport /output \"%USERPROFILE%\\Desktop\\systempower.html\"", requiresAdmin: true, keywords: "powercfg,systempowerreport,power,電源,診斷"),
    Tweak.Cmd("maint.power-requests", "Active power requests", "目前嘅電源請求",
        "List apps and drivers currently preventing sleep or display-off.", "列出而家阻止系統瞓覺或者熄屏嘅程式同驅動。",
        "Show", "顯示", "powercfg /requests", requiresAdmin: true, keywords: "powercfg,requests,sleep,電源,瞓覺"),
    Tweak.Cmd("maint.last-wake", "Last wake source", "上次喚醒嘅來源",
        "Show what last woke the computer from a sleep state.", "睇下上次係咩嘢將部電腦由睡眠狀態喚醒。",
        "Show", "顯示", "powercfg /lastwake", keywords: "powercfg,lastwake,wake,喚醒,睡眠"),
    Tweak.Cmd("maint.wake-armed-devices", "Devices armed to wake", "可以喚醒系統嘅裝置",
        "List devices currently allowed to wake the system.", "列出而家容許喚醒系統嘅裝置。",
        "Show", "顯示", "powercfg /devicequery wake_armed", keywords: "powercfg,wake_armed,device,喚醒,裝置"),
    Tweak.Cmd("maint.systeminfo", "System information", "系統資訊",
        "Show OS, BIOS, memory and hotfix summary for this PC.", "顯示呢部電腦嘅作業系統、BIOS、記憶體同更新摘要。",
        "Show", "顯示", "systeminfo", keywords: "systeminfo,system,系統,資訊"),
    Tweak.Shell("maint.msinfo32", "Open System Information", "開系統資訊工具",
        "Launch the graphical System Information (msinfo32) tool.", "開圖形化嘅系統資訊 (msinfo32) 工具。",
        "Open", "開啟", "msinfo32.exe", "", keywords: "msinfo32,system information,系統資訊"),
    Tweak.Shell("maint.dxdiag", "Open DirectX Diagnostics", "開 DirectX 診斷工具",
        "Launch the DirectX Diagnostic Tool (dxdiag) for display and audio info.", "開 DirectX 診斷工具 (dxdiag) 睇顯示同音效資料。",
        "Open", "開啟", "dxdiag.exe", "", keywords: "dxdiag,directx,顯示,音效,診斷"),
    Tweak.Powershell("maint.computer-info", "Computer info summary", "電腦資訊摘要",
        "Show a quick subset of Windows, BIOS and CPU details.", "顯示 Windows、BIOS 同 CPU 嘅重點資料。",
        "Show", "顯示", "Get-ComputerInfo -Property WindowsProductName,WindowsVersion,OsArchitecture,BiosManufacturer,BiosVersion,CsManufacturer,CsModel,CsProcessors,CsTotalPhysicalMemory | Format-List | Out-String", keywords: "computerinfo,system,系統,資訊"),
    Tweak.Shell("maint.perfmon", "Open Performance Monitor", "開效能監視器",
        "Launch Performance Monitor for live counters and data collector sets.", "開效能監視器睇即時計數器同資料收集組。",
        "Open", "開啟", "perfmon.exe", "", keywords: "perfmon,performance monitor,效能,監視器"),
    Tweak.Shell("maint.resmon", "Open Resource Monitor", "開資源監視器",
        "Launch Resource Monitor to watch CPU, disk, network and memory live.", "開資源監視器即時睇 CPU、磁碟、網絡同記憶體。",
        "Open", "開啟", "resmon.exe", "", keywords: "resmon,resource monitor,資源,監視器"),
    Tweak.Powershell("maint.test-net", "Test internet connectivity", "測試上網連線",
        "Ping 1.1.1.1 and report latency and reachability.", "Ping 1.1.1.1 睇下延遲同通唔通。",
        "Test", "測試", "Test-NetConnection -ComputerName 1.1.1.1 -InformationLevel Detailed | Out-String", keywords: "test-netconnection,ping,network,網絡,連線"),
    Tweak.Cmd("maint.display-dns", "Show DNS cache", "顯示 DNS 快取",
        "Display the contents of the local DNS resolver cache.", "顯示本機 DNS 解析快取嘅內容。",
        "Show", "顯示", "ipconfig /displaydns", keywords: "ipconfig,displaydns,dns,快取,網絡"),
    Tweak.Powershell("maint.top-memory", "Top processes by memory", "記憶體用得最多嘅程序",
        "List the 15 processes using the most working-set memory.", "列出工作集記憶體用得最多嘅 15 個程序。",
        "Show", "顯示", "Get-Process | Sort-Object WS -Descending | Select-Object -First 15 Name,@{n='WS(MB)';e={[math]::Round($_.WS/1MB,1)}},Id | Format-Table -Auto | Out-String", keywords: "memory,process,記憶體,程序"),
    Tweak.Powershell("maint.uptime", "Uptime and last boot", "開機時間同上次啟動",
        "Show the last boot time and how long the system has been running.", "顯示上次啟動時間同系統開咗機幾耐。",
        "Show", "顯示", "$os = Get-CimInstance Win32_OperatingSystem; $boot = $os.LastBootUpTime; [PSCustomObject]@{ LastBoot = $boot; Uptime = ((Get-Date) - $boot).ToString() } | Format-List | Out-String", keywords: "uptime,lastboot,boot,開機,啟動"),
    Tweak.Powershell("maint.thermal-zone", "Thermal zone temperature", "熱區溫度",
        "Read ACPI thermal-zone temperatures (converted to Celsius).", "讀取 ACPI 熱區溫度 (轉做攝氏)。",
        "Show", "顯示", "Get-CimInstance -Namespace root/wmi -ClassName MSAcpi_ThermalZoneTemperature | Select-Object InstanceName,@{n='TempC';e={[math]::Round(($_.CurrentTemperature/10)-273.15,1)}} | Format-Table -Auto | Out-String", keywords: "thermal,temperature,acpi,溫度,熱"),
    };
}
