using System.Collections.Generic;
using WinTune.Models;

namespace WinTune.Catalog;

/// <summary>
/// 媒體操作目錄（ffmpeg/ffprobe，喺選中嘅檔執行）。
/// Catalog of 60 real ffmpeg/ffprobe operations on the selected media file.
/// 由 ultracode workflow 產生並對抗式覆核。
/// </summary>
public static class MediaOperations
{
    public static IEnumerable<TweakDefinition> All() => new List<TweakDefinition>
    {
        // ===== video (12) =====
MediaTweak.Op("media.video.to-mp4-h264", "Convert to MP4 (H.264)", "轉做 MP4 (H.264)",
    "Re-encode to MP4 with H.264 video and AAC audio.", "重新編碼做 H.264 影片同 AAC 聲嘅 MP4 喇。",
    "Convert", "轉換", "-i {in} -c:v libx264 -c:a aac -movflags +faststart {out}", keywords: "mp4,h264,convert,video,轉換,影片"),
MediaTweak.Op("media.video.to-mp4-h265", "Convert to MP4 (H.265/HEVC)", "轉做 MP4 (H.265/HEVC)",
    "Re-encode to MP4 with H.265/HEVC video and AAC audio for smaller files.", "用 H.265/HEVC 重新編碼做 MP4，檔案細啲嚟。",
    "Convert", "轉換", "-i {in} -c:v libx265 -c:a aac -tag:v hvc1 -movflags +faststart {out}", keywords: "mp4,h265,hevc,libx265,video,轉換,影片"),
MediaTweak.Op("media.video.to-webm-vp9", "Convert to WebM (VP9)", "轉做 WebM (VP9)",
    "Re-encode to WebM with VP9 video and Opus audio.", "重新編碼做 VP9 影片同 Opus 聲嘅 WebM 呀。",
    "Convert", "轉換", "-i {in} -c:v libvpx-vp9 -b:v 0 -crf 31 -c:a libopus {out}", keywords: "webm,vp9,opus,video,轉換,影片"),
MediaTweak.Op("media.video.to-mkv", "Convert to MKV", "轉做 MKV",
    "Re-encode to a Matroska MKV with H.264 video and AAC audio.", "重新編碼做 H.264 影片同 AAC 聲嘅 MKV 啦。",
    "Convert", "轉換", "-i {in} -c:v libx264 -c:a aac {out}", keywords: "mkv,matroska,h264,video,轉換,影片"),
MediaTweak.Op("media.video.to-mov", "Convert to MOV", "轉做 MOV",
    "Re-encode to a QuickTime MOV with H.264 video and AAC audio.", "重新編碼做 H.264 影片同 AAC 聲嘅 QuickTime MOV 喇。",
    "Convert", "轉換", "-i {in} -c:v libx264 -c:a aac -movflags +faststart {out}", keywords: "mov,quicktime,h264,video,轉換,影片"),
MediaTweak.Op("media.video.to-avi", "Convert to AVI", "轉做 AVI",
    "Re-encode to an AVI with MPEG-4 video and MP3 audio.", "重新編碼做 MPEG-4 影片同 MP3 聲嘅 AVI 呀。",
    "Convert", "轉換", "-i {in} -c:v mpeg4 -qscale:v 4 -c:a libmp3lame -q:a 4 {out}", keywords: "avi,mpeg4,mp3,video,轉換,影片"),
MediaTweak.Op("media.video.remux-copy-mp4", "Remux to MP4 (copy streams)", "重新封裝做 MP4 (複製串流)",
    "Repackage into MP4 without re-encoding by copying the existing streams.", "唔重新編碼，直接複製原本串流封裝做 MP4，好快㗎。",
    "Remux", "重新封裝", "-i {in} -c copy -movflags +faststart {out}", keywords: "remux,copy,mp4,nocopy,video,封裝,影片"),
MediaTweak.Op("media.video.faststart-web", "Optimise for web (faststart)", "為網頁優化 (faststart)",
    "Move the moov atom to the front for fast web streaming, without re-encoding.", "唔重新編碼，將 moov atom 搬去前面，網頁串流會快好多呀。",
    "Optimise", "優化", "-i {in} -c copy -movflags +faststart {out}", keywords: "faststart,web,moov,stream,copy,網頁,優化"),
MediaTweak.Op("media.video.set-crf-23", "Set quality (CRF 23)", "設定畫質 (CRF 23)",
    "Re-encode H.264 at CRF 23 for a balanced quality-to-size ratio.", "用 H.264 喺 CRF 23 重新編碼，畫質同檔案大細啱啱好嘅。",
    "Encode", "編碼", "-i {in} -c:v libx264 -crf 23 -c:a aac {out}", keywords: "crf,quality,23,libx264,video,畫質,編碼"),
MediaTweak.Op("media.video.set-bitrate-2m", "Set video bitrate (2 Mbps)", "設定影片位元率 (2 Mbps)",
    "Re-encode H.264 with a target video bitrate of 2 Mbps.", "用 H.264 重新編碼，影片位元率設做 2 Mbps 呀。",
    "Encode", "編碼", "-i {in} -c:v libx264 -b:v 2M -c:a aac {out}", keywords: "bitrate,2m,libx264,video,位元率,編碼"),
MediaTweak.Op("media.video.constant-fps-30", "Force constant 30 fps", "強制固定 30 fps",
    "Re-encode to a constant 30 frames per second with H.264 video.", "用 H.264 重新編碼成固定每秒 30 格嘅影片喇。",
    "Encode", "編碼", "-i {in} -r 30 -c:v libx264 -c:a aac {out}", keywords: "fps,30,constant,framerate,video,幀率,編碼"),
MediaTweak.Op("media.video.downscale-720p", "Downscale to 720p", "縮放做 720p",
    "Re-encode H.264 scaled down to 1280x720 while keeping the aspect ratio.", "用 H.264 重新編碼，縮細到 1280x720 同時保持比例呀。",
    "Resize", "縮放", "-i {in} -vf scale=-2:720 -c:v libx264 -crf 23 -c:a aac {out}", keywords: "scale,720p,resize,downscale,video,縮放,影片"),

        // ===== audio (12) =====
MediaTweak.Op("media.audio.extract-mp3", "Extract audio (MP3)", "抽出聲音 (MP3)",
        "Extract the audio track to an MP3 file using LAME at quality 2.", "用 LAME 質素 2 將聲道抽出做 MP3 檔。",
        "Extract", "抽出", "-i {in} -vn -c:a libmp3lame -q:a 2 {out}", keywords: "audio,mp3,extract,lame,聲音,抽出"),
    MediaTweak.Op("media.audio.extract-aac", "Extract audio (AAC)", "抽出聲音 (AAC)",
        "Extract the audio track to an AAC (.m4a) file.", "將聲道抽出做 AAC (.m4a) 檔。",
        "Extract", "抽出", "-i {in} -vn -c:a aac {out}", keywords: "audio,aac,m4a,extract,聲音,抽出"),
    MediaTweak.Op("media.audio.extract-wav", "Extract audio (WAV)", "抽出聲音 (WAV)",
        "Extract the audio track to an uncompressed 16-bit PCM WAV.", "將聲道抽出做未壓縮嘅 16-bit PCM WAV。",
        "Extract", "抽出", "-i {in} -vn -c:a pcm_s16le {out}", keywords: "audio,wav,pcm,extract,聲音,抽出"),
    MediaTweak.Op("media.audio.extract-flac", "Extract audio (FLAC)", "抽出聲音 (FLAC)",
        "Extract the audio track to a lossless FLAC file.", "將聲道抽出做無損嘅 FLAC 檔。",
        "Extract", "抽出", "-i {in} -vn -c:a flac {out}", keywords: "audio,flac,lossless,extract,無損,聲音,抽出"),
    MediaTweak.Op("media.audio.extract-opus", "Extract audio (Opus)", "抽出聲音 (Opus)",
        "Extract the audio track to an Opus file using libopus.", "用 libopus 將聲道抽出做 Opus 檔。",
        "Extract", "抽出", "-i {in} -vn -c:a libopus {out}", keywords: "audio,opus,libopus,extract,聲音,抽出"),
    MediaTweak.Op("media.audio.extract-ogg", "Extract audio (OGG Vorbis)", "抽出聲音 (OGG Vorbis)",
        "Extract the audio track to an OGG Vorbis file using libvorbis.", "用 libvorbis 將聲道抽出做 OGG Vorbis 檔。",
        "Extract", "抽出", "-i {in} -vn -c:a libvorbis {out}", keywords: "audio,ogg,vorbis,libvorbis,extract,聲音,抽出"),
    MediaTweak.Op("media.audio.set-bitrate-192k", "Set audio bitrate (192k)", "設定音訊位元率 (192k)",
        "Re-encode the audio to AAC at a 192 kbps bitrate, copying any video.", "將聲音重新編碼做 192 kbps 嘅 AAC,畫面就照抄喇。",
        "Apply", "套用", "-i {in} -c:v copy -c:a aac -b:a 192k {out}", keywords: "audio,bitrate,192k,aac,位元率"),
    MediaTweak.Op("media.audio.to-mono", "Convert to mono", "轉做單聲道",
        "Downmix the audio to a single mono channel, copying any video.", "將聲音混落單一單聲道,畫面就照抄喇。",
        "Convert", "轉換", "-i {in} -c:v copy -ac 1 {out}", keywords: "audio,mono,channels,單聲道"),
    MediaTweak.Op("media.audio.sample-rate-44100", "Set sample rate (44.1 kHz)", "設定取樣率 (44.1 kHz)",
        "Resample the audio to a 44100 Hz sample rate, copying any video.", "將聲音重新取樣到 44100 Hz,畫面就照抄喇。",
        "Apply", "套用", "-i {in} -c:v copy -ar 44100 {out}", keywords: "audio,sample rate,44100,44.1khz,取樣率"),
    MediaTweak.Op("media.audio.normalize-loudness", "Normalize loudness", "正規化響度",
        "Normalize perceived loudness using the EBU R128 loudnorm filter.", "用 EBU R128 loudnorm 濾鏡將響度正規化喇。",
        "Normalize", "正規化", "-i {in} -af loudnorm {out}", keywords: "audio,normalize,loudnorm,ebu r128,loudness,響度"),
    MediaTweak.Op("media.audio.volume-up", "Change volume (+50%)", "調整音量 (+50%)",
        "Boost the audio volume to 150% using the volume filter.", "用 volume 濾鏡將音量推到 150% 咁。",
        "Apply", "套用", "-i {in} -af volume=1.5 {out}", keywords: "audio,volume,gain,1.5,音量"),
    MediaTweak.Op("media.audio.remove", "Remove audio (mute)", "移除聲音 (靜音)",
        "Strip out the audio track entirely, leaving video only.", "將聲道完全去走,淨返畫面咋。",
        "Remove", "移除", "-i {in} -c:v copy -an {out}", keywords: "audio,mute,remove,strip,靜音,移除"),

        // ===== edit (12) =====
MediaTweak.Op("media.trim-first-30s", "Trim first 30 seconds", "剪頭 30 秒",
        "Keep only the first 30 seconds of the file.", "淨係留住個檔頭 30 秒嘅內容。",
        "Trim", "剪裁", "-i {in} -t 30 -c copy {out}", keywords: "trim,cut,duration,剪裁,30秒"),
    MediaTweak.Op("media.start-at-10s", "Start at 10 seconds", "由 10 秒開始",
        "Skip the first 10 seconds and keep the rest.", "跳過頭 10 秒,留住之後嘅內容。",
        "Skip", "跳過", "-ss 10 -i {in} -c copy {out}", keywords: "seek,start,skip,offset,跳過,10秒"),
    MediaTweak.Op("media.cut-range", "Cut range (5s–15s)", "截取片段 (5 至 15 秒)",
        "Keep only the segment from 5s to 15s.", "淨係留住 5 秒到 15 秒嗰段。",
        "Cut", "截取", "-ss 00:00:05 -to 00:00:15 -i {in} -c copy {out}", keywords: "cut,range,segment,clip,截取,片段"),
    MediaTweak.Op("media.scale-1080p", "Scale to 1080p", "縮放到 1080p",
        "Resize the video to 1080 pixels tall, keeping aspect ratio.", "將影片縮放到 1080 像素高,保持比例。",
        "Scale", "縮放", "-i {in} -vf scale=-2:1080 -c:a copy {out}", keywords: "scale,resize,1080p,resolution,縮放,解像度"),
    MediaTweak.Op("media.scale-720p", "Scale to 720p", "縮放到 720p",
        "Resize the video to 720 pixels tall, keeping aspect ratio.", "將影片縮放到 720 像素高,保持比例。",
        "Scale", "縮放", "-i {in} -vf scale=-2:720 -c:a copy {out}", keywords: "scale,resize,720p,resolution,縮放,解像度"),
    MediaTweak.Op("media.scale-480p", "Scale to 480p", "縮放到 480p",
        "Resize the video to 480 pixels tall, keeping aspect ratio.", "將影片縮放到 480 像素高,保持比例。",
        "Scale", "縮放", "-i {in} -vf scale=-2:480 -c:a copy {out}", keywords: "scale,resize,480p,resolution,縮放,解像度"),
    MediaTweak.Op("media.crop-center", "Crop center square", "中央裁剪做正方形",
        "Crop a centered square based on the shorter side.", "以短邊為準,喺中央裁出一個正方形。",
        "Crop", "裁剪", "-i {in} -vf crop=min(iw\\,ih):min(iw\\,ih) -c:a copy {out}", keywords: "crop,center,square,裁剪,中央"),
    MediaTweak.Op("media.rotate-90-cw", "Rotate 90° clockwise", "順時針轉 90 度",
        "Rotate the video 90 degrees clockwise.", "將影片順時針轉 90 度。",
        "Rotate", "旋轉", "-i {in} -vf transpose=1 -c:a copy {out}", keywords: "rotate,transpose,clockwise,旋轉,順時針"),
    MediaTweak.Op("media.rotate-90-ccw", "Rotate 90° counter-clockwise", "逆時針轉 90 度",
        "Rotate the video 90 degrees counter-clockwise.", "將影片逆時針轉 90 度。",
        "Rotate", "旋轉", "-i {in} -vf transpose=2 -c:a copy {out}", keywords: "rotate,transpose,counter,逆時針,旋轉"),
    MediaTweak.Op("media.hflip", "Flip horizontally", "水平翻轉",
        "Mirror the video left-to-right.", "將影片左右鏡像翻轉。",
        "Flip", "翻轉", "-i {in} -vf hflip -c:a copy {out}", keywords: "flip,hflip,mirror,horizontal,翻轉,鏡像"),
    MediaTweak.Op("media.speed-2x", "Speed up 2×", "加速 2 倍",
        "Double the playback speed of video and audio.", "將影片同聲音嘅播放速度加快一倍。",
        "Speed up", "加速", "-i {in} -vf setpts=0.5*PTS -af atempo=2.0 {out}", keywords: "speed,fast,2x,setpts,atempo,加速"),
    MediaTweak.Op("media.fps-30", "Change frame rate to 30", "改幀率做 30",
        "Re-time the video to 30 frames per second.", "將影片重新調做每秒 30 幀。",
        "Set FPS", "設定幀率", "-i {in} -r 30 -c:a copy {out}", keywords: "fps,framerate,30,frame,幀率"),

        // ===== imagegif (12) =====
MediaTweak.Op("media.gif-make", "Make GIF", "整 GIF 動圖",
        "Convert the video to a GIF at 12 fps, scaled to 480px wide.", "將影片整做 12 fps、闊 480px 嘅 GIF 動圖呀。",
        "Make GIF", "整 GIF", "-i {in} -vf \"fps=12,scale=480:-1:flags=lanczos\" {out}", keywords: "gif,animate,動圖,convert"),
    MediaTweak.Op("media.gif-hq-palette", "High-quality GIF (palette)", "高質 GIF (調色板)",
        "Make a sharper GIF using a generated colour palette at 15 fps.", "用生成嘅調色板整張 15 fps 更清嘅 GIF 出嚟呀。",
        "Make GIF", "整 GIF", "-i {in} -vf \"fps=15,scale=480:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse\" {out}", keywords: "gif,palette,quality,高質,調色板"),
    MediaTweak.Op("media.frame-at-5s", "Frame at 5 seconds", "第 5 秒嘅一格",
        "Grab a single still frame from the 5-second mark.", "喺第 5 秒嗰度抽出一格靜止畫面呀。",
        "Grab", "抽出", "-ss 5 -i {in} -frames:v 1 {out}", keywords: "frame,still,seek,截圖,第五秒"),
    MediaTweak.Op("media.thumbnail", "Extract thumbnail", "抽出縮圖",
        "Pick a representative thumbnail frame from the video.", "由條片度揀張有代表性嘅縮圖出嚟呀。",
        "Extract", "抽出", "-i {in} -vf \"thumbnail\" -frames:v 1 {out}", keywords: "thumbnail,preview,縮圖"),
    MediaTweak.Op("media.frames-every-1s", "Frames every 1 second", "每 1 秒一格",
        "Export one image per second of the video (use a pattern like out_%03d.png).", "影片每一秒導出一張圖片呀（檔名用 out_%03d.png 之類嘅樣式）。",
        "Export", "導出", "-i {in} -vf fps=1 {out}", keywords: "frames,fps,sequence,每秒,逐格"),
    MediaTweak.Op("media.to-webp", "Convert to WebP", "轉做 WebP",
        "Convert a still image or frame to the WebP format.", "將靜態圖片或者一格畫面轉做 WebP 格式呀。",
        "Convert", "轉換", "-i {in} -c:v libwebp -frames:v 1 {out}", keywords: "webp,image,convert,圖片"),
    MediaTweak.Op("media.to-animated-webp", "Convert to animated WebP", "轉做動態 WebP",
        "Make an animated WebP at 15 fps, scaled to 480px wide.", "整張 15 fps、闊 480px 嘅動態 WebP 出嚟呀。",
        "Convert", "轉換", "-i {in} -vf \"fps=15,scale=480:-1:flags=lanczos\" -c:v libwebp -loop 0 {out}", keywords: "webp,animated,動態,動圖"),
    MediaTweak.Op("media.contact-sheet", "Contact sheet", "縮圖總表",
        "Build a tiled contact sheet from sampled frames of the video.", "由影片抽樣嘅畫面砌張排版縮圖總表出嚟呀。",
        "Build", "製作", "-i {in} -vf \"select=not(mod(n\\,300)),scale=240:-1,tile=4x4\" -frames:v 1 {out}", keywords: "contact,sheet,tile,montage,總表,縮圖"),
    MediaTweak.Op("media.first-frame", "Grab first frame", "抽出第一格",
        "Capture the very first frame of the video.", "擷取條片最開頭嗰一格畫面呀。",
        "Grab", "抽出", "-i {in} -frames:v 1 {out}", keywords: "first,frame,start,第一格"),
    MediaTweak.Op("media.poster", "Poster image", "海報圖",
        "Create a poster image from the frame at the 1-second mark.", "喺第 1 秒嗰格整張海報圖出嚟做封面呀。",
        "Create", "製作", "-ss 1 -i {in} -frames:v 1 -q:v 2 {out}", keywords: "poster,cover,thumbnail,海報,封面"),
    MediaTweak.Op("media.frame-at-10s", "Frame at 10 seconds", "第 10 秒一格",
        "Grab a still frame from around the 10-second mark.", "喺大約第 10 秒嗰度抽出一格靜止畫面呀。",
        "Grab", "抽出", "-ss 10 -i {in} -frames:v 1 {out}", keywords: "frame,middle,seek,中段,截圖"),
    MediaTweak.Op("media.gif-small", "Make small GIF", "整細 GIF",
        "Convert to a compact GIF at 10 fps, scaled to 320px wide.", "轉做張細嘅 10 fps、闊 320px GIF 出嚟呀。",
        "Make GIF", "整 GIF", "-i {in} -vf \"fps=10,scale=320:-1:flags=lanczos\" {out}", keywords: "gif,small,compact,細,動圖"),

        // ===== filters (12) =====
MediaTweak.Op("media.denoise", "Denoise video", "影片降噪",
        "Reduce noise using the hqdn3d filter.", "用 hqdn3d 濾鏡減少雜訊呀。",
        "Denoise", "降噪", "-i {in} -vf hqdn3d {out}", keywords: "denoise,noise,hqdn3d,降噪,雜訊"),
    MediaTweak.Op("media.sharpen", "Sharpen video", "影片銳化",
        "Sharpen the image using the unsharp filter.", "用 unsharp 濾鏡令畫面更清晰啲。",
        "Sharpen", "銳化", "-i {in} -vf unsharp {out}", keywords: "sharpen,unsharp,銳化,清晰"),
    MediaTweak.Op("media.fade-in", "Fade in", "淡入",
        "Add a one-second fade-in at the start.", "喺開頭加一秒嘅淡入效果。",
        "Apply", "套用", "-i {in} -vf \"fade=t=in:st=0:d=1\" {out}", keywords: "fade,fade in,transition,淡入"),
    MediaTweak.Op("media.fade-out", "Fade out (3s mark)", "淡出 (第3秒)",
        "Add a one-second fade-out starting at the three-second mark.", "由第三秒開始加一秒嘅淡出效果呀。",
        "Apply", "套用", "-i {in} -vf \"fade=t=out:st=3:d=1\" {out}", keywords: "fade,fade out,transition,淡出"),
    MediaTweak.Op("media.brightness-contrast", "Brightness & contrast", "光暗同對比度",
        "Boost brightness and contrast with the eq filter.", "用 eq 濾鏡提升光度同對比度呀。",
        "Adjust", "調整", "-i {in} -vf eq=brightness=0.1:contrast=1.2 {out}", keywords: "brightness,contrast,eq,光暗,對比"),
    MediaTweak.Op("media.grayscale", "Convert to grayscale", "轉做黑白",
        "Remove colour by setting saturation to zero.", "將飽和度設做零,變做黑白畫面。",
        "Convert", "轉換", "-i {in} -vf hue=s=0 {out}", keywords: "grayscale,greyscale,black white,黑白,灰階"),
    MediaTweak.Op("media.deshake", "Stabilize (deshake)", "防震穩定",
        "Reduce camera shake using the deshake filter.", "用 deshake 濾鏡減少鏡頭震動呀。",
        "Stabilize", "穩定", "-i {in} -vf deshake {out}", keywords: "deshake,stabilize,shake,防震,穩定"),
    MediaTweak.Op("media.show-format", "Show format info", "顯示格式資訊",
        "Show container format details with ffprobe.", "用 ffprobe 顯示容器格式嘅詳情。",
        "Show", "顯示", "-hide_banner -show_format -i {in}", useProbe: true, needsOutput: false, keywords: "format,probe,container,格式,資訊"),
    MediaTweak.Op("media.show-streams", "Show stream info", "顯示串流資訊",
        "Show details of every stream with ffprobe.", "用 ffprobe 顯示每條串流嘅詳情。",
        "Show", "顯示", "-hide_banner -show_streams -i {in}", useProbe: true, needsOutput: false, keywords: "streams,probe,串流,資訊"),
    MediaTweak.Op("media.duration", "Show duration", "顯示時長",
        "Print the media duration in seconds.", "用秒數顯示媒體嘅時長呀。",
        "Show", "顯示", "-v error -show_entries format=duration -of default=nw=1 -i {in}", useProbe: true, needsOutput: false, keywords: "duration,length,時長,長度"),
    MediaTweak.Op("media.resolution", "Show resolution", "顯示解析度",
        "Print the video width and height.", "顯示影片嘅闊度同高度呀。",
        "Show", "顯示", "-v error -select_streams v:0 -show_entries stream=width,height -of csv=p=0 -i {in}", useProbe: true, needsOutput: false, keywords: "resolution,width,height,解析度,尺寸"),
    MediaTweak.Op("media.video-codec", "Show video codec", "顯示影片編碼",
        "Print the codec name of the first video stream.", "顯示第一條影片串流嘅編碼名稱。",
        "Show", "顯示", "-v error -select_streams v:0 -show_entries stream=codec_name -of default=nw=1 -i {in}", useProbe: true, needsOutput: false, keywords: "codec,video,編碼,codec_name"),
    MediaTweak.Op("media.audio-codec", "Show audio codec", "顯示聲音編碼",
        "Print the codec name of the first audio stream.", "顯示第一條聲音串流嘅編碼名稱呀。",
        "Show", "顯示", "-v error -select_streams a:0 -show_entries stream=codec_name -of default=nw=1 -i {in}", useProbe: true, needsOutput: false, keywords: "codec,audio,聲音,編碼,codec_name"),
    };
}
